### ISSUE TITLE
Styling buttons

### ISSUE THREAD

**Issue by capndave** [hodgef/simple-keyboard#1]
Hi. Can we use theme to style individual buttons? I've been unable to do so or to target the buttons themselves, and I'd love to make those buttons taller, adjust padding, etc. Thanks!

**Comment by capndave** [comment]
Ok I just changed the theme to "hg-layout-custom" and was then able to target .hg-button no problem. Thanks!

**Comment by hodgef** [comment]
Hello @capndave,

Glad you got it working!

There's definitely some improvements I would like to do in terms of customization. I put it as a todo in a "Roadmap" post:
https://github.com/hodgef/simple-keyboard/wiki/Roadmap

I think I'll start work on this and hopefully release an improvement in the next few hours. :)

Thanks for filing the issue, btw! If you see anything that you think should be improved, feel free to open a new issue.

Regards,
Francisco Hodge

**Comment by capndave** [comment]
Awesome, thanks! I was dreading making a custom keyboard so your library is
very useful. Did you just release it?

*David Thompson *
Master of Public Affairs
Data and Visualization Consultant

**Comment by hodgef** [comment]
Glad it's been useful to you! I started it back in March for a small
project. It's pretty much stable now (for my needs) so I mainly come back
and improve it whenever there's an issue, pr or feedback. :)

Have a nice one!



Francisco Hodge
*Full Stack Web Developer*

w : franciscohodge.com  e: hello@franciscohodge.com
