### ISSUE TITLE
Custom buttons? '{close}': '↓'

### ISSUE THREAD

**Issue by datnordstrom** [hodgef/simple-keyboard#10]
Just wondering if this the correct way to make custom buttons since it wasn't documented.

```javascript
const keyboardLayout = {
      default: [
        '1 2 3 4 5 6 7 8 9 0 - = {bksp}',
        'Q W E R T Y U I O P [ ] \\',
        "A S D F G H J K L ; ' {enter}",
        'Z X C V B N M , . /',
        '{space} {close}',
      ],
    };


const keyboardDisplay = {
'{close}': '↓',
}

**Comment by hodgef** [comment]
Hello @datnordstrom !

Here's the docs for the properties `layout` and `display`:

Layout:
https://github.com/hodgef/simple-keyboard#layout

Display:
https://github.com/hodgef/simple-keyboard#display

I set up some demos here that you can fork and adapt. They are linked through the Readme:
https://codesandbox.io/u/hodgef/sandboxes/1

For instance, I forked this one and adapted it to your question:
https://codesandbox.io/s/vvyvrxv29l

I think this should do it, if you have any issues feel free to respond and I'll reopen the ticket.

Regards
