### ISSUE TITLE
Prevent multiple events from firing on key press

### ISSUE THREAD

**Issue by sofiaps** [hodgef/simple-keyboard#100]
Hello there! Is there a way to prevent events from firing multiple times on key-down? Thank you in advance!

**Comment by hodgef** [comment]
Hello @sofiaps,

Could you provide an example of this happening? Are you able to reproduce this issue here?
https://codesandbox.io/s/simplekeyboardnpmdemos-f7yx8

Will reopen once I get more info.

Regards,
Francisco Hodge

**Comment by sofiaps** [comment]
@hodgef thank you for the prompt response! For example, when I click on a button and I hold it pressed, the number/letter continues to append to the input until I release the button. Is there a way to have the button triggered just once no matter how long the button is being held down?

**Comment by hodgef** [comment]
Hello @sofiaps,

Oh, that is something that is not in currently, but I can definitely release this later today.
I'll update the ticket once it's ready.

Thanks,
Francisco Hodge

**Comment by hodgef** [comment]
Hello @sofiaps,

The option `disableButtonHold` is now available as of simple-keyboard 2.23.0. Feel free to try it out!

More info:
https://github.com/hodgef/simple-keyboard/releases/tag/2.23.0

Regards,
Francisco Hodge

**Comment by sofiaps** [comment]
Hello @hodgef,

Works perfectly, thank you! :)

**Comment by neXorianus** [comment]
could you please add the typing for this property?
should be as simple as `disableButtonHold: boolean;`
