### ISSUE TITLE
Is it possible to use this keyboard with Nuxt?

### ISSUE THREAD

**Issue by just10minutes** [hodgef/simple-keyboard#101]
Hi Team,

Is there a documentation or any lead on how can we use this keyboard on Nuxt apps?

Thanks

**Comment by hodgef** [comment]
Hello @just10minutes,

Unfortunately I'm not very familiar with Nuxt and haven't been able to get the data binding right.

Here's my (failing) attempt:
https://codesandbox.io/s/codesandboxnuxt-lcyot

If you're able to get it working, I would really appreciate if you could share the fix!

Here's the Vue demo for reference:
https://codesandbox.io/s/github/hodgef/vue-simple-keyboard/tree/master/

Best,
Francisco Hodge

**Comment by mohitgir** [comment]
`<template>
  <div :class="keyboardClass" />
</template>

<script>
// import Keyboard from 'simple-keyboard'
import 'simple-keyboard/build/css/index.css'

export default {
  name: 'SimpleKeyboard',
  props: {
    keyboardClass: {
      default: 'simple-keyboard',
      type: String
    },
    // eslint-disable-next-line vue/require-default-prop
    input: {
      type: String
    }
  },
  data: () => ({
    keyboard: null
  }),
  watch: {
    input(input) {
      this.keyboard.setInput(input)
    }
  },
  mounted() {
    if (typeof window !== 'undefined') {
      import('simple-keyboard').then((KeyboardClass) => {
        const Keyboard = KeyboardClass.default
        this.keyboard = new Keyboard({
          onChange: this.onChange,
          onKeyPress: this.onKeyPress
        })
      })
    }
  },
  methods: {
    onChange(input) {
      this.$emit('onChange', input)
    },
    onKeyPress(button) {
      this.$emit('onKeyPress', button)

      /**
       * If you want to handle the shift and caps lock buttons
       */
      if (button === '{shift}' || button === '{lock}') this.handleShift()
    },
    handleShift() {
      const currentLayout = this.keyboard.options.layoutName
      const shiftToggle = currentLayout === 'default' ? 'shift' : 'default'

      this.keyboard.setOptions({
        layoutName: shiftToggle
      })
    }
  }
}
</script>


<style scoped>
</style>
`
