### ISSUE TITLE
Chinese Layout isn't working with react

### ISSUE THREAD

**Issue by elrumordelaluz** [hodgef/simple-keyboard#1020]
First of all, thanks for this cool library.

Seems that for some reason the chinese layout isn't working when using `react`.

[Here](https://codesandbox.io/s/staging-silence-1hidc?file=/src/index.js) is a sandbox switching between chinese and japanese, which works as expected.

![keyboard](https://user-images.githubusercontent.com/784056/117474500-40dc5b80-af5b-11eb-8f5d-02a43d5eab09.gif)

I am loading the `layout` from here 
```
import chineseLayout from "simple-keyboard-layouts/build/layouts/chinese"
```
and seems that [exists](https://unpkg.com/browse/simple-keyboard-layouts@3.0.67/build/layouts/chinese.js) in the last build.

I am missing something?

Thanks in advance,

**Comment by hodgef** [comment]
Hey @elrumordelaluz, what isn't working exactly? I find these sentences a bit contradictory

> Seems that for some reason the chinese layout **isn't working** when using react.
> Here is a sandbox switching between chinese and japanese, which **works as expected**.

**Comment by hodgef** [comment]
Sorry, do you mean that the candidate box doesn't appear when you try to type things like "ni" "hao" ?

I can see them on my end, just wondering what exactly you mean by "isn't working"?

![image](https://user-images.githubusercontent.com/25509135/117478154-c85ea600-af2c-11eb-8cc3-2d31d17a2a1c.png)

**Comment by elrumordelaluz** [comment]
Thank you @hodgef I think I was expecting the keyboard wit chinese characters but probably this is impossible due to language stuff I am missing. 

The suggestions works ok.
Thank you again,
