### ISSUE TITLE
Implementation of the {delete} function.

### ISSUE THREAD

**Issue by philfontaine** [hodgef/simple-keyboard#1033]
**Is your feature request related to a problem? Please describe.**

Right now, the {backspace} function is fully implemented, and even handles the cases where there is a selection in the current input.

However, the {delete} button is not implemented.

**Describe the solution you'd like**
I would want the exact same behavior for {delete} (only difference is that it deletes the next character instead of the previous one 😛)

**Describe alternatives you've considered**
I tried to implement this in userland by using setInput, but I can't seem to find a way to implement this correctly when there is a selection.

**Additional context**

**Comment by hodgef** [comment]
Hey @philfontaine,

Thanks for submitting this request. This is now available as of simple-keyboard@3.1.0, please feel free to check it out.

If you come across any issues with it, let me know and I'll fix it.

Regards,
Francisco Hodge

**Comment by philfontaine** [comment]
Thanks @hodgef it works great. really appreciated 🙏
