### ISSUE TITLE
What are the steps necessary to make a custom keyboard like this with your script?

### ISSUE THREAD

**Issue by inglesuniversal** [hodgef/simple-keyboard#1034]
We built this keyboard with css and a few svg images but it breaks really easy as you adjust the screen size.

[BEE_HIVE_KEYBOARD_STYLE](https://inglesuniversal.s3.amazonaws.com/images/SPELLING_BEE_KEYBOARD.png)

Best regards and #STAYSAFE

**Comment by hodgef** [comment]
Hey @inglesuniversal,

Can you provide a sandbox or git repository showing the issue? Unfortunately an image is not enough to debug this.

Regards,
Francisco Hodge

**Comment by inglesuniversal** [comment]
Please let me clarify the image shown above was not made using your script so I would like to know if your script has capabilities to customize the look of the keys and only make use of the alphabet in a few extra keys as the picture shows if you still need to take a look at the code please let me know but once again I made it by hand per se and without any particular library

**Comment by hodgef** [comment]
Hello @inglesuniversal,

In the example linked above you can see an implementation using simple-keyboard. Feel free to adapt it to your needs.

Regards,
Francisco Hodge

**Comment by inglesuniversal** [comment]
You've got to be kidding.... You recreated my layout from scratch using your script?

Wooooow.... Now you blew me away!!!!

You see, it's been a while since I have a bunch of issues of native keyboards on both Android and iPhone... mess up my work and web-app usability since the "weirdness" of their keyboard tends to block the view to the user or has a bunch of key that are not needed for my custom app.

Thanks so much... I'll start hanging around here more often.

Best regards and #STAYSAFE
