### ISSUE TITLE
Chrome 49 physicalKeyboardHighlight Out of service

### ISSUE THREAD

**Issue by skyunBoss** [hodgef/simple-keyboard#1035]
Chrome 49 physicalKeyboardHighlight Won't highlight

**Comment by hodgef** [comment]
Hey @skyunBoss,

Thanks for this bug report. Indeed it appears `KeyboardEvent.key` was [introduced in Chrome 51](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key#browser_compatibility).

I have added a fix in simple-keyboard@3.1.3. Feel free to check it out.

Regards,
Francisco Hodge
