### ISSUE TITLE
Keep simple-keyboard fixed at the bottom of the screen: 0px and make it responsive

### ISSUE THREAD

**Issue by inglesuniversal** [hodgef/simple-keyboard#1036]
Hi, LOVE the code I got so far.

Is there a way to keep the keyboard fixed to bottom of the page: 0px and the size of the keys, letters and the whole keyboard... keep it at 100vw (full width) and proportional height no more than 50% page height) so it adjust from small cell phones to large laptop screens (always center)

Current DEMO link:

[DEMO](https://inglesuniversal.com/keyboard/simple_keyboard.html)

FIXED LINK ABOVE JUST NOW... 11:15pm CST

Hope you can help me find a solution for maintaining the proportion of the keyboard based on the width of the device (responsive)

**Comment by hodgef** [comment]
Hello @inglesuniversal,

I think you can accomplish all of this with CSS. As noted in the previous ticket, you can take the provided demo and adapt it to your needs.

Quick note regarding tickets: If your request is generic/something you can figure out by browsing Google or StackOverflow, I suggest you try those sites instead.

Regards,
Francisco Hodge
