### ISSUE TITLE
Duplicate keyboard created instead of overriding existing one

### ISSUE THREAD

**Issue by erazmerita** [hodgef/simple-keyboard#1045]
**Simple-keyboard version** : 3.1.8

**Describe the bug** : 
When 2 keyboards is created for the same 'selector', I expected that first one will be removed (overridden).
Use case: When user click on input field and keyboard is already created from another input field then keyboard is overridden with new options for new input field without destroying previous one.

I checked keyboard options and didn't found a property which will do it, but this works fine in version 2.29.72.

**Screenshots**
![Double-initialization](https://user-images.githubusercontent.com/60657830/118831884-cbf91200-b8c8-11eb-8b6c-fa2d63490088.png)

**Comment by hodgef** [comment]
Hello @erazmerita,

You can use [`keyboard.destroy()`](https://hodgef.com/simple-keyboard/documentation/methods/destroy/) when you want to discard a simple-keyboard instance. It's pretty straightforward so I don't think this needs to be automated.

Let me know if you come across any issues with that approach.

Regards,
Francisco Hodge
