### ISSUE TITLE
How to input Chinese

### ISSUE THREAD

**Issue by shuai4983958** [hodgef/simple-keyboard#1046]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hodgef** [comment]
Hello @shuai4983958,

Check out this Pinyin layout with Candidate Box support
https://hodgef.com/simple-keyboard/demos/?d=chinese

![image](https://user-images.githubusercontent.com/25509135/119096858-1ae69a80-b9e2-11eb-9677-e217c7255efa.png)

You can also create a custom layout to fit your needs. Taking this one for example:
https://github.com/simple-keyboard/simple-keyboard-layouts/blob/master/src/lib/layouts/chinese.ts

Regards,
Francisco Hodge

**Comment by shuai4983958** [comment]
thank you,&nbsp;I will read the documentation carefully;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hodgef/simple-keyboard"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月21日(星期五) 下午3:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hodgef/simple-keyboard] How to input Chinese (#1046)





 
Hello @shuai4983958,
 
Check out this Pinyin layout with Candidate Box support
 https://hodgef.com/simple-keyboard/demos/?d=chinese
 

 
You can also create a custom layout to fit your needs. Taking this one for example:
 https://github.com/simple-keyboard/simple-keyboard-layouts/blob/master/src/lib/layouts/chinese.ts
 
Regards,
 Francisco Hodge
