### ISSUE TITLE
initial value as same as the next value not trigger onChange

### ISSUE THREAD

**Issue by Danieliverant** [hodgef/simple-keyboard#1058]
**Simple-keyboard version**
2.32.51

If my input has a value, and I want the keyboard continue to write from this value I use `.setInput(initialValue)`
but then if the value is "3" for example and the user clicks "3" again (as he want "33") 
the onChange won't fire because of this if:
`this.input[inputName] !== updatedInput`
line 415 in Keyboard.ts

a possible solution can be to remove this if or to find another way to add initial input to the keyboard.

**Comment by hodgef** [comment]
Hello @Danieliverant,

I could not reproduce this issue, here's the test sandbox:
https://codesandbox.io/s/charming-waterfall-iy3ew?file=/src/index.js

Feel free to submit a repro sandbox for this bug and I'll take a look.

Regards,
Francisco Hodge

**Comment by Danieliverant** [comment]
@hodgef I forgot to mention that happens when the element selected

repro in your sandbox: https://codesandbox.io/s/distracted-wiles-kzsu6?file=/src/index.js

**Comment by hodgef** [comment]
Hey @Danieliverant,

You're right, this is a bug. I will try to get this addressed before the end of the week if possible.

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
Hello @Danieliverant,

Sorry for the delay. I managed to fix the issue, although I might need to improve this logic in the future.

Feel free to update to 3.1.30 and give it a try. Let me know if you come across any issues.

Regards,
Francisco Hodge

**Comment by Danieliverant** [comment]
@hodgef updated and works as expected. Thank you!
