### ISSUE TITLE
How to auto show and auto hide?

### ISSUE THREAD

**Issue by paulo-coutinho** [hodgef/simple-keyboard#1125]
Hi,

Im building a web app that will run fullscreen and is only for touch devices.

How i can auto run/hide using this library and vuejs?

https://github.com/paulo-coutinho/cef-sample

Thanks.

**Comment by hodgef** [comment]
Hello @paulo-coutinho,

Please refer to this documentation article:
https://hodgef.com/simple-keyboard/questions-answers/implement-show-hide-toggling/

Regards,
Francisco Hodge

**Comment by SashoStzPakAz** [comment]
Hello,

I just want to add for people who might be struggling with the focusout or blur on the keyboard.

If you add tabindex and focusout it works!

 ```
 <SimpleKeyboard
    @onChange="onChange"
    @onKeyPress="onKeyPress"
    :input="this.$data[inputName]"
    :inputName="inputName"
    v-if="showKeyboardOnScreen"
    :theme="theme[1]"
    @focusout="hideKeyboard"
    tabindex="0"
  />
```
