### ISSUE TITLE
Keyboard integration

### ISSUE THREAD

**Issue by andrevenancio** [hodgef/simple-keyboard#113]
It would be nice to add `keyup` even listeners for development so we can quickly type stuff without having to press it.

If you have a readOnly input field and you have `keyup` even listener on the page you still may want to have the field change by injecting the e.key onto the <Keyboard /> component. right now all logic is handled internally and the onChange event changes the input field. Would be nice to add a e.key in a prop

**Comment by hodgef** [comment]
Hello @andrevenancio,

Do you mean something like this? (as in when you type, a key is pressed in simple-keyboard)

https://codesandbox.io/s/github/simple-keyboard/react-simple-keyboard-layout-keys-mapping/tree/master/

Currently there's the option `physicalKeyboardHighlight` where you'd press a key in your physical keyboard and this key would highlight in the virtual keyboard. I could add an option so it presses that key as well, like the example above, but less verbose.

I'm not sure I can work on this soon though. I will close the ticket for now, while adding it to the [Enhancement proposals list](https://github.com/hodgef/simple-keyboard/projects/3). The idea being that it can be reopened as development starts. If you would like to work on this, PRs are always welcome !

PS: I moved the ticket to the simple-keyboard repo as such a feature would be nice to have across libraries/frameworks.

Regards,
Francisco Hodge
