### ISSUE TITLE
 keyboard layout language switcher kit for simple-keyboard

### ISSUE THREAD

**Issue by e404r** [hodgef/simple-keyboard#114]
hi, I have an idea: This is a [demo github ](https://github.com/e404r/simple-keyboard-layouts-switcher) and [full Demo ](http://djfun.space/skls/index.html)

**Comment by hodgef** [comment]
Thanks a lot for this nice project @e404r,

I have included it to the following showcase:
https://franciscohodge.com/projects/simple-keyboard/implementations/

Keep up the good work !
Francisco Hodge

**Comment by e404r** [comment]
Thank you for this project
