### ISSUE TITLE
Simple Keyboard Layout Mapping Module onpointerdown is not a function

### ISSUE THREAD

**Issue by tehChromic** [hodgef/simple-keyboard#115]
**Simple-keyboard version**
latest

**Describe the bug**

TypeError: buttonElement.onpointerdown is not a function
Platform: safari and iOs chrome
Using simple_keyboard_layout_mapping module

**Screenshots**
<img width="1017" alt="Screen Shot 2019-06-20 at 4 30 32 PM" src="https://user-images.githubusercontent.com/1296288/59887658-125e3300-9379-11e9-973f-4e01dcf06578.png">

**Comment by hodgef** [comment]
Hello @tehChromic,

Does the following example work for you in your browser/OS?
https://codesandbox.io/s/github/simple-keyboard/simple-keyboard-layouts-key-mapping-module-sample/tree/master/

If it does, it means there's something different in your implementation that is causing the issue, and I would need a sandbox demo/repro of that.

I'll close the ticket for now and reopen when I get this information.

Regards,
Francisco Hodge

**Comment by tehChromic** [comment]
Hi, thanks for prompt one and pardon slow one:

Yes it appears to be an issue in that codepen:

<img width="1280" alt="Screen Shot 2019-07-01 at 4 12 58 PM" src="https://user-images.githubusercontent.com/1296288/60471915-8622fa00-9c1b-11e9-8a46-54e478fd4e56.png">

**Comment by hodgef** [comment]
Hey @tehChromic,

It seems safari doesn't support pointer events yet:
https://caniuse.com/#feat=pointer

Here's that same demo using click events:
https://codesandbox.io/s/simple-keyboard-layouts-demo-npm-m7848

Regards,
Francisco Hodge

**Comment by tehChromic** [comment]
Thanks Francisco! I suppose I could have figured that one myself and will
try to use you less.

But question: I'm implementing your excellent keyboard for a sizeable
project and may have more issues and requests. Do you prefer I create new
issues in the tracker or use this thread? I'm not sure what's better.

Thanks,
Christian

**Comment by hodgef** [comment]
Hello @tehChromic ,

Glad to hear that it works!

Feel free to create new issues as needed or reach out on [discord chat here](http://franciscohodge.com/simple-keyboard/chat/join) (whatever is easier for you). I'll do my best to respond quickly.
 
Thank you,
Francisco Hodge
