### ISSUE TITLE
SimpleKeyboard object not set to window

### ISSUE THREAD

**Issue by Nevitones** [hodgef/simple-keyboard#1157]
I'm trying to use the Simple Keyboard on a project that already uses the RequireJs 2.1.6.

But the SimpleKeyboard is not set to the window.

```javascript
window.SimpleKeyboard // returns undefined
```

It seems that the Simple Keyboard script detects that the `define` and `define.amd` are not undefined and ends up not setting the `window.SimpleKeyboard` but executing the following instead:

```javascript
define([], e)
```

Here is the example of the possible issue:
https://codepen.io/nevitones/pen/QWvqKBV?editors=1011

**Comment by hodgef** [comment]
Can you share a full repro with your requireJS logic?

I see `window.SimpleKeyboard.default` being populated without issues in the following demo:
https://playcode.io/792129/

Regards,
Francisco Hodge

**Comment by Nevitones** [comment]
Sorry, I've probably removed the line importing the requirejs script by mistake.
Please check the codepen again.

Here is the code there anyway:

HTML
```html
<html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/simple-keyboard@latest/build/css/index.css">
    </head>

    <body>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.6/require.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-keyboard@latest/build/index.js"></script>
    </body>
</html>
```

Javascript
```javascript
console.log(window.SimpleKeyboard);
```

**Comment by Nevitones** [comment]
Hey @hodgef 

I've changed the code above to load the Simple Keyboard via RequireJS and it worked as you can see:
https://codepen.io/nevitones/pen/xxdXywV?editors=1011

But now, I don't know if I was stupid by trying to embed the Simple Keyboard via script tag,
or if it should work both ways, require and script tag(with RequireJS embeded before the Simple Keyboard).

**Comment by hodgef** [comment]
I think the way you've done it in your last demo is correct. It's the way shown in the RequireJS demo:
https://requirejs.org/docs/api.html#config

In any case, glad it works now!

Regards,
Francisco Hodge
