### ISSUE TITLE
Keyboard's keys which are laid over the input filed is not responding. 

### ISSUE THREAD

**Issue by darda-ergo** [hodgef/simple-keyboard#1175]
i am using this keyboard for multiple input fields but Keyboard's keys which are laid over the input field is not responding. Rather it is focusing the input field below.

**Comment by hodgef** [comment]
Hey @darda-ergo, if you can provide a test sandbox or repo showing the issue I'd be glad to look into this.

I will reopen this ticket once that is provided. Thanks!

Regards,
Francisco Hodge
