### ISSUE TITLE
In touchscreen devices Device keybord opens and closes continuously while typing.

### ISSUE THREAD

**Issue by sagarkardani** [hodgef/simple-keyboard#1178]
**Simple-keyboard version**

-  Used demo from `preventMouseDownDefault` option
[Link](https://hodgef.com/simple-keyboard/documentation/options/preventmousedowndefault/)

**Describe the bug**

- I want to show cursor continuously and do not want to loose focus from input while typing from virtual keyboard so I used `preventMouseDownDefault: true` as shown in demo
- I was able to get desired behavior in Windows-Chrome
- In Android mobile and tablet the device keybord continuously opens and closes while typing. Is there anything else to be done to get desired behavior on touch screen devices ?
- Not tested in any iOS devices

**Screen Recording**

- Attached is the screen recording from Galaxy Tab S7 Plus

https://user-images.githubusercontent.com/60609139/128241227-43726465-3578-47fb-8f57-280b944683e1.mp4

**Comment by hodgef** [comment]
Hello @sagarkardani,

Check out the following answer
https://stackoverflow.com/questions/7610758/prevent-iphone-default-keyboard-when-focusing-an-input/65358992#65358992

Regards,
Francisco Hodge

**Comment by sagarkardani** [comment]
@hodgef

Thanks for quick reply. Now I am getting the behavior I want.

Regards,
Sagar
