### ISSUE TITLE
Demos are not working on the simple-keyboard website

### ISSUE THREAD

**Issue by x-turbo** [hodgef/simple-keyboard#1183]
for example: https://hodgef.com/simple-keyboard/editor/?d=simple-keyboard/react-simple-keyboard-hooks-multiple-inputs
tested with Chrome and Edge Browser
error in console:
![image](https://user-images.githubusercontent.com/88527004/128461450-d3d892e2-9691-4875-b6fe-723a6f1d6100.png)
![image](https://user-images.githubusercontent.com/88527004/128461429-919ed110-d991-40c0-ac96-26b92d3b08a6.png)

**Comment by hodgef** [comment]
Hello @x-turbo, it's working now :

![image](https://user-images.githubusercontent.com/25509135/128480780-a18e18fe-0a82-4e91-9621-c66f3d8e94a3.png)

Codesandbox is rather unstable sometimes. I will look into adding an error message whenever Codesandbox is down.

Regards,
Francisco Hodge
