### ISSUE TITLE
simple-keyboard accessibility

### ISSUE THREAD

**Issue by instadrew** [hodgef/simple-keyboard#1187]
My organization has need of a virtual keyboard and I have been trying to determine if simple-keyboard will work for our use case.  We need the virtual keyboard to offer accessibility for blind users who must rely on an external keyboard to interface with the virtual keyboard (including the use case of a Bluetooth hardware keyboard connected to a mobile device).  Here are some more details:

- We'll need a virtual keyboard that can switch from a standard QWERTY layout to a custom layout of math symbols and another custom layout of greek symbols.  From what I can see, this looks feasible to do with simple-keyboard (although I'm not clear why some keys in the layout documentation have curly braces around them, such as "{tab}", while others don't, such as ".com": https://hodgef.com/simple-keyboard/documentation/options/layout/
- The virtual keyboard needs to be accessible so that the keys can be navigated via the hardware keyboard Tab and Shift + Tab keys (and possibly the hardware keyboard Arrow keys), and activating each virtual key via the hardware keyboard Enter or Spacebar keys.  Since the standard QWERTY virtual keys can already be accessed via the corresponding hardware keys, this is more a requirement for the custom math and greek symbol layouts since these symbols won't correspond to actual keys on the hardware keyboard).
- It would be necessary that the Tab and Shift + Tab keystrokes not be trapped by the virtual keyboard (or could be escaped somehow) so that hardware keyboard users can use Tab and Shift + Tab to navigate to other elements on the page.

Could you please let me know if simple-keyboard would be able to support these requirements?

**Comment by hodgef** [comment]
Hello @instadrew,

I created simple-keyboard to be quite flexible and extensible, so you should be able to achieve most use-cases. I think your best bet though is to try out the keyboard with the available demos/sandboxes & docs, and to surf the issues for similar requests. If you come across any issues during implementation I'd be glad to assist.

Thanks!
Francisco Hodge
