### ISSUE TITLE
Need the strike the keys from system keyboard

### ISSUE THREAD

**Issue by Sudhakarareddyn** [hodgef/simple-keyboard#1193]
Hi, 
Am using the simple keyboard in my project it's nice and fast.
I need to strike the simple keyboard keys the same as in the keys from the system as well from the laptop/desktop keyboard. Is there anything like that? please help out on this.

**Comment by hodgef** [comment]
Hello @Sudhakarareddyn,

You can use the options `physicalKeyboardHighlight` and `physicalKeyboardHighlightPress` combined. This way, pressing your physical keyboard keys will trigger a press from simple-keyboard.

For example:
https://codesandbox.io/s/naughty-lederberg-kcym0?file=/src/index.js

Regards,
Francisco Hodge

**Comment by Sudhakarareddyn** [comment]
Hi Francisco Hodge,
   Thank you so much for the fast response,  I tried the above solution, it is working fine for English. But for other languages, it's not striking the physical keys. Is there any solution for other languages? Please let me know any solution.  

Regards,
Sudhakara N

**Comment by hodgef** [comment]
Hey @Sudhakarareddyn,

For `physicalKeyboardHighlight` to work, your pressed key needs to match what's on your simple-keyboard layout.

If your pressed key is not found in your simple-keyboard layout, it won't work. If your use-case is not satisfied by that built-in logic, you would need to create a custom module such as the following one:

https://codesandbox.io/s/github/hodgef/simple-keyboard-layout-mapping-module-v2

That demo maps one layout to another. You can take that as an example, but you would need to change it according to your needs.

> Note: For debugging, you can turn on the `debug: true` option.

Thank you,
Francisco Hodge
