### ISSUE TITLE
layoutCandidates are not shown when using Key Navigation Module

### ISSUE THREAD

**Issue by cbfrank** [hodgef/simple-keyboard#1196]
**3.2.0**
Run with latest stable simple-keyboard version.

**Describe the bug**
When using key navigation module, the layoutCandidates can be shown when user click keys by mouse, but the candidates are not shown when user user key navigation and press enter (hardware keyboard), the input is updated, but no candidates shows.
and also, the candidates can not be select by key navigation, user have to use touch or mouse click to select them.

Thanks

**Comment by hodgef** [comment]
Hello @cbfrank,

When creating the layoutCandidates functionality, I didn't intend for it to be used with the key-navigation module. However, I agree that it makes sense to support it. I would be willing to work on this soon, potentially next week.

I will track this feature request in the Enhancements project and will update this thread as soon as I get to work on it.

Thank you,
Francisco Hodge

**Comment by hodgef** [comment]
Hey @cbfrank,

I have deployed an update to simple-keyboard-key-navigation (latest) to support layoutCandidates.

The support is quite basic as you can see in the following gif, but it should do the job. Feel free to update the module and give it a try.

![keyNavCandidates2](https://user-images.githubusercontent.com/25509135/132139851-dca2f0c6-e06b-476f-89f7-b5f9155c9141.gif)

Regards,
Francisco Hodge

**Comment by cbfrank** [comment]
Hello
Thank you so much for supporting this in a very short time. I have download the latest simply-keyboard and simple-keyboard-key-navigation and put the index.js from both lib into my local project. but this seems doesn't work for me and event broken the existing of press enter, with the latest code, I can move with the hardware arrow keys, but press enter does nothing, no soft key is press actually.  I have put all my project code here https://github.com/cbfrank/simple-keyboard-test

Thank you!

**Comment by hodgef** [comment]
Sorry about that, I will clone your repo and investigate. Thanks!

**Comment by hodgef** [comment]
Hey @cbfrank,

The issue should be fixed as of simple-keyboard-key-navigation@2.4.3. Feel free to update and give it a try.

Thanks!
Francisco Hodge

**Comment by cbfrank** [comment]
Hello
It works very well!
Thank you very much for helping on this!

Best regards
Frank
