### ISSUE TITLE
Usage with Vuetify - problem with v-combobox

### ISSUE THREAD

**Issue by stuomas** [hodgef/simple-keyboard#1206]
**Simple-keyboard version**
3.2.37

**Describe the bug**
When using with v-combobox or v-autocomplete from Vuetify, the input field needs to be clicked twice to be able to use simple-keyboard to input more that one character. If input field is clicked once, as normally, only one simple-keyboard button can be pressed before input is blurred and a one-character "chip" is created.

I have been struggling with this for a while in my app, and just cannot figure out what is the reason. It can of course be an issue with Vuetify too. I cannot find anything special happening with the second click, no new events or anything.

Codesandbox: https://codesandbox.io/s/demo-nuxt-spa-simplekeyboard-vuex-forked-qsng4?file=/pages/index.vue

**Screenshots**

**Comment by hodgef** [comment]
Hello @stuomas, as far as I can tell `v-combobox` is calling blur as soon as you click outside of it. You can contrast this with the normal behavior of `v-text-field` which is a real input element.

I believe this is an issue with `v-combobox`'s code and not simple-keyboard.

Regards,
Francisco Hodge

**Comment by mariocampacci** [comment]
@stuomas I had the same problem using the v-autocomplete component from vuetify.

This is the best solution I've found to fix this unexpected behaviour, by setting a custom `v-click-outside` directive for the component.

I updated your Codesandbox: https://codesandbox.io/p/sandbox/demo-nuxt-spa-simplekeyboard-vuex-forked-fqddh7?welcome=true&file=%2FREADME.md
