### ISSUE TITLE
Edit multiple inputs by using the same keyboard

### ISSUE THREAD

**Issue by KyleOng** [hodgef/simple-keyboard#1274]
Hello,

First of all, love the simple and lightweight on-screen keyboard. So far I have been using it for one input and notice that multiple inputs can't be used by the same keyboard. So this leads to my question, is it possible to edit multiple inputs by using the same keyboard?

Thank you very much

**Comment by hodgef** [comment]
Hello @KyleOng,

That can be done for sure. Check out the following for more info:
https://hodgef.com/simple-keyboard/questions-answers/use-simple-keyboard-multiple-inputs/

Regards,
Francisco Hodge
