### ISSUE TITLE
Documentation: broken link in Options / physicalKeyboardHighlight

### ISSUE THREAD

**Issue by klossner** [hodgef/simple-keyboard#1281]
Documentation page [https://hodgef.com/simple-keyboard/documentation/options/physicalkeyboardhighlight/](https://hodgef.com/simple-keyboard/documentation/options/physicalkeyboardhighlight/) contains a link labeled "Click here" to [https://github.com/hodgef/simple-keyboard/blob/master/src/lib/services/Utilities.js#L42](https://github.com/hodgef/simple-keyboard/blob/master/src/lib/services/Utilities.js#L42). That gets a 404 - there is no file "Utilities.js". There is a "Utilities.ts", but line 42 of that file doesn't seem to be the right one "to see some of keys supported out of the box".

**Comment by hodgef** [comment]
Fixed, thanks for reporting!
