### ISSUE TITLE
After deleting first character cursor jumps to an end

### ISSUE THREAD

**Issue by chhunchha** [hodgef/simple-keyboard#13]
**Describe the bug**
1. Type text in to input for example "123456789"
2. Put cursor between '3' and '4'
3. Hit backspace till it deletes '1'
4. Hit backspace one more time 

Expected:
Cursor should have stayed at start of input box and delete nothing

Actual:
It deletes 9

**Comment by hodgef** [comment]
Hello @chhunchha,

Thank you for this bug report! The issue should now be fixed as of simple-keyboard 2.5.9 and react-simple-keyboard 1.5.6.

[![Edit simple-keyboard demo - npm](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/krzkx19rr?module=%2Fsrc%2Findex.js)

If you notice the problem still, please let me know and I'll reopen the ticket.

Regards
