### ISSUE TITLE
regex to force 01-123456/01

### ISSUE THREAD

**Issue by ramstein74** [hodgef/simple-keyboard#131]
Hello i need force the user to fill something like dd-dddddd/dd
i tried 
inputPattern: {
  'default': /^\d{2}-\d{6}\/d{2}$/,
}

but it does not work.
Can you help ?

**Comment by hodgef** [comment]
Hello @ramstein74,

[`inputPattern`](https://franciscohodge.com/projects/simple-keyboard/documentation/#inputPattern) tests individual keys, not the whole input. It's meant for simple checks like ensuring users only enter numbers.

In your example, when the user enters "0" in the keyboard, it will be tested against the regex `/^\d{2}-\d{6}\/\d{2}$/` and will not match.

I would suggest instead to use one of the following options:

**- Input validation** 
[Demo](https://codesandbox.io/s/simple-keyboard-npm-demos-1q9vi) - [Docs](https://franciscohodge.com/projects/simple-keyboard/qa-use-cases/#input-validation)

**- Input Mask** 
[Demo](https://codesandbox.io/s/simple-keyboard-input-mask-demo-1k8gc) - [Docs](https://franciscohodge.com/projects/simple-keyboard/modules/input-mask/)

Regards,
Francisco Hodge

**Comment by CrashyBang** [comment]
Note the docs link above for **Input validation** does not work.

Cheers.

**Comment by hodgef** [comment]
Thanks @CrashyBang ! I've updated the link.

Regards,
Francisco Hodge
