### ISSUE TITLE
Import of the Keyboard component in Electron throws an invalid hook error

### ISSUE THREAD

**Issue by fadime-ozdemir** [hodgef/simple-keyboard#1322]
**Simple-keyboard version**
version ^3.3.22

**Describe the bug**
Import of the Keyboard component in Electron throws invalid hooks error. 
I have tried to add it to whitelistmodule, change webpack configuration of the package , see if there were more instances of react or react-dom.
I still get the same error. 

**Screenshots**
more details about the error message
![hook-details](https://user-images.githubusercontent.com/12509733/139856772-7c8e42b2-bf41-4318-91e0-7861fd91a22d.PNG)

**Comment by hodgef** [comment]
Hello @fadime-ozdemir,

It does work for me on latest, can you share a test git repo so I can debug?

![image](https://user-images.githubusercontent.com/25509135/140012873-090cb3b5-358a-49dd-9e51-e2b59d9f33e9.png)

Will re-open as soon as I get the repro, thanks!

Regards,
Francisco Hodge
