### ISSUE TITLE
Weird behavior when key is clicked using the right button of the mouse

### ISSUE THREAD

**Issue by sfasp** [hodgef/simple-keyboard#1333]
**Simple-keyboard version**
The used in demo site (https://hodgef.com/simple-keyboard/demos/)

**Describe the bug**
When a key is clicked with the right button of the mouse (whatever reason: by mistake, a child, ...) the input key is endlessly repeated until new click.
Tested with Chrome Version 95.0.4638.69 (Official Build) (64-bit)

**Comment by hodgef** [comment]
Hey @sfasp,

Sorry, I cannot repro the issue - not sure why you're getting that behavior, but if PointerEvents are giving you trouble you can use mouse events with the option: [`useMouseEvents: true`](https://hodgef.com/simple-keyboard/documentation/options/usemouseevents/)

![cnr](https://user-images.githubusercontent.com/25509135/141084186-9aa84101-3c86-4d23-966b-275f837be11b.gif)

Regards,
Francisco Hodge

**Comment by sfasp** [comment]
Hi @hodgef,
Thank you very much for your fast response.
Here you have a video reproducing the issue.
I will try your suggestion.

https://user-images.githubusercontent.com/74743015/141086807-1824bac4-5eba-4f79-a75c-872f21095051.mp4

Regards,
Santi

**Comment by hodgef** [comment]
Hey Santi, is that Ubuntu? I still cannot repro the issue so it will be tough to proceed. As a workaround: Besides using [`useMouseEvents`](https://hodgef.com/simple-keyboard/documentation/options/usemouseevents/) you can alternatively use [`disableButtonHold`](https://hodgef.com/simple-keyboard/documentation/options/disablebuttonhold/) to get rid of button hold altogether.

If you do have Ubuntu/Linux I will try testing there, but if you have Windows I'm afraid I cannot proceed until I can repro.

Regards,
Francisco Hodge

**Comment by jiangyh1024** [comment]
I came across a similar behavior.

I have an input for users to enter a code like '123456', and then call an api to validate it.


keyboard will be displayed when input is focused, and hidden when blurred.

the strange thing is that after validation, the keyboard is hidden. and then, the input will be filled indefinitely (onchange event is triggered incessantly)

add disablebuttonold solves the problem, but we're losing the feature, which means the user needs to press delete button several times to delete the chars entered

**Comment by hodgef** [comment]
@jiangyh1024 I wouldn't know if your issue is the same as the one above without a repro. If you would like for me to take a look, please create an issue and attach a repro sandbox or repository. Thanks!

If you want to keep using `disableButtonHold`, you can create a ["clear" button](https://hodgef.com/simple-keyboard/documentation/methods/clearinput/) that will empty the input for the user. Like so:

```js
keyboard.clearInput();
// also clear your input element
input.value = "";
```
