### ISSUE TITLE
Korean keyboard won't type korean syllables 

### ISSUE THREAD

**Issue by hanuz06** [hodgef/simple-keyboard#1398]
Hi Francisco,

For example: it should be "워", but it always types as '우 ㅓ'. How can I fix the problem? Thank you in advance.

![korean-keyboard](https://user-images.githubusercontent.com/17211293/147375132-3dca5fe2-9f78-4e14-949d-b205c6f2bb3a.JPG)

**Comment by hodgef** [comment]
Hey @hanuz06,

I have pushed updates to simple-keyboard and simple-keyboard-layouts to support Korean CandidateBox.

To try it out, please upgrade to the following:

- simple-keyboard@3.4.29
- simple-keyboard-layouts@3.1.29

Demo: https://codesandbox.io/s/fragrant-dawn-1w9eh?file=/src/index.js

Here's the layout that was changed:
https://github.com/simple-keyboard/simple-keyboard-layouts/blob/master/src/lib/layouts/korean.ts

Note: I'm convinced there will be some issues, such as missing syllabes, redundant entries, among others. I cannot verify as I'm not a native Korean speaker, so I will rely on community effort to modify the layout linked above and submit PRs as needed.

Regards,
Francisco Hodge

**Comment by hanuz06** [comment]
Hi Francisco,

Thank you very much for your update. In demo it works fine. I wonder if you can update React version? I tried to implement with simple-keyboard@3.4.29
simple-keyboard-layouts@3.1.29 but it doesn't seem to work. Thank you in advance.

Kind regards,
Andrey

**Comment by hodgef** [comment]
No problem, I have published the update to react-simple-keyboard@3.4.38.

You can get your setup to work by following this React example:
https://codesandbox.io/s/mutable-framework-0y51i?file=/src/index.js

Regards,
Francisco Hodge

**Comment by hanuz06** [comment]
Thank you very much, Francisco.

**Comment by hanuz06** [comment]
@hodgef 
Hi Francisco,

I wonder if korean keyboard is in unicode? With korean keyboard it shows correct syllables but it's not recognized by code. I investigated and found that same words typed from keyboard and typed from virtual keyboard have different character code.  

I think the problem is that currently words typed from virtual keyboard are considered as a sequence of letters like in English but korean syllables have separate code type. For example: In a word "신", ㅅ = U+3145, ㅣ= U+3163, ㄴ = U+3134, and 신=U+C2E0.  In virtual keyboard may show syllables as  U+3145/U+3163/U+3134 but it should be U+C2E0.

So I wonder if it's possible to assign unicode to each syllable? If necessary I can make a list with each syllable assigned to corresponding unicode code.

This character codes for a word from virtual keyboard:

![utf8-virtual](https://user-images.githubusercontent.com/17211293/152767482-9f25eb67-1e32-4f6a-becd-351d2084c5fb.png)

This character codes for a word from real keyboard:

![utf8-real](https://user-images.githubusercontent.com/17211293/152767504-d6f7a89c-fbd5-464d-975c-5bc5b0a8863e.png)

**Comment by hanuz06** [comment]
Actually the syllable code can be reliably calculated if we know all letters composing that syllable. So when a user clicks on that small window to make a syllable, the program can generate a syllable unicode code. 

https://en.wikipedia.org/wiki/Korean_language_and_computers#Hangul_in_Unicode

**Comment by hodgef** [comment]
Hello @hanuz06,

Once you select a CandidateBox item, the item is decomposed like this:
https://github.com/hodgef/simple-keyboard/blob/8628bf34a385da7505d99922a71336e1ef1b812d/src/lib/components/Keyboard.ts#L371

This is helpful if you made a mistake, as it allows you to hit backspace and remove that last portion of the syllabe (triggering the CandidateBox) instead of deleting the whole syllabe and starting over.

You can try out the various normalize functions to see their effect:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize

In that page there's a box that you can use to run your code. Try entering this:

```js
const name1 = '신';
const name2 = '신';

console.log(`${name1}, ${name2}`, name1.length, name2.length);
console.log(name1 === name2);
console.log(name1.length === name2.length);

const name1NFC = name1.normalize('NFC');
const name2NFC = name2.normalize('NFC');

console.log(`${name1NFC}, ${name2NFC}`, name1NFC.length, name2NFC.length);
console.log(name1NFC === name2NFC);
console.log(name1NFC.length === name2NFC.length);
```

Regards,
Francisco Hodge

**Comment by hanuz06** [comment]
Thank you very much Francisco. normalize('NFC') works for korean syllables.
