### ISSUE TITLE
Input loses focus & cursor on simple-keyboard keypress

### ISSUE THREAD

**Issue by zreese** [hodgef/simple-keyboard#14]
Using simple-keyboard v2.6.8. Testing in Chrome 70.0.3538.77 (Official Build) (64-bit) on macOS 10.12.6.

When selecting a text input, it gets a CSS `:focus` selector. When interacting with the keyboard to enter text into the input field, the keyboard steals focus and the `:focus` selector and cursor both disappear. 

![image](https://user-images.githubusercontent.com/5454454/47800404-98ead500-dd02-11e8-9efd-e4889d735156.png)
![image](https://user-images.githubusercontent.com/5454454/47800427-a2743d00-dd02-11e8-83df-fb3e6d053a87.png)

[Sandbox example](https://codepen.io/zreese/pen/XxLGNw)

**Comment by hodgef** [comment]
Hello @zreese,

A loss of input focus when you click away from the input is normal. To handle multiple inputs, check out this example:

https://codesandbox.io/s/github/hodgef/demo_npm_simple-keyboard_multiple-inputs

____
**How simple-keyboard works**

Simple-keyboard has an internal input, so it really isn't aware of input elements - you could even ditch them altogether.

To update an input/textarea/div, you must do so manually on simple-keyboard's onChange callback. The same way, when you enter text with a physical keyboard, you must update simple-keyboard afterward through the input element's onchange event. Check out the example above to see this in action.

Hope this helps, if not please feel free to let me know and I'll reopen the ticket.

Thanks!
