### ISSUE TITLE
Some event listeners are not removed on destroy

### ISSUE THREAD

**Issue by emiljohansson** [hodgef/simple-keyboard#144]
**Simple-keyboard version**
2.23.3

**Describe the bug**
After destroying a keyboard instance, I still see some listeners attached to the `document` object and new ones are added for each instance. I believe it is coming from https://github.com/hodgef/simple-keyboard/blob/master/src/lib/services/PhysicalKeyboard.js#L33
They're anonymous so I am not able to manually remove them.

Thanks

**Comment by hodgef** [comment]
Hello @emiljohansson,

You are correct, [`destroy()`](https://simple-keyboard.com/documentation/#destroy) currently only removes caret positioning events that are set [here](https://github.com/hodgef/simple-keyboard/blob/ea84c35e32a8e8a4ce031a4997bc3d67ac683f52/src/lib/components/Keyboard.js#L606). I forgot about the PhysicalKeyboard events (which are used for the [`physicalKeyboardHighlight`](https://simple-keyboard.com/documentation/#physicalKeyboardHighlight) feature).

I'll release a fix today and update the ticket once it's out.

Thank you,
Francisco Hodge

**Comment by hodgef** [comment]
Hello @emiljohansson,

Sorry for the delay, I ended up taking the opportunity to do a bit of code cleanup.

As of the latest version, `destroy()` should be disposing of all event listeners set by simple-keyboard. Feel free to try it out!

Regards,
Francisco Hodge

**Comment by emiljohansson** [comment]
@hodgef Thank you! I don't think i see any dead listeners anymore.
