### ISSUE TITLE
Keyboard not displaying after router navigate on Angular

### ISSUE THREAD

**Issue by NPaolo** [hodgef/simple-keyboard#1446]
**Simple-keyboard version**
3.4.44

**Describe the bug**
I'm using the simple-keyboard in an Angular project which basically consists of 2 components with same template (both containing a keyboard), each linked to the other through a router.navigateByUrl.

The keyboard displays fine when I initially land on the root component, but as I navigate to the second component, the keyboard doesn't display and its element in the DOM looks empty in the inspector.

This doesn't happen if I directly target the URL writing it in the browser address bar.

**Screenshots**
<img width="623" alt="Schermata 2022-02-12 alle 19 53 16" src="https://user-images.githubusercontent.com/56586429/153724358-0e9a9b2b-1361-4252-b196-b5548e24bb69.png">
<img width="622" alt="Schermata 2022-02-12 alle 19 54 03" src="https://user-images.githubusercontent.com/56586429/153724405-deff1acb-be2b-425e-8b83-e1c6fbaea10c.png">

**Comment by hodgef** [comment]
Hello @NPaolo,

The keyboard class needs to be instantiated every time the DOM element is recreated. I believe this doesn't happen in your logic as you change pages, but to confirm I would need a repro. Do you mind providing a test git repo or runnable sandbox example that would allow me to debug this?

I will reopen once that's provided, thanks!

**Comment by dmesmin** [comment]
@NPaolo I have the same issue, I tried to reproduce it with a simple stackblitz but I'm unable to, it's always working :p
Did you solve it ? thanks

**Comment by hodgef** [comment]
Hey @dmesmin do you mind providing a test git repository that shows the issue? I'm sure it has something to do with the app logic but I would need to debug to find a solution.

**Comment by NPaolo** [comment]
@dmesmin Hi, I also couldn't reproduce it on Stackblitz, but I figured out that the issue only comes up when I navigate from a keyboard page to another keyboard page.

So I solved it with a workaround, navigating first on a different page and then to the target page.

Page 1 (keyboard) --> Page 2 --> Page 3 (keyboard)

**Comment by hodgef** [comment]
Sadly I haven't gotten a repro so I cannot tell for sure what the issue is. That being said, you can try giving different classes to each keyboard:

https://hodgef.com/simple-keyboard/questions-answers/give-different-base-class-keyboard/

You can also try calling `destroy` on route unload:
https://hodgef.com/simple-keyboard/documentation/methods/destroy/

Hope that helps. Closing the thread as I cannot do much here without repro.

Regards,
Francisco Hodge
