### ISSUE TITLE
onKeyReleased or onKeyUp option

### ISSUE THREAD

**Issue by emiljohansson** [hodgef/simple-keyboard#145]
**Is your feature request related to a problem? Please describe.**
It would be helpful to be able to listen when the user release a key press, similar to `onChange` and `onKeyPress`. Working with the google autocomplete api, I need to be able to re-focus the field after the user has pressed a key.

**Describe the solution you'd like**
Expose a `onKeyReleased` (or similar) in the options, like `onKeyPress`. 

**Describe alternatives you've considered**
I'm solving this by adding another `pointerup` event on keyboardDOM, but would much rather use the build in listener on the buttons.

Thanks

**Comment by hodgef** [comment]
Hello @emiljohansson,

Just as a side note, If you want to avoid losing input focus, you can enable the option [`preventMouseDownDefault`](https://simple-keyboard.com/documentation/#preventMouseDownDefault).

Getting back on topic: I see the value in having the `onKeyReleased` feature built-in. I will implement it as part of the next minor release. Should be out by EOW or before.

Thanks !

**Comment by emiljohansson** [comment]
@hodgef Thanks for the instant responses on both tickets! 💯 It's a great module, very easy to work with!

**Comment by hodgef** [comment]
Hello @emiljohansson,

`onKeyReleased` is now available as of the latest version. Feel free to update and try it out!

https://github.com/hodgef/simple-keyboard/releases/tag/2.24.0

Regards,
Francisco Hodge

**Comment by emiljohansson** [comment]
@hodgef Thanks! it works as expected.
