### ISSUE TITLE
Angular 11 and simple-keyboard-input-mask?

### ISSUE THREAD

**Issue by tamerhas** [hodgef/simple-keyboard#1463]
Hello, how to use simple-keyboard-input-mask with angular 11. Any code example please?

**Comment by hodgef** [comment]
Hello @tamerhas,

The module seems to be working well here:
https://codesandbox.io/s/busy-lichterman-gscqol?file=/src/app/app.component.ts

That being said, I had to adjust the types a bit. The types depend on the module you're using, but I plan to roll out an improvement for this later on. In the meantime you can use the module with custom types as shown in the above sandbox.

If you're still having issues, please provide a repro and I will have a look.

Regards,
Francisco Hodge
