### ISSUE TITLE
Keyboard not displayed II

### ISSUE THREAD

**Issue by dmesmin** [hodgef/simple-keyboard#1467]
Hi Francisco,
It's sad that you lock the issue below while I'm still investigating it, 2 hours after I got an answer from OP.
I found what was the issue, it's not in your repo, but I guess I can provide some input if someone had the same issue but I can't in the old one as the issue is locked.

In my case the issue was a side-effect of Ionic:
Ionic sometimes caches angular components and therefore don't call standard Angular lifecycle hooks (such as OnInit, AfterViewInit, OnDestroy) even when a new page is displayed. 
Therefore, in my case, the component that holds the keyboard was being re-used and those functions were never called:
```
 ngAfterViewInit() {
        this.keyboard = new Keyboard({...});
        ...
  }
  ngOnDestroy(): void {
        this.keyboard?.destroy();
    }
```
That's why simple-keyboard was not displayed the second time.

Best regards,
Daniel

--------------------------------
Sadly I did not get the repro so I cannot tell for sure what the issue is. That being said, you can try giving different classes to each keyboard:

https://hodgef.com/simple-keyboard/questions-answers/give-different-base-class-keyboard/

Alternatively, you can try calling `destroy` on route unload:
https://hodgef.com/simple-keyboard/documentation/methods/destroy/

Hope that helps. Closing the thread as I cannot do much here without repro.

Regards,
Francisco Hodge

_Originally posted by @hodgef in https://github.com/hodgef/simple-keyboard/issues/1446#issuecomment-1056837357_

**Comment by hodgef** [comment]
Thanks for sharing the solution Daniel! I locked the issue https://github.com/hodgef/simple-keyboard/issues/1446 because I thought the conversation could end up in a back and forth with no repro provided. I really appreciate that you took the time to share your findings with everyone.

Regards,
Francisco Hodge
