### ISSUE TITLE
onKeyReleased not working with physicalKeyboardHighlightPress

### ISSUE THREAD

**Issue by jamesgoodhouse** [hodgef/simple-keyboard#1506]
**Simple-keyboard version**
`3.4.104`

**Describe the bug**
I'm utilizing `physicalKeyboardHighlightPress` and am noticing that `onKeyReleased` does not seem to do anything when I release a key. It only seems to fire when I click and release the virtual keyboard with my mouse.

**Screenshots**
N/A

**Comment by hodgef** [comment]
Hey @jamesgoodhouse, `onReleased` only triggers "on pointer up", and `physicalKeyboardHighlightPress` triggers the button handler directly.

I have added a new option called `physicalKeyboardHighlightPressUsePointerEvents` which uses onpointerup and should resolve your issue. Feel free to update and give it a try.

Regards,
Francisco Hodge

**Comment by jamesgoodhouse** [comment]
Awesome, thank you so much! I'll give it a go.

**Comment by jamesgoodhouse** [comment]
So looks like it's working; not as I was expecting, but likely how it's intended. If I hold the key down on the keyboard, it basically does a key repeat (which is normal behavior for a keyboard), and thus firing the "key up" event continually. I was hoping to be able to implement behavior such that when you hold a key down, it registers a single keystroke, and then when you release the key, it triggers the key up event.

**Comment by hodgef** [comment]
Sorry about that, I didn't do the initial fix correctly. Feel free to update to latest and give it another try, hopefully this time it works!

Regards,
Francisco Hodge
