### ISSUE TITLE
shift and caps lock button are working the same!?

### ISSUE THREAD

**Issue by ray-kay** [hodgef/simple-keyboard#1516]
**Simple-keyboard version**
3.4.88

**Describe the bug**
Not sure if its a bug or intentional: but shift and caps lock button are currently working the same.

**Expected behavior**
From a regular keyboard I would expect to
- press shift button once (keyboard adds "hg-layout-shift" class)
- next letter would be in uppercase
- now the class "hg-layout-shift" would be removed and any other letter in lowercase

I also need to differentiate between caps lock und shift in css to style the caps look button in active state.

Many thanks

**Comment by hodgef** [comment]
Hello @ray-kay,

There's a short mention of this behavior in the docs:
https://hodgef.com/simple-keyboard/questions-answers/shift-caps-lock-behaving-same/

The demo in there will not address your feature request however. I think you will need to add your own logic to accomplish this  (perhaps with the use of [`onKeyReleased`](https://hodgef.com/simple-keyboard/documentation/options/onkeyreleased/)). I will add this as an Enhancement proposal to build this in eventually but I don't expect to pick it up soon.

Regards,
Francsico Hodge
