### ISSUE TITLE
Error Loading CSS from CDN

### ISSUE THREAD

**Issue by mccaffreyp** [hodgef/simple-keyboard#154]
Getting errors loading 

https://cdn.jsdelivr.net/npm/simple-keyboard@latest/build/css/index.css

saying .simple-keyboard not found

due I think to the line actually being commented out

 */body,html{margin:0;padding:0}.simple-keyboard{font-family:HelveticaNeue........

**Comment by hodgef** [comment]
Could you show me a screenshot of the errors? That line is not commented out, as you can see `*/` marks the end of the comment.

I'l reopen once I get this information.

Regards,
Francisco Hodge
