### ISSUE TITLE
Holding key for optional characters (e.g. accented vowels)

### ISSUE THREAD

**Issue by Guiladg** [hodgef/simple-keyboard#1544]
I would like to have the option to add accents to vowels and why not symbols to different keys on hold. I couldn't find if it is possible right now.

**Comment by hodgef** [comment]
Hey @Guiladg,

I think you can use the `layoutCandidates` option for this task:
https://hodgef.com/simple-keyboard/documentation/options/layoutcandidates/

This is not triggered by "press and hold" however. I will add this to the Enhancement proposals so I can pick it up in a future version.

Regards,
Francisco Hodge

**Comment by Guiladg** [comment]
Thanks a lot!
Your work is truely amazing.
