### ISSUE TITLE
Input Mask Breaks

### ISSUE THREAD

**Issue by bencreighton** [hodgef/simple-keyboard#155]
Hi Francisco,

It looks like your latest version of simple-keyboard breaks the input mask.  

-Ben

**Comment by hodgef** [comment]
Hello @bencreighton,

Thanks a lot for bringing this to my attention. I'll work on a fix right away.

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
Hello @bencreighton,

The issue [should now be fixed](https://travis-ci.org/hodgef/simple-keyboard-input-mask/builds/559169066) as of `simple-keyboard-input-mask@2.0.1`.
Sorry for the trouble!

Regards,
Francisco Hodge

**Comment by bencreighton** [comment]
No trouble at all.  Thanks for fixing it so quickly.  

-Ben
