### ISSUE TITLE
Shift capitalize only first letter

### ISSUE THREAD

**Issue by dkaklamanis** [hodgef/simple-keyboard#1567]
**Is your feature request related to a problem? Please describe.**
It would be ideal if the shift button should capitalize only the first letter and after that return the layout to small case letters.
So it would behave as a mobile native keyboard.

**Describe the solution you'd like**
shift option or parameter to capitalize only the first letter.

**Comment by hodgef** [comment]
Hey @dkaklamanis,

Thanks for your suggestion. I think this one can be easily implemented by devs, so I wouldn't build this in.

Essentially you can do this is in your onKeyPress handler. If the layout is "shift" and there's already a letter in the input, then change the layout to default.

Regards,
Francisco Hodge
