### ISSUE TITLE
Key sticking and characters repeating indefinitely

### ISSUE THREAD

**Issue by rouxster777** [hodgef/simple-keyboard#1572]
The keyboard key remains in the down state when clicked with the secondary mouse button (right-click). Characters are then added indefinitely. 

On further investigation the repeating characters can be resolved with disableButtonHold, however the key still remains in the down state.

**Comment by hodgef** [comment]
You haven't provided a repro or OS/Browser details, so I have to close it on that basis. However I'm pretty sure you're using Ubuntu/Linux and that this is a duplicate of https://github.com/hodgef/simple-keyboard/issues/1333
