### ISSUE TITLE
[Feature Request] Working with keyboard or remote arrow keys

### ISSUE THREAD

**Issue by DQvsRA** [hodgef/simple-keyboard#158]
**Describe the solution you'd like**
I would like to navigate within this virtual keyboard keys using the physical keyboard arrows or remote controller keys.

**Comment by hodgef** [comment]
Hello @DQvsRA,

I think the [Key Navigation module](https://franciscohodge.com/projects/simple-keyboard/demo-showcase/module-key-navigation/) is what you're looking for. Feel free to check it out.

Regards,
Francisco Hodge
