### ISSUE TITLE
Support for <input type="date"

### ISSUE THREAD

**Issue by ray-kay** [hodgef/simple-keyboard#1586]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Simple keyboard also works for <input type="date" like it does for type="text"

**Comment by hodgef** [comment]
Hello @ray-kay,

This is a browser limitation. Please see https://github.com/hodgef/react-simple-keyboard/issues/247

Thanks,
Francisco Hodge
