### ISSUE TITLE
Bug with mouse selection of the input

### ISSUE THREAD

**Issue by BFernandez-intuiface** [hodgef/simple-keyboard#1597]
**Simple-keyboard version**
Version: 3.4.94

Hello Francisco,
When you select multiple letters of your input and then just click to place the caret, the selection disappears as expected but pressing a button of a keyboard act like the selection is still there. 
If you select "abc" and then click after the "c", pressing "d" will replace "abc" instead of just adding the "d".

Really nice project by the way!

Regards,
Bastien

**Comment by hodgef** [comment]
Hello @BFernandez-intuiface,

I believe this is a Chromium bug. The mouse up event that is fired when we click to unselect the text has the wrong `event.target.selectionStart` and `event.target.selectionEnd` values.

![caret](https://user-images.githubusercontent.com/25509135/174934120-06ccccd7-afa8-45e0-a552-cd698196d2c3.gif)

Repro: https://jsfiddle.net/xcf5saze/7/

If you can repo the issue, it migh be worth reporting to https://bugs.chromium.org/p/chromium/issues/list.

Regards,
Francisco Hodge
