### ISSUE TITLE
Enter does not trigger form submission when using simplekeyboard in a form.

### ISSUE THREAD

**Issue by quinlo** [hodgef/simple-keyboard#1602]
**Simple-keyboard version**
3.4.88

**Describe the bug**
Enter does not trigger form submission when using simplekeyboard in a form.  Is there a workaround here using the other options available?  I saw some reference in another ticket discussing accesibility that suggested flexibility using the buttonAttributes or useButtonTag options but I can't understand how that might solve this issue.

**Comment by hodgef** [comment]
Hello @quinlo,

Probably something like this:
https://codesandbox.io/s/unruffled-khorana-xdpkbm?file=/src/index.js

Regards,
Francisco Hodge

**Comment by alexandereneroth** [comment]
> Hello @quinlo,
> 
> Probably something like this: [codesandbox.io/s/unruffled-khorana-xdpkbm?file=/src/index.js](https://codesandbox.io/s/unruffled-khorana-xdpkbm?file=/src/index.js)
> 
> The idea is that a button with the property `type="submit"` will submit the parent form.
> 
> Regards, Francisco Hodge

@hodgef With that code all buttons will submit, since the default type of button is already `submit`.

How can i target all buttons and give them `type="button"`?

**Comment by hodgef** [comment]
Very true. In that case you can try this out
https://codesandbox.io/s/sweet-worker-r2yx1j?file=/src/index.js

Regards,
Francisco Hodge
