### ISSUE TITLE
Supporting: add columns to layout

### ISSUE THREAD

**Issue by ray-kay** [hodgef/simple-keyboard#1614]
**Is your feature request related to a problem? Please describe.**
I would like to add a numpad with a different row number (Buttons are bigger).  It could be easily done by adding another "column" into the layout for the numpad block

**Describe the solution you'd like**
Like there is the group button in a row syntax  [ ... ] there should be a syntax to add another column

**Describe alternatives you've considered**
Currently my workaround is to use 2 instances of the keyboard which causes overhead.
![image](https://user-images.githubusercontent.com/12802386/176867329-cab71228-f5c5-4450-aa15-e15807cc0651.png)

**Comment by hodgef** [comment]
Hi @ray-kay, while I agree that having this functionality would be nice to have, I wouldn't implement it for the following reasons:

- It's probably not worth the extra load in terms of dev effort, potential bugs, maintenance and documentation. (This is the main reason, as I'm trying to make simple-keyboard as stable and easy to maintain as possible).
- The current multi-keyboard approach doesn't seem to show any significant perf impact or complexity.
- There's not a lot of demand for this use-case.

For these reasons, I would still recommend using the synchronized keyboards approach shown in the [full keyboard demo](https://hodgef.com/simple-keyboard/demos/?d=fullKeyboard).

That being said, I completely agree that this would be an improvement - it's just that for simple-keyboard I want to prioritize critical features and bug fixing.

Regards,
Francisco Hodge
