### ISSUE TITLE
Setting maxLength in one input causes incorrect caret position on another input

### ISSUE THREAD

**Issue by ray-kay** [hodgef/simple-keyboard#1620]
**Simple-keyboard version**
3.4.122

**Describe the bug**
I have one instance of the keyboard an a directive that changes the input id on focus.
Now in my login screen I have a UserId with maxLength: 3 and Password field with no maxLength limitation.

`const options: KeyboardOptions = {
 inputName: this._inputTarget.id || 'default',
 maxLength: this._inputTarget.maxLength > -1 ? this._inputTarget.maxLength : undefined,
};
this._keyboard.setOptions({
 options
});`

When I type in the UserId field more then 3 chars it looks fine (eg 1234 only shows 123)
Now I focus in the password field and start typing "1235" it looks like this

![image](https://user-images.githubusercontent.com/12802386/177349521-169fd829-34ec-4ebf-ab1c-55454d26cddf.png)

I would expect to have "1235"

At the end of the `onChange` callback function I have this
`this._inputTarget.setSelectionRange(this._keyboard.caretPosition, this._keyboard.caretPosition);`

**Comment by hodgef** [comment]
Hello @ray-kay,

Could you provide a repro for debugging? Will reopen the ticket once that is provided.

Thanks!
Francisco Hodge

**Comment by ray-kay** [comment]
Hi @hodgef 

please see this demo repo:
https://stackblitz.com/edit/ng-simple-keyboard-maxlength

If you type in more then 3 chars oin the first field and then focus und type in the other field eg 123 its showing 321

![image](https://user-images.githubusercontent.com/12802386/177750577-76d16352-fca7-40ad-8e6b-792e62a4ca58.png)


Thanks for looking into this

Br Ralf

**Comment by hodgef** [comment]
Hey Raif,

Thanks for providing the repro. The `maxLength` option should either affect all inputs as a boolean or affect "some" inputs by passing an object.

Here's the fix:
https://stackblitz.com/edit/ng-simple-keyboard-maxlength-d8rmfa?file=src%2Fapp%2Fcomponents%2Fkeyboard%2Fkeyboard.component.ts

Regards,
Francisco Hodge

**Comment by ray-kay** [comment]
Thanks for clarifying  @hodgef 
I simply missunderstood the documentation (https://hodgef.com/simple-keyboard/documentation/options/maxlength/)
