### ISSUE TITLE
Word Suggestions Feature

### ISSUE THREAD

**Issue by naschimhit** [hodgef/simple-keyboard#1628]
I think in this project should add word suggestions from new word in dictionary.

Data a the word from user input. Example if user type a new word then add word suggestions dictionary.

**Comment by hodgef** [comment]
Hey @naschimhit,

If you mean something like word suggestions when you type, this is something that you can accomplish with custom code, like this:

https://codesandbox.io/s/00jzw1ry70?file=/src/index.js

For now I don't plan to build this into the core library, but I will track this proposal in the Enhancements project for future tracking.

Regards,
Francisco Hodge
