### ISSUE TITLE
If keyboard already has input value. Backspace key doesn't work and keyboard entirely starts new input on pressing any key.

### ISSUE THREAD

**Issue by anehal123** [hodgef/simple-keyboard#1634]
I am using below code to set the value when user gives any input from onscreen kbd.

 public onChange = (input: string) => {
  this.data.content.inputValue = input;
  }

**Comment by hodgef** [comment]
Duplicate of #55

**Comment by hodgef** [comment]
More info: https://github.com/hodgef/simple-keyboard/issues/858#issuecomment-754394081
