### ISSUE TITLE
Dead keys

### ISSUE THREAD

**Issue by romikforest** [hodgef/simple-keyboard#1642]
I don't see dead keys are working. E.g. on a greek demo I can't input diacritics. If dead keys are not implemented they are really required for many languages.

**Comment by hodgef** [comment]
Hello @romikforest,

The [Greek layout](https://hodgef.com/simple-keyboard/demos/?d=greek) was submitted by a contributor before the [`layoutCandidates`](https://hodgef.com/simple-keyboard/documentation/options/layoutcandidates/) feature was released.

If you would like to have popups with key suggestions, you can add the layoutCandidates option accordingly:
https://hodgef.com/simple-keyboard/documentation/options/layoutcandidates/

If you want to contribute your change to simple-keyboard-layouts, I would welcome your PR. Here's the Greek layout file:
https://github.com/simple-keyboard/simple-keyboard-layouts/blob/master/src/lib/layouts/greek.ts

For comparison, here's the Chinese and Korean versions which contain layout candidates:
https://github.com/simple-keyboard/simple-keyboard-layouts/blob/master/src/lib/layouts/chinese.ts
https://github.com/simple-keyboard/simple-keyboard-layouts/blob/master/src/lib/layouts/korean.ts

Regards,
Francisco Hodge
