### ISSUE TITLE
"^" does not call up layoutCandidates selection properly

### ISSUE THREAD

**Issue by gvolt** [hodgef/simple-keyboard#1645]
**Simple-keyboard version**
3.4.0 stable

**Describe the bug**
Add this code
```
  layoutCandidates: {
    '^': 'â Â ê Ê î Î ô Ô û Û'
  }
```
to e.g. the french layout.

Pressing the ^ key on the virtual keyboard just prints "^" to the input field instead of opening the layoutCandidates selection which would be the expected behaviour.

After you have entered one or more characters in the input field, surprisingly the layoutCandidates selection field appears when you delete all characters, e.g. with the backspace key. This happens even if "^" was not used at all, but any other key. Expected behaviour would be the layoutCandidates selection field not showing up when the input field is emptied.

**Comment by hodgef** [comment]
Hey @gvolt, thanks for reporting this issue!

The issue was that "^" is a special regex character and needed to be escaped. The fix has been deployed to the latest version of simple-keyboard.

Regards,
Francisco Hodge

**Comment by gvolt** [comment]
Thanks a lot @hodgef! Keep up the excellent work.
