### ISSUE TITLE
Keyboard lacks any css

### ISSUE THREAD

**Issue by joachimek** [hodgef/simple-keyboard#1657]
**Simple-keyboard version**
react-simple-keyboard 3.4.180

**Describe the bug**
Whenever i try to render the keyboard in my app, it is displayed as a column of divs working as buttons, but lacking any css styling.

**Screenshots**
![obraz](https://user-images.githubusercontent.com/45990411/182860558-81d742ff-5382-45bf-b01a-a1046417a6b9.png)

**Comment by hodgef** [comment]
Are you importing the CSS file into your project like in the demo?
If so, please provide a repro and I will reopen this and take a closer look.
