### ISSUE TITLE
Shift not working

### ISSUE THREAD

**Issue by dieterdreist** [hodgef/simple-keyboard#1673]
**Simple-keyboard version**
As some bugs have been addressed in later versions, please ensure you are running the latest.

**Describe the bug**
A clear and concise description of what the bug is. Providing a [sandbox example](https://codesandbox.io/s/vanilla) or code depicting the issue is important, as this will help us reproduce the issue.

on no browsers I could get the shift working, neither in your demos it works for me. iOS Android and Firefox on mac
**Screenshots**

**Comment by hodgef** [comment]
Clicking shift does change the layout in the demos. Closing issue
