### ISSUE TITLE
Customizing keyboard buttons

### ISSUE THREAD

**Issue by mirodil1** [hodgef/simple-keyboard#1690]
I'm trying to customize my keyboard passing the following option in my VUE.
`watch: {
    guessedLetters: {
      handler(guessedLetters) {
        this.keyboard.addButtonTheme(
          guessedLetters.miss.map(name => name.toUpperCase()).join(" "),
          "is-dark"
        );
      );
     }
}`

also tried from documentation by adding `buttonTheme[...]` but not working,
My console shows that it gets class and letters 
![Screenshot from 2022-09-06 11-11-06](https://user-images.githubusercontent.com/69641938/188560154-afae7a2e-f998-4775-9c65-141060ed6a33.png)

**Comment by hodgef** [comment]
Hey @mirodil1, please share a full repro of your current attempt, that will make it easier to debug.

Will reopen the thread once that is provided. Thank you

**Comment by mirodil1** [comment]
@hodgef thanks for answer, [my git repo](https://github.com/mirodil1/wordlefront)

**Comment by hodgef** [comment]
As far as I can tell, your watcher's handler (`watch: { guessedLetters: { handler(guessedLetters) {  ...`) is never being called - which is not a simple-keyboard issue.

If I call `addButtonTheme` directly in the Keyboard's onKeyPress, it works:

![image](https://user-images.githubusercontent.com/25509135/188666382-3e661ac0-b19a-4640-8582-4be8fd4e1753.png)

So first I think you'd need to find out why your watcher is not being called, there might be a few posts on this on StackOverflow.

Regards,
Francisco Hodge

**Comment by mirodil1** [comment]
I made some changes to repo, can you check it pls, watchers handler is called when a word submitted.

I also checked it gets class but not affecting css, I don't know why, I guess everything is fine on my side.
![Screenshot from 2022-09-07 10-14-23](https://user-images.githubusercontent.com/69641938/188796105-758bcf39-87ad-4089-904b-e3050833960c.png)

![Screenshot from 2022-09-07 10-14-12](https://user-images.githubusercontent.com/69641938/188796179-2e76db91-ac3c-42a3-b53b-0439d8b376d3.png)

**Comment by hodgef** [comment]
Try removing "scoped" from your CSS:

![image](https://user-images.githubusercontent.com/25509135/188799161-5a0a6a8d-f7f8-4be7-9515-51049f188404.png)

simple-keyboard is coded in vanilla JS so Vue is not aware of the elements it creates.

**Comment by mirodil1** [comment]
Thanks very much, worked now
