### ISSUE TITLE
Enable/Disable keyboard feature?

### ISSUE THREAD

**Issue by OikonomouDimitrios** [hodgef/simple-keyboard#1729]
Hi there!
Is there a keyboard option/method i can call to disable/enable the keyboard? I cannot seem to find one.
My version is 2.28.73.
Thank you!

**Comment by hodgef** [comment]
Hello @OikonomouDimitrios,

There's isn't such an option currently. You can toggle the CSS property [`pointer-events`](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) or [hide the keyboard](https://hodgef.com/simple-keyboard/questions-answers/implement-show-hide-toggling/) with JS to prevent input.

Regards,
Francisco Hodge
