### ISSUE TITLE
Unable to get correct keyboard's caret position and value entered by keys after upating input in middle are appending at the last

### ISSUE THREAD

**Issue by Niharika-Pat** [hodgef/simple-keyboard#1753]
I am trying to paste a value on the input field of keyboard using external button. But when I update the input field value with new value by calling onChange(input) and then click on any keyboard key then the values typed are appending always at the end and keyboard.caretPosition returned is null.
I tried explicitly setting the position using keyboard.caretPosition=(length of old value + length of added string). But it doesnt work and value always appends at the end.

synchronizing cursor after input field updated:
//called inside onChange()
private syncCurserPosition() {
if (!this.keyboard || this.keyboard.options.disableCaretPositioning) {
return;
}
let caretPosition = this.keyboard.caretPosition;

if (caretPosition !== undefined) {
  this.inputHandler?.targetElement.setSelectionRange?.(caretPosition, caretPosition);
}
}

updating input value by pasting:
pasteValue(cursorPosition) {
const old = this.inputHandler?.targetElement.value;
const newValue = xyz +old;
const val = 3; // any length of copied value
this.onChange(newValue);
this.inputHandler!.targetElement.selectionStart =
cursorPosition + val;
}
}

Can you suggest why keyboard.caretPosition taking null after paste.

**Comment by hodgef** [comment]
Hey @Niharika-Pat,

Please provide a full repro. It can be a sandbox or a test git repository. This will be more useful for debugging.

Regards,
Francisco Hodge
