### ISSUE TITLE
Cursor alignment and text adding issue in hebrew keyboard

### ISSUE THREAD

**Issue by chiragbytes** [hodgef/simple-keyboard#1788]
**^2.31.4**
I have 2.31.4 in my local, however I have also tried with latest version in this given demo URL, issue exist there also. [hebrew keyboard](https://hodgef.com/simple-keyboard/demos/?d=hebrew)

Scenario:
As you type hebrew letters from keyboard it works fine, suppose after finished typing you want to add some extra text at the first word or starting of the line, you move your cursor there and type something at that time that text does not appear on the exact location I moved my cursor but beyond it.

**Screen recording**
[Screen recording link](https://drive.google.com/file/d/1m0UKiZlgLMlXfTvp6yVVa4MH4Crjopsc/view)

**Comment by hodgef** [comment]
Hello @chiragbytes,

I think this issue has to do with the usage of `rtl: true`, which adds two invisible characters to the input.

> When set to true, this option adds [unicode directional control characters](http://unicode.org/reports/tr9/#Directional_Formatting_Codes) \u202B and \u202C to onChange() and getInput() returns. This helps to address issues when using simple-keyboard with right-to-left layouts.

https://hodgef.com/simple-keyboard/documentation/options/rtl/

For example, with the `rtl` option enabled:
![image](https://user-images.githubusercontent.com/25509135/203900733-89624315-5ed8-4aa7-bd77-5bb1e56794ee.png)

And without:
![image](https://user-images.githubusercontent.com/25509135/203900644-0b64d937-f866-4ea7-98f0-3e971768c764.png)

When I added this option I didn't take into account its effects on caret positioning. I will put out a fix for that asap.

**Comment by hodgef** [comment]
I have added a tentative fix for this issue in the latest release. Please feel free to update and try it out.

Regards,
Francisco Hodge
