### ISSUE TITLE
Using display options with layoutCandidates

### ISSUE THREAD

**Issue by angrykoala** [hodgef/simple-keyboard#1831]
**Is your feature request related to a problem? Please describe.**
I'm trying to use display tags along with layoutCandidates, with a configuration similar to the following:

```
{
            layout: {
                default: ["a b c {test}"],
            },
            display: {
                "{test}": "Test",
            },
            layoutCandidates: {
                "a": "{test} another",
            },
}
```

I expected `{test}` to be formatted as `Test` in the candidates menu, like with the normal keys, however, `{test}` is shown instead:
![Screenshot from 2023-01-03 16-34-10](https://user-images.githubusercontent.com/5960567/210400040-eafe3c7e-3590-44d6-992e-9b5967fea08c.png)

**Comment by hodgef** [comment]
Thanks for the suggestion, this should be supported as of the latest version. Please feel free to give it a try.

Regards,
Francisco Hodge
