### ISSUE TITLE
Insert HTML instead of text in layoutCandidates through display

### ISSUE THREAD

**Issue by angrykoala** [hodgef/simple-keyboard#1835]
**Is your feature request related to a problem? Please describe.**
Trying to use html tags in the layout candidate injects the html as text, instead of as a spam:

![Screenshot from 2023-01-09 21-16-36](https://user-images.githubusercontent.com/5960567/211410494-0d0a3b32-458d-42d0-a703-a765f5e3bf92.png)

```javascript
{
    display: {
        "{mod-hp}": `<img class="hp-key">`,
    },
    layoutCandidates: {
        "1": "{mod-hp} 2 3",
    },
};
```

**Describe the solution you'd like**
Instead of inserting the display value as text, to be inserted as part of a span (like in normal keys) so it is rendered accordingly:

![Screenshot from 2023-01-09 21-15-48](https://user-images.githubusercontent.com/5960567/211410824-055c4389-ddb9-4735-91aa-7811af0414ba.png)

**Additional context**
This is related to #1831

**Comment by hodgef** [comment]
Fixed in latest version. Thanks!

**Comment by angrykoala** [comment]
:open_mouth: Thanks for the quick response :clap:
