### ISSUE TITLE
Please follow semver

### ISSUE THREAD

**Issue by crfrolik** [hodgef/simple-keyboard#1838]
**Is your feature request related to a problem? Please describe.**

This project likes to make breaking changes in minor versions. This can cause headaches for users.

**Describe the solution you'd like**

Breaking changes should only happen in major releases.

**Comment by hodgef** [comment]
Hm you are completely right... Still, I'm not sure I would like to bump major version for every breaking change. I thought of major version as major collection of features (or an overhaul of sorts). Also I wanted to keep major versions synced between simple-keyboard and react-simple-keyboard. I agree that this is not semver though.

I would recommend to only auto-upgrade when you have good unit test coverage, or to read the release notes before upgrading. Your suggestion is valid and I will think about what balance I can strike here...
