### ISSUE TITLE
Firefox: Cursor always jumps to the end after typing a character

### ISSUE THREAD

**Issue by heebj** [hodgef/simple-keyboard#1839]
**Simple-keyboard version**
3.4.0

**Describe the bug**
Having a text input field which contains already text. 

1. Positioning the cursor in the middle of the text (e.g. to fix a typo) by mouse or touch.
2. On the simple-keyboard type a character or press backspace to delete a character.

=> The cursor always jumps to the end of the text after typing a single character. I would expect it to stay at the same position so that I can insert multiple characters at the same position. The behavior can be observed even on your [demo page](https://hodgef.com/simple-keyboard/demos/).

I also tried disableCaretPositioning but without the desired effect.

Thanks a lot for your work and thr great keyboard!

**Comment by hodgef** [comment]
I cannot repro this on the demo page, therefore I would need a repro in order to debug this.

However, since you mentioned an input that contains text. I will mention the following issue in case you haven't used `setInput`:
https://github.com/hodgef/simple-keyboard/issues/858#issuecomment-754394081

Will reopen once a repro sandbox is provided.

Thanks!
Francisco Hodge

**Comment by heebj** [comment]
Hi @hodgef 

Thanks for your very quick response!

I just tried it again with the demo page and it seems as if it is a Firefox related problem. I do the following:

1. Open your Demo page
2. Enter some characters with virtual or physical keyboard
3. Positioning the cursor in the middle of the text by mouse or touch.
4. On the simple-keyboard type a few characters

In Firefox, the first character is inserted at the cursor position and then the cursor automatically jumps to the end of the text. In Chrome it works fine.

Can you reproduce this as well?

**Comment by hodgef** [comment]
Thanks for the details @heebj,

Looks like the "selectionchange" event is returning wrong caret position values in Firefox. Here's a minimal JS repro:
https://codesandbox.io/s/solitary-violet-u9cknx?file=/src/index.js

![test](https://user-images.githubusercontent.com/25509135/212566692-57ef80bd-c13a-4c74-9148-b31bc5983bca.gif)

I have pushed a quick fix to ignore this event on Firefox, but I would suggest [reporting this to Mozilla](https://bugzilla.mozilla.org/home).

Regards,
Francisco Hodge
