### ISSUE TITLE
Special keys like alt, ctrl, shift, etc. are not released when the virtual keyboard loses the focus

### ISSUE THREAD

**Issue by sskorol** [hodgef/simple-keyboard#1841]
**Simple-keyboard version**: ^3.4.202
**Browser**: Chrome 109
**OS**: MacOS / Linux

**Describe the bug**
- Open a full keyboard [demo](https://hodgef.com/simple-keyboard/demos/?d=fullKeyboard)
- Press (and release) any system hotkey that switches the focus from the keyboard, e.g. `ctrl + f`, `alt + ~`, etc.
- Focus back the virtual keyboard.

**Expected**: all the keys on the virtual keyboard are released.
**Actual**: some keys (in most of the cases - the special ones like `alt, ctrl, cmd, shift`) are left "unreleased".

Note that it can be "fixed" by pressing the unreleased key once again.

**Screenshots**
![UX_BUG](https://user-images.githubusercontent.com/6638780/212761887-eba314c7-daf2-43f8-a17b-fb9df993dbfc.png)

**Comment by hodgef** [comment]
Hey @sskorol, I decided to make all `onKeyPress` behave the same, meaning no action unless it's decided by the dev. I think if I add this in now I will introduce a breaking change, therefore I would suggest to use `e.preventDefault()` instead.

For example, in the following demo:
https://codesandbox.io/s/n5mllkkmyl?file=/src/index.js

![image](https://user-images.githubusercontent.com/25509135/212767214-91b203cd-9b4c-43a5-b1ed-07008a06ff3e.png)

```js
/**
 * Physical Keyboard support
 * Whenever the input is changed with the keyboard, updating SimpleKeyboard's internal input
 */
document.addEventListener("keydown", (event) => {
  // Disabling keyboard input, as some keys (like F5) make the browser lose focus.
  // If you'd like to re-enable it, comment the next line and uncomment the following ones
  // event.preventDefault();
  if (event.key === "Alt") event.preventDefault();
  if (event.key === "F5") event.preventDefault();

  if (event.key === "ArrowUp") event.preventDefault();
  if (event.key === "ArrowDown") event.preventDefault();
  if (event.key === "ArrowLeft") event.preventDefault();
  if (event.key === "ArrowRight") event.preventDefault();
});
```

**Comment by hodgef** [comment]
Actually, now that I think of it - this will require you to roll out your own key press mechanism. I will provide a new option.

**Comment by hodgef** [comment]
Please feel free to pass the following option in the latest version of simple-keyboard:

```js
physicalKeyboardHighlightPreventDefault: true
```

Thanks,
Francisco Hodge

**Comment by sskorol** [comment]
@hodgef thanks, I've just tried the latest version, but facing the same issue.

Here's the component I use:
```js
const Keyboard = observer(() => {
    const {rosStore: { handleKeyboardShortcuts }} = useStore()
    const [layoutName, setLayoutName] = useState('default')
    const { classes } = useStyles();

    const onKeyPress = (button) => {
        if (button === '{capslock}') {
            setLayoutName(layoutName === 'default' ? 'shift' : 'default')
        }
        const key = syntethicKeysMap[button] || button
        handleKeyboardShortcuts(key)
    }

    const theme = useTheme()

    return (
        <div className='keyboard-wrapper'>
            <SimpleKeyboard
                layoutName={layoutName}
                onKeyPress={onKeyPress}
                theme={`hg-theme-default ${classes.root}`}
                baseClass={'simple-keyboard-main'}
                physicalKeyboardHighlight={true}
                physicalKeyboardHighlightPress={true}
                physicalKeyboardHighlightPreventDefault={true}
                physicalKeyboardHighlightTextColor={theme.palette.common.white}
                physicalKeyboardHighlightBgColor={theme.palette.background.keyboardButtonBgPressed}
                syncInstanceInputs={true}
                mergeDisplay={true}
                layout={layout}
                display={display}
                buttonTheme={buttonTheme}
                buttonAttributes={buttonAttributes}
            />
        </div>
    )
})

export default Keyboard
```

I also tried to `preventDefaults` from your previous comment like this:
```js
    const handleKeyDown = (event) => {
        event.preventDefault();
    }

    useEffect(() => {
        document.addEventListener('keydown', handleKeyDown);
        return () => document.removeEventListener('keydown', handleKeyDown);
    }, []);
```
But it only partially works. For example, `alt + f` works as expected, but `alt + tab` causes `alt` to remain highlighted. It's also reproducible in the sandbox you've shared above.

Any thoughts on what I'm doing wrong?

**Comment by sskorol** [comment]
I apologies for the confusion. Seems like I posted the issue to the wrong repo. I'm using [react-simple-keyboard](https://github.com/hodgef/react-simple-keyboard).

**Comment by hodgef** [comment]
No problem, react-simple-keyboard normally pulls deps at [4am EST](https://github.com/hodgef/react-simple-keyboard/blob/master/.github/dependabot.yml). But I've gone ahead and updated it.

Feel free to try the latest version of react-simple-keyboard (3.5.11) - the fix should be there.

Regards,
Francisco Hodge

**Comment by sskorol** [comment]
@hodgef ok, I checked it. Now this property behaves the same way as I described above in a `useEffect` with `preventDefault` snippet: some hotkeys are prevented, the others - not. For example, `alt + tab` still holds the `alt` key active after physical releasing. Or I have a custom system hotkey to take screenshots -> `alt + p`. It also causes the alt key to hang highlighted after releasing.

**Comment by hodgef** [comment]
Hey @sskorol, I have edited the behavior per the commit above, feel free to give it a try. If you still have issues, try to repro in the test listener you've created. Chances are that if you cannot block the default behavior then I likely won't be able either.

**Note:** there are combos like <kbd>alt</kbd>+<kbd>tab</kbd> that are not possible to override. Check out this answer for details:
https://stackoverflow.com/a/40434403

Regards,
Francisco Hodge

**Comment by sskorol** [comment]
@hodgef got it. Thanks for the link and a quick fix!
Just wonder if there's an API for releasing all the highlighted buttons at once. I can catch the window blur event which would signalize the focus switch. In this case, if there are some stuck buttons on the virtual keyboard, I'd call some method to release them. Does it make sense?

**Comment by hodgef** [comment]
Check out `keyboard.recurseButtons()`:
https://hodgef.com/simple-keyboard/documentation/methods/recursebuttons/

Most likely you can do something like this
```js
keyboard.recurseButtons(buttonElement => {
  buttonElement.removeAttribute("style");
});
```

**Comment by sskorol** [comment]
@hodgef in this case I'd need to access keyboard ref within a functional component. I tried `ref` attribute, but it doesn't work. Current value is null.

**Comment by sskorol** [comment]
Ok, seems like I found the way. Now it correctly handles `alt + tab`
```js
const Keyboard = observer(() => {
    const keyboard = useRef(null);

    const assignRef = (kb) => {
        keyboard.current = kb
    }

    const handleBlur = (event) => {
        keyboard.current.recurseButtons(buttonElement => {
            buttonElement.removeAttribute("style");
        });
    }

    useEffect(() => {
        window.addEventListener('blur', handleBlur);
        return () => window.removeEventListener('blur', handleBlur);
    }, []);

    return (
        <div className='keyboard-wrapper'>
            <SimpleKeyboard
                onInit={assignRef}
// ...
```

**Comment by hodgef** [comment]
You got it! Per the hooks demo:

![image](https://user-images.githubusercontent.com/25509135/213019371-6c125e73-93bd-4c1d-860f-e60dd573aa19.png)
https://hodgef.com/simple-keyboard/editor/?d=simple-keyboard/react-simple-keyboard-hooks-demo/tree/master

**Comment by sskorol** [comment]
Ah, damn, I also tried `keyboardRef` (as I found it in a source code). But I used it in a wrong way by trying to pass `keyboard` reference directly like this `keyboardRef={keyboard}` 🤦🏻‍♂️ 
Now I see what's the correct way of using it. Thanks!

**Comment by sskorol** [comment]
@hodgef hm, I just noticed that `physicalKeyboardHighlightPreventDefault={true}` blocks the other inputs I have in the app. I can't type anything there. Moreover, they are in completely different components on the other screen. So I wonder, how does this option may affect the global inputs state. Note that I use `@mui/material/InputBase`, but never get `onChange` event fired.

**Comment by hodgef** [comment]
Well, the change is a preventDefault on `keydown`/`keyup`:
https://github.com/hodgef/simple-keyboard/blame/master/src/lib/services/PhysicalKeyboard.ts#L31

I can see this issue happening if your inputs are reliant on these listeners.

What I can do is to only target the modifier keys instead of all keys, however it will still affect anything that relies on those. I will give that a try and update this thread.

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
I have [limited the preventDefault to modifier keys only](https://github.com/hodgef/simple-keyboard/blob/e49f06089f0a4cf2adda48fb9ca1ce0eb8abf4a0/src/lib/services/PhysicalKeyboard.ts#L30). If you want to access the [isModifierKey](https://github.com/hodgef/simple-keyboard/blob/e49f06089f0a4cf2adda48fb9ca1ce0eb8abf4a0/src/lib/services/PhysicalKeyboard.ts#L263) method elsewhere in your logic, you can access it through `keyboard.physicalKeyboard.isModifierKey`. Regards

**Comment by mujeebcpy** [comment]
there is a typo in  [isModifierKey](https://github.com/hodgef/simple-keyboard/blob/e49f06089f0a4cf2adda48fb9ca1ce0eb8abf4a0/src/lib/services/PhysicalKeyboard.ts#L263) f instead of d
