### ISSUE TITLE
invoke onKeyReleased when physical keyboard button realeased

### ISSUE THREAD

**Issue by alex-waverley** [hodgef/simple-keyboard#1846]
With the help of your library, I'm trying as much as possible to map the behavior of the physical keyboard to the virtual one (using `physicalKeyboardHighlight` property). At the moment, I am faced with a situation when I press the `shift` button on the physical keyboard, then the `onKeyPress` callback is invoked and there I change the layout to shift one (everything is ok), but when I release the `shift` button, the `onKeyReleased` callback does not work and I can't chage layout back.

It would be great to invoke `onKeyReleased` callback when `physicalKeyboardHighlight` property is set to `true`.

Or add another callback which will be invoked on `keyup` event.

**Additional context**
react-simple-keyboard version: ^3.5.17
Browser: Chrome 109.0.5414.87
OS: MacOS

**Comment by hodgef** [comment]
Hey @alex-waverley,

Try setting `physicalKeyboardHighlightPressUsePointerEvents: true`. Thanks!
