### ISSUE TITLE
[Question] Doubts on how to integrate

### ISSUE THREAD

**Issue by JFeldaca** [hodgef/simple-keyboard#1848]
Hi!

I've an a very simple electron app, who consist in "a simple fullscreen webbrowser" for our internal app use.

![image](https://user-images.githubusercontent.com/102365010/214078730-6a943818-7148-43ba-a6f8-2e91d69f0228.png)

As you can see, there is an input to put the url, and a serie of buttons to interact, including a keyboard icon to unfold a virtual keyboard.

I would love to be able to incorporate this keyboard when that icon is tapped, without losing focus on the input where the user is now.

In the Getting started guide I see that an input with class "input" is used to display and interact with the keyboard. With the URL input this wouldn't be a big problem, but in the rendering page I have no control over what class or ID that input has.

Would it be possible to "show" and make it work with the inputs from the visited pages?

Thanks for your time!

Regards,

**Comment by JFeldaca** [comment]
Adding to the topic, this APP is build with electron 22, so it is chrome 106 as web renderizer.

**Comment by hodgef** [comment]
Hello @JFeldaca,

I suggest to experiment a bit more with the keyboard. simple-keyboard doesn't really need any inputs to work, when you type it saves it internally and you can access the value through `onChange` and `keyboard.getInput()`. If you want to modify the internal value, you can use `keyboard.setInput()` per the [docs](https://hodgef.com/simple-keyboard/documentation/).

That being said, the main issue you're describing is not related to simple-keyboard. You would need to investigate how to alter/inject js into pages loaded through an iframe/webview in Electron. For example to add an event listener to all inputs in a given page. That part is out of the scope for me but I believe there's already some information online regarding this.
