### ISSUE TITLE
Prevent special keyst fromo attaching to input

### ISSUE THREAD

**Issue by bemon** [hodgef/simple-keyboard#1861]
I couldn find this feature, so is it possible to disable custom special keys ? For example, i want a key that hides keyboard. I added it to layout, but when clicked appends its value  to keyboard input.

How to define custom special keys like {shift}, {enter} etc. ?

**Comment by hodgef** [comment]
`{enter}` and `{shift}` do nothing by default, like all other "function keys" (except `{bksp}` and `{space}`). You would need to program their behavior in the `onKeyPress()`.

You can define any key, such as `{mykey}`, and use the [documentation](https://hodgef.com/simple-keyboard/documentation/) to customize it. For example:
https://codesandbox.io/s/dreamy-ives-luro32?file=/src/index.js

Any key not surrounded by curly braces will be appended to the input.

**Comment by bemon** [comment]
@hodgef thank you, i somehow miss it from docs.
