### ISSUE TITLE
LayoutCandidatesBox closing immediately if a candidate overlaps the key invoking the LayoutCandidatesBox 

### ISSUE THREAD

**Issue by gvolt** [hodgef/simple-keyboard#1884]
**Simple-keyboard version**
3.5.29

**Describe the bug**
Not sure if this is really a bug, but as the lengthy (sorry for that) title already says:

If a key has LayoutCandidates and the LayoutCandidatesBox overlaps this key, the candidate which is positioned over the key invoking the LayoutCandidatesBox will be selected automatically and the LayoutCandidatesBox gets closed immediately. This happens unless you hold the key until autorepeat sets in - but then at least on character of the key which invokes the LayoutCandidatesBox has already been put to the input field before one could select the desired candidate from the box.

The issue does only occur using a touchscreen, not if the key invoking the LayoutCandidatesBox is clicked on with a mouse.

This can be replicated with the [chinese keyboard demo](https://hodgef.com/simple-keyboard/editor/?d=hodgef/simple-keyboard-layouts-demos/tree/chinese) after adding

```
.simple-keyboard .hg-candidate-box {
  margin-top: 130px;
}
```

to "index.css". Then the LayoutCandidatesBox will overlap the keyboard so that touching the key "a" will expose the mentioned behaviour.

I discovered the issue coincidentally trying to save space on the display by placing the LayoutCandidatesBox over the keyboard. Playing around with "preventMouseDownDefault" and "preventMouseUpDefault" did not solve the issue.

**Comment by hodgef** [comment]
Hey @gvolt, I cannot repro this. Do you mind sharing a video or gif of the issue? Perhaps also more details regarding device/OS/browser. I tried on a Surface laptop with touchscreen (W11 on Edge).

Regards,
Francisco Hodge

**Comment by gvolt** [comment]
Hi @hodgef,

I have only Linux systems with touchscreens at hand. One is running openSUSE Tumbleweed (lastly updated yesterday) on an ancient MS Surface 3 Pro, browser is Firefox 110.0.1 (64bit). Another one is a Raspberry Pi equipped with the "original" Raspberry Pi Foundation 7" display. That one is running a Debian Buster (32bit) based OS; browser is chromium-browser (Chromium 92.0.4515.98 Built on Raspbian , running on Raspbian 10).

I have recorded a short video showing the chinese demo modified as described above. At first it shows touching the "a" key, i.e. using the touchscreen. After that I use the mouse to hit the "a" key.

In the first case the LayoutCandidateBox opens, the first candidate (which overlapped the "a" key) is selected automatically and the box gets closed immediately.

When the mouse is used, the LayoutCandidateBox is invoked, too, but stays open and waits for selecting one of the candidates.

[Recording20230309.webm](https://user-images.githubusercontent.com/36240972/224133226-f3fa29c3-b28d-453f-b20b-24be40a981a8.webm)

**Comment by gvolt** [comment]
@hodgef One piece of information I forgot to mention in my last post: The openSUSE Tumbleweed system uses Wayland, the Debian Buster-based Raspberry system uses X11. Since the problem occurs on both systems, this information may not be relevant.

**Comment by hodgef** [comment]
This is taking me a longer, since the repro takes a bit of work and sourcing some parts on my end. Sorry for the delays & I appreciate the patience on this!

**Comment by gvolt** [comment]
> Sorry for the delays & I appreciate the patience on this.

No, no, I am grateful that you are investigating the problem and working on it.

**Comment by hodgef** [comment]
Thanks @gvolt, I was able to confirm that the issue does happen on openSUSE with a touchscreen.

The solution I would suggest is to use `useMouseEvents: true`. There's something about the default PointerEvents implementation that is not working correctly, and since it happens on a narrow set of browsers I'm inclined to say that it's a browser issue.

Regards,
Francisco Hodge

**Comment by gvolt** [comment]
Thanks again @hodgef for looking into it!

> I was able to confirm that the issue does happen on openSUSE with a touchscreen

I don't think it is an openSUSE specific problem. As I had described above the issue occurs on a Debian Buster based Raspberry Pi system as well and also when using an Android mobile. Browsers I tried in the past were Firefox/Fennec and Chromium. Recently I checked with the stock browsers of LineageOS 17 and 18 and also just had the opportunity to test with Edge  (112.0.1722.34, 64bit) and Firefox (111.0.1, 64bit) on Windows 10. They all show the same effect - even on Windows so to me the issue appears not to be limited to Linux.

> The solution I would suggest is to use [`useMouseEvents: true`](https://hodgef.com/simple-keyboard/documentation/options/usemouseevents/).

Yes, that was my thought too and I already tried it. Unfortunately, with this option I lose the automatic repetition of the keys.

I could be completely wrong as I don't have enough knowledge, but after taking a look at your link regarding PointerEvents, I could imagine a solution might be possible with an option to control [setPointerCapture](https://javascript.info/pointer-events#pointer-capturing) on the keyboard's key elements. What do you think about this?

**Comment by hodgef** [comment]
Hey @gvolt, sorry for the delay.

I have pushed an update which should add TouchEvents support for the CandidateBox. Try out the following options and I believe your issue will be solved.

```js
preventMouseDownDefault: true,
useMouseEvents: true,
autoUseTouchEvents: true
```

I have not found a way to get it to work with PointerEvents, but if you want to explore your proposed approach and raise a PR I would definitely appreciate it.

Thanks!
Francisco Hodge

**Comment by gvolt** [comment]
@hodgef Many thanks for your efforts, I appreciate that very much.! Also sorry for the late reply, but had to find time to do some testing on various platforms and sum up the results:

1. On Lineage 17.1 and 19.1 powered Android devices your fix and the proposed keyboard options work as expected - as well in Lineage stock browser as in Fennec (112.2.0).

2. On openSUSE Tumbleweed (Gnome desktop 44.1 running on Wayland) using Firefox 112.0.2 the issue from my initial report is solved, but now the following problems occur:

    When you touch a key and hold the finger on the key no character appears in the input field. When you lift the finger and touch the key again the input field gets filled by auto repeating the character of the touched key infinitely (until you touch another key).

   Expected behaviour would be the input field showing the character of the pressed key and then auto repeating it until the finger is lifted.

3. On Windows 10 (64bit) using Edge (112.0.1722.64) neither touching the keys nor clicking on them with a mouse generates characters in the input field.

   Firefox (112.0.1) behaves similar like on openSUSE: When you touch a key and hold the finger on the key no character appears in the input field. "Instead" a rectangle shows up around the touched area which disappears as soon as you lift the finger; auto repeat does not work.

6. On the Debian (Buster) based system mentioned above, Chromium shows similar behaviour to Edge under Windows: Neither touching the keys nor clicking on them with a mouse generates characters in the input field. This changes after setting the keyboard option "autoUseTouchEvents" to "false" - but then auto repetition of keys is lost.

**Comment by gvolt** [comment]
Skimming through "keyboards.ts" the candidates box seems to get opened by [calling "showCandidatesBox"](https://github.com/hodgef/simple-keyboard/blob/5031cf1baa1d99d6742d2198430602548bb4894f/src/lib/components/Keyboard.ts#L566) at ["onKeyPress" events](https://github.com/hodgef/simple-keyboard/blob/5031cf1baa1d99d6742d2198430602548bb4894f/src/lib/components/Keyboard.ts#L492) from a key that has candidates.

Could it be a solution to open the candidates box only when the "onKeyReleased" event occurs?

I am far from familiar with the code of simple-keyboard, so bear with me if my idea is completely off. ;)

**Comment by hodgef** [comment]
> Skimming through "keyboards.ts" the candidates box seems to get opened by [calling "showCandidatesBox"](https://github.com/hodgef/simple-keyboard/blob/5031cf1baa1d99d6742d2198430602548bb4894f/src/lib/components/Keyboard.ts#L566) at ["handleButtonClicked"](https://github.com/hodgef/simple-keyboard/blob/cb1c598432642c12d387ef0ad1799c36fe2e80ae/src/lib/components/Keyboard.ts#L449) from a key that has candidates.
> 
> Could it be a solution to open the candidates box only when an event calling "handleButtonMouseUp" occurs?
> 
> I am far from familiar with the code of simple-keyboard, so bear with me if my idea is completely off. ;)

I think this might bring along other issues down the line. My recommendation would still be the workarounds I shared above.

Unfortunately, I cannot add a fix for every browser issue. I recall an issue in Firefox (on Linux exclusively) where a key would stay pressed forever (https://github.com/hodgef/simple-keyboard/issues/1333). I think you also brought this up in a previous comment. In that case I recommended disabling buttonHold. I'd rather do that than to come up with a series of hacks that over time could bring more problems and be hard to maintain.

That being said, you can clone the repo and try your solution out or use a [module](https://hodgef.com/simple-keyboard/modules/) to override existing behavior in the code.

**Comment by gvolt** [comment]
Thank you very much for your efforts!

> Unfortunately, I cannot add a fix for every browser issue.

Yes, I understand that completely.

I'm still trying find a browser-independent solution where I can preserve auto-repeat. But the different handling of the relevant events by different browsers in different environments is a thankless situation.
