### ISSUE TITLE
Use your actual keyboard keys for virtual keyboard

### ISSUE THREAD

**Issue by YahorLukyanchyk** [hodgef/simple-keyboard#1886]
Hi! I was looking for a ready solution for detecting what keyboard key was pressed and based on it doing a nessesary action and found your simple-keyboard. I went thro some demos and documentation and couldn't really find any option/method for this. I'm a beginner in this and in case if you have some suggestion for me I will be happy to hear it and try it on my project. On my side it's working only when I'm pressing the buttons with my mouse, but I really need it to work with my actual keys pressing.

Looking forward to your reply!

**Comment by hodgef** [comment]
Hey @YahorLukyanchyk,

Check out the following options:
https://hodgef.com/simple-keyboard/documentation/options/physicalkeyboardhighlight/
https://hodgef.com/simple-keyboard/documentation/options/physicalkeyboardhighlightpress/

Regards,
Francisco Hodge
