### ISSUE TITLE
onchange event is triggered endlessly

### ISSUE THREAD

**Issue by jiangyh1024** [hodgef/simple-keyboard#1898]
https://jake.stackblitz.com/edit/angular-pau3um?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Fstyles.scss

it is not happening on my laptop, but it's happening on the real  machine.with touchable screen and also happening on some of my colleagues; computers

first enter a wrong code like '111111', and then see whether the onchange event is triggered endlessly ?

**Comment by hodgef** [comment]
Are you trying it on a Linux machine? I cannot repro on a Surface laptop with touchscreen (W11 on Edge). Please provide some details like device/OS/browser. Will reopen the ticket when that is provided. Thanks!

**Comment by jinelleB** [comment]
Hi @hodgef, I'm having this issue too. Sharing some info for your reference. Thanks!

Browser: Firefox v.119.0
Device: Macbook Air with M2 chip
OS: macOS Sonoma v14.0

**Comment by hodgef** [comment]
Unfortunately I could not repro this on my laptop with touchscreen, I tried on Windows and Linux.

If someone else comes across this using search, I would appreciate if they could [clone the repro](https://github.com/hodgef/simple-keyboard#to-run-demo-on-your-own-computer) and debug it on their device by setting port: "0.0.0.0" [here](https://github.com/hodgef/simple-keyboard/blob/2db277f3eb0742dfa9bc64c88f0b6f65d2642de6/webpack.config.demo.js#L17) and accessing the app in their device through local IP.

Until then, the option will be to use [disableButtonHold](https://hodgef.com/simple-keyboard/documentation/options/disablebuttonhold/) to disable the button hold feature.

Thank you,
Francisco Hodge
