### ISSUE TITLE
Simple-keyboard with Chang's spatial navigation

### ISSUE THREAD

**Issue by xo-vision** [hodgef/simple-keyboard#1910]
For a SmartTV demo I need to use keyboard/spatial navigation. 

Unfortunatley the module "Keyboard Navigation" collides with the module I am using:  https://github.com/luke-chang/js-spatial-navigation.

So I tried making Changs modul to work with simple keyboard like this:

window.addEventListener("load", function () {
  // Initialize
  SpatialNavigation.init();
  // Define navigable elements (anchors and elements with "focusable" class).
  SpatialNavigation.add({
    selector: ".hg-button",
  });
  // Make the *currently existing* navigable elements focusable.
  SpatialNavigation.makeFocusable();
  // Focus the first navigable element.
  SpatialNavigation.focus();

  // Event listener for pressing OK/Enter
  window.addEventListener("sn:enter-down", (event) => {
    console.log("From SN: "+ event.target.getAttribute("data-skbtn")); // works
    event.target.click(); // does not work
  });
});

The magic is in "sn:enter-down: it responds to pressing OK/Enter on a specific  hg-button element. This works perfectly, except that sending the click event to the hg-button element has no effect.

In theory it should behave like I clicked the element, but it does not.

Question: how can I simulate a click on a hg-button element?

**Comment by xo-vision** [comment]
One more insight: everything seems to work perfectly  when I include your "Keyboard Navigation" module, but remove the keydown event listener, ie:

/*
document.addEventListener(
  "keydown",
  e => {
    if (e.key === "ArrowUp") keyboard.modules.keyNavigation.up();
    else if (e.key === "ArrowDown") keyboard.modules.keyNavigation.down();
    else if (e.key === "ArrowLeft") keyboard.modules.keyNavigation.left();
    else if (e.key === "ArrowRight") keyboard.modules.keyNavigation.right();
    else if (e.key === "Enter") keyboard.modules.keyNavigation.press();
  },
  false
);
*/

As a workaround I can live with that, though I would prefer not to load too much unnecessary code and solely rely on Chang;'s spatial navigation, as SmartTVs tend to have low memory and performance.

Let me explain, why I need to use Chang's spatial navigation module: as there are other interactive elements on the screen, I need to use a more global cursor key navigation that also includes other on-screen elements. 
With your "Keyboard Navigation" module cursor navigation would be limited only to the keyboard module. This might be true for anybody that needs to apply cursor navigation.

**Comment by hodgef** [comment]
You can try the option `useMouseEvents: true`
https://hodgef.com/simple-keyboard/documentation/options/usemouseevents/

Regards,
Francisco Hodge

**Comment by xo-vision** [comment]
Hello Francisco!

I can confirm that this works, thank you!

Also there is no need to add the "Keyboard Navigation" module anymore, so that's really great!
