### ISSUE TITLE
Physical backspace doesn't fire on MacOS

### ISSUE THREAD

**Issue by n-ext** [hodgef/simple-keyboard#1932]
**Simple-keyboard version**: 3.5.48
As some bugs have been addressed in later versions, please ensure you are running the latest.

**Describe the bug**
Pressing physical backspace isn't catched by simple keyboard. This problem doesn't occur on other keys.
Debug log:
```
KeyboardEvent {isTrusted: true, key: 'Backspace', code: 'Backspace', location: 0, ctrlKey: false, …}
```

**Comment by hodgef** [comment]
Could not repro here:
https://codesandbox.io/s/amazing-kowalevski-9t13jx

Notice that the key is called `{backspace}`.

Per the docs (in case it applies):
> For functional keys such as shift, note that the key’s event.code is used. In that instance, pressing the left key will result in the code ShiftLeft. **Therefore, the key must be named {shiftleft}.**
https://hodgef.com/simple-keyboard/documentation/options/physicalkeyboardhighlight

Regards,
Francisco Hodge
