### ISSUE TITLE
Suggestion box unable to work correctly

### ISSUE THREAD

**Issue by kulipo** [hodgef/simple-keyboard#1945]
I tried the following example：

https://hodgef.com/simple-keyboard/editor/?d=hodgef/simple-keyboard-layouts-demos/tree/chinese

when i tried modify the keyboard's css in file "index.css", I have modified the following content:

.simple-keyboard {
  max-width: 850px;
}

to

.simple-keyboard {
  max-width: 850px;
  position: absolute;
  bottom: 0;
}

then I found that the candidatesBox not displaying correctly, quickly appearing and  then disappearing.
Hope to receive help

**Comment by hodgef** [comment]
Hey @kulipo,

If the issue appeared after your changed something, I recommend you use your browser's Dev Tools to properly debug your issue, for example you can try overriding/adjusting the CandidateBox CSS. 

Regards,
Francisco Hodge
