### ISSUE TITLE
Link to demos doesn't work

### ISSUE THREAD

**Issue by Zireael07** [hodgef/simple-keyboard#1955]
The hodge site just doesn't open. No 404, just forever empty

**Comment by hodgef** [comment]
I can't repro the issue:

![image](https://user-images.githubusercontent.com/25509135/236548623-711ba282-13b7-463b-a5f8-5c7264da0238.png)

The page is hosted on Github Pages, so any downtime will be temporary. If you keep having issues, check out your DevTools in case your are blocking JS.

Thanks,
Francisco Hodge

**Comment by Zireael07** [comment]
You're right, it works today, must've been a temporary network issue
