### ISSUE TITLE
Allow adding custom attributes to keyboard buttons.

### ISSUE THREAD

**Issue by ecin** [hodgef/simple-keyboard#196]
**Is your feature request related to a problem? Please describe.**
In order to improve screenreader pronunciation of the keyboard's keys, it'd be useful to allow setting a custom `aria-label` value on each key, e.g. `aria-label='bee'` on the `b` key. 

**Describe the solution you'd like**
A possible generic solution would be to allow setting arbitrary attributes on specified keys, similar to how the current API allows us to set a custom class on a key. 

```javascript
<Keyboard
    buttonAttributes={[
        {
            aria-label: 'bee',
            buttons: 'b B'
        }
    ]}
/>
```

**Describe alternatives you've considered**
Presumably we could do this manually after the keyboard has been rendered by using one of the event hooks (e.g. `onRender`). I still feel that a specific API addition would better serve developers though. Let me know your thoughts!

**Additional context**
Hope this change helps with https://github.com/votingworks/bmd/issues/518

**Comment by hodgef** [comment]
Hello @ecin,

The option `buttonAttributes` is now available of the latest versions:

- simple-keyboard `2.25.0` [(Docs)](https://simple-keyboard.com/documentation/#buttonAttributes)
- react-simple-keyboard `1.26.0` [(Docs)](https://simple-keyboard.com/react/documentation/#buttonAttributes)

Feel free to reach out if you find any issues.

Regards,
Francisco Hodge

**Comment by ecin** [comment]
Wow, thanks for the super prompt response, @hodgef!
