### ISSUE TITLE
cannot set properties of undefined (setting 'SimpleKeyboard')  

### ISSUE THREAD

**Issue by MarcelFinkbeiner** [hodgef/simple-keyboard#1965]
Hello,

**Simple-keyboard version**
3.5.59

**Describe the bug**
I'm getting this error after startup.
The stack is: vue3, vite, electron, ts.

**Screenshots**
```
Uncaught TypeError: Cannot set properties of undefined (setting 'SimpleKeyboard')
    at index.js:12:204
    at index.js:12:209
(anonymous) @ index.js:12
(anonymous) @ index.js:12

```
the index.js file is in /node_modules/simple-keyboard/build

<img width="763" alt="image" src="https://github.com/hodgef/simple-keyboard/assets/133217468/17b80a07-5d4d-4f57-b2f5-0d11aa091506">

**Comment by hodgef** [comment]
Hello @MarcelFinkbeiner, when you click on the link "index.js:...", what is the variable that is undefined? I'm guessing that this is `window`, and if so you can try making sure that window is defined before importing SimpleKeyboard.
