### ISSUE TITLE
How to Add string name "space" to spacebar and show tooltip for keys on hover.

### ISSUE THREAD

**Issue by SciTechDude** [hodgef/simple-keyboard#1974]
Hi,
I am working on creating a non-english language keyboard for my application and would like to have following.

1) Add string name "space" to spacebar - Currently its shows as blank - (no name).  for other keys e.g. tab , it shows as 'tab'. why not  have name for space key?
2) Show tooltip for keys on hover. e.g. if I hover say 'a' , key , the tooltip would show custom helper data for 'a' key. This will help non-native user of that language.

I am using "react-simple-keyboard": "^3.5.76" and  MUI ^5.12.1

Thanks.

**Comment by hodgef** [comment]
Hello @SciTechDude,

simple-keyboard is simple by default but can be easily extended. In your case I suggest to just add your desired functionality in the `onRender`:

https://codesandbox.io/s/eager-ives-x6i5m9?file=/src/index.js

For more complex alterations of the keyboard behavior, you can create a [module](https://hodgef.com/simple-keyboard/modules/).

Thanks,
Francisco Hodge

**Comment by SciTechDude** [comment]
Thanks @hodgef  - the solution works as required. However,  I've need for binding a  external tooltip component (e.g. https://mui.com/material-ui/react-tooltip/) to each of the button with its custom message using card? I'll try it out and ask separate question if needed.
