### ISSUE TITLE
Does not support Node.js v18.16.0

### ISSUE THREAD

**Issue by mopduan** [hodgef/simple-keyboard#1977]
**Simple-keyboard version**
3.5.64

**Describe the bug**
`npm i` Error! Does not support Node.js v18.16.0

**Screenshots**
<img width="1235" alt="image" src="https://github.com/hodgef/simple-keyboard/assets/675025/cf35cc7c-81c8-4f9b-b54d-a89e541878ea">

**Comment by gvolt** [comment]
IIRC you can workaround this issue using

`export NODE_OPTIONS=--openssl-legacy-provider && npm run build`

**Comment by hodgef** [comment]
I updated the Webpack version, which should fix the issue out of the box (https://github.com/hodgef/simple-keyboard/commit/5e3a0370fd70a9f03606983a1ba0553681af7982). Please let me know if you still encounter the issue. Thanks!

**Comment by mopduan** [comment]
> I updated the Webpack version, which should fix the issue out of the box ([5e3a037](https://github.com/hodgef/simple-keyboard/commit/5e3a0370fd70a9f03606983a1ba0553681af7982)). Please let me know if you still encounter the issue. Thanks!

After update simple-keyboard to latest version, everything is ok! 

Thanks for your quick fix!
