### ISSUE TITLE
Configure different layoutCandidates for lower/upper case letters

### ISSUE THREAD

**Issue by romain-aragon** [hodgef/simple-keyboard#1993]
Actually when you have
layoutCandidates: {
    a: "à â ª æ á ä ã å ā",
    A: 'À Â ª Æ Á Ä Ã Å Ā'
  }

You will receive 'a' or 'A' on the onKeyPress event, but in both case the first layout Candidate (in the exemple lower a) is displayed

A turn around is to change the layoutCandidate when you toogle defaut/shift layouts

**Comment by hodgef** [comment]
Hello @romain-aragon,

You can use the option `layoutCandidatesCaseSensitiveMatch: true`

Regards,
Francisco Hodge

**Comment by romain-aragon** [comment]
Thanks !
