### ISSUE TITLE
Quickly typing on iPads.

### ISSUE THREAD

**Issue by jantuitman** [hodgef/simple-keyboard#2]
This is probably more an issue of your demo and the documentation than of the library: if you quickly type on an iPad  there is a high chance you will trigger a double tap zoom, which is built into mobile safari. So on the page, zooming should probably be disabled for the keyboard to be useful on an iPad.

But great library!

**Comment by hodgef** [comment]
Hello Jan, I'll take a look into this today and update the CodeSandbox examples, readme and other demos.

Thank you for the feedback!

**Comment by hodgef** [comment]
Hello @jantuitman,

This bug should now be fixed (as of version ^2.3.7).
If you see this bug pop-up again, please do let me know and I'll reopen the ticket :)

All the best,
Francisco Hodge

**Comment by jantuitman** [comment]
Thanks! It works.
