### ISSUE TITLE
Display sub keys in default layout 

### ISSUE THREAD

**Issue by dzikoysk** [hodgef/simple-keyboard#2016]
I'm looking for a convenient way to display sub key in the default layout for multilanguage keyboard. I need this for 2 reasons:

* Functional: I need to annotate Korean keyboard with a-Z letters just like in [Branah keyboard](https://www.branah.com/korean)
* Cosmetic: I want to annotate other symbols & layouts with their shift-variants known from regular keyboards

By sub key, I mean the alt key that will be applied with shift and that in most cases is displayed above the standard key, e.g.:

* Apple physical keyboard:

![obraz](https://github.com/hodgef/simple-keyboard/assets/4235722/8341774b-ad4f-4235-b85e-775d0e42c2e4)

* Windows virtual keyboard:

![obraz](https://github.com/hodgef/simple-keyboard/assets/4235722/866ce639-d103-420c-95fd-2c46b3b0d3c8)

To be fair, I rarely see keyboards without these alt keys, so the default impl of simple-keyboard looks quite unnatural. I've seen there's a possibility to adjust the renderer key by key with e.g. [`display property`](https://github.com/hodgef/simple-keyboard/issues/636), but I'd treat as a cumbersome workaround rather than a real solution to the issue. The most user-friendly solution that comes to my mind would be a possibility to define these keys at `layout` level, e.g.:

```javascript
layout={{
  default: [
    "`/~ 1/! 2/@ 3/# 4/$ 5/% 6/^ 7/& 8/* 9/( 0/) -/_ =/+ {bksp}",
```

would result in:

![obraz](https://github.com/hodgef/simple-keyboard/assets/4235722/fcc437c1-77ef-49e8-a412-3b2d4779edc2)

Alt keys should also share the same css class, so users can easily style it :)

**Comment by hodgef** [comment]
Hello @dzikoysk,

simple-keyboard is meant to be simple yet extensible. Feel free to try out the options and build something that fits your needs.

For instance, you could create a function that displays the desired alt keys on render:
https://codesandbox.io/s/beautiful-banzai-3x7mm7?file=/src/index.js

I will file this ticket as a [Proposal](https://github.com/hodgef/simple-keyboard/projects/3#card-89578139) for consideration in a future simple-keyboard release.

Regards,
Francisco Hodge

**Comment by CodingWithTashi** [comment]
@dzikoysk 
It would be great if you could share how you have initialize Keyboard and style the overlay.
