### ISSUE TITLE
If input has default value, it resets input after clicking on keyboard button

### ISSUE THREAD

**Issue by dmitrijsmihailovs** [hodgef/simple-keyboard#2018]
**Simple-keyboard version**
3.6.14

**Describe the bug**
If input has set "value" attribute, after clicking on keyboard buttons it resets the value and starts from empty value.
For example, if input already has value "test", clicking button "a", input will show only "a"
Here is forked example from showing/hiding keyboard with added "value" attribute: https://codesandbox.io/s/recursing-kate-vlc6nn

**Comment by hodgef** [comment]
Hello @dmitrijsmihailovs,

You would need to sync your default value with the internal keyboard input. More details here:
https://github.com/hodgef/simple-keyboard/issues/55#issuecomment-466401011

Regards,
Francisco Hodge
