### ISSUE TITLE
Can't override default style

### ISSUE THREAD

**Issue by NathanTe** [hodgef/simple-keyboard#2019]
**"simple-keyboard": "^3.6.15"
"simple-keyboard-layouts": "^3.2.20"**

**Describe the bug**
I'm not able to change the styling of the class `hg-rows, hg-row, hg-button`, I want to make the buttons a dynamic height. Because now my keyboard is overflowing the parent so i want to make the keys smaller. If you look closely you will see the bottom buttons are cut off

**Screenshots**
[stablitz url](https://stackblitz.com/edit/stackblitz-starters-qlcgay?file=src%2Fkeyboard%2Fkeyboard.component.css)

**Comment by hodgef** [comment]
Hello @NathanTe,

You can make your selectors more specific so that they override the default ones. One way to do this is through the `theme` option.

Check out the Angular example for this demo:
https://hodgef.com/simple-keyboard/demos/?d=darkTheme

Regards,
Francisco Hodge

**Comment by NathanTe** [comment]
Well after some playing around with the example. I figured out that the `ViewEncapsulation.None` is crucial in Angular to make your custom styling work. After that everything worked flawlessly.

**Comment by hodgef** [comment]
Good to hear that it works now. Here's some more details about the `ViewEncapsulation.None` requirement and an alternative solution: https://github.com/hodgef/simple-keyboard/issues/580#issuecomment-641404568

Regards,
Francisco Hodge
