### ISSUE TITLE
Chinese support please ^^

### ISSUE THREAD

**Issue by JocelynFloresz** [hodgef/simple-keyboard#2056]
**Is your feature request related to a problem? Please describe.**
I can use this keyboard to output chinese

**Describe the solution you'd like**
none

**Describe alternatives you've considered**
windows virtual keyboard

**Additional context**

**Comment by hodgef** [comment]
Hello @JocelynFloresz, this is currently possible with Pinyin:
https://hodgef.com/simple-keyboard/demos/?d=chinese

Hope that helps. Thanks!
Francisco Hodge

**Comment by JocelynFloresz** [comment]
> Hello @JocelynFloresz, this is currently possible with Pinyin: https://hodgef.com/simple-keyboard/demos/?d=chinese
> 
> Hope that helps. Thanks! Francisco Hodge

I think this is a Chinese keyboard layout. But I want to type chinese output to screen
