### ISSUE TITLE
Simple keyboard doesn't work with Vue 3

### ISSUE THREAD

**Issue by vishuvt** [hodgef/simple-keyboard#2057]
**Simple-keyboard version**
 "simple-keyboard": "latest",

**Describe the bug**
I was using simple keyboard in Vue 2 and it just worked fine .After migrating my application to Vue 3 it stopped working .Getting this error 

**Screenshots**
![image](https://github.com/hodgef/simple-keyboard/assets/128807463/ed490dcc-fed9-4fc9-8dca-fa8de1c5f121)

My dependencies   "dependencies": {
    "
    "eslint-plugin-vuetify": "^2.0.0-beta.4",
    "lodash.isequal": "^4.5.0",
    "simple-keyboard": "latest",
    "vue": "^3.2.47",
    "vue-draggable-next": "^2.1.1",
    "vue3-tour": "^0.3.4",
    "vuetify": "^3.3.2"
  },
  "devDependencies": {
    "@babel/core": "^7.12.16",
    "@babel/eslint-parser": "^7.12.16",
    "@rollup/plugin-alias": "^5.0.0",
    "@rollup/plugin-commonjs": "^24.1.0",
    "@rollup/plugin-image": "^3.0.2",
    "@rollup/plugin-node-resolve": "^15.0.2",
    "@rollup/plugin-terser": "^0.4.1",
    "@vue/cli-plugin-babel": "~5.0.0",
    "@vue/cli-plugin-eslint": "~5.0.0",
    "@vue/cli-plugin-pwa": "~5.0.0",
    "@vue/cli-plugin-router": "~5.0.0",
    "@vue/cli-plugin-unit-jest": "~5.0.0",
    "@vue/cli-plugin-vuex": "~5.0.0",
    "@vue/cli-service": "~5.0.0",
    "@vue/compiler-sfc": "^3.1.5",
    "@vue/eslint-config-standard": "^8.0.1",
    "@vue/test-utils": "^2.0.0-0",
    "@vue/vue3-jest": "^27.0.0-alpha.1",
    "axios": "^1.4.0",
    "babel-jest": "^27.0.6",
    "babel-loader": "^9.1.2",
    "concurrently": "^8.0.1",
    "copy-webpack-plugin": "^11.0.0",
    "css-loader": "^6.7.4",
    "css-minimizer-webpack-plugin": "^5.0.0",
    "eslint": "^8.41.0",
    "eslint-config-google": "^0.14.0",
    "eslint-formatter-codeframe": "^7.32.1",
    "eslint-plugin-import": "^2.25.3",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^6.1.1",
    "eslint-plugin-vue": "^9.2.0",
    "jest": "^27.0.5",
    "jest-junit": "^16.0.0",
    "mini-css-extract-plugin": "^2.7.6",
    "moment": "^2.29.4",
    "rollup": "^2.79.1",
    "rollup-plugin-copy": "^3.4.0",
    "rollup-plugin-postcss": "^4.0.2",
    "rollup-plugin-vue": "^6.0.0",

    "webpack": "^5.80.0",
    "webpack-cli": "^5.0.2"

My rollup config
![image](https://github.com/hodgef/simple-keyboard/assets/128807463/859c4bb0-7594-46dc-96e0-7aa7dfab1201)

Using Node 18.16

**Comment by hodgef** [comment]
Hello @vishuvt,

This seems to work fine here:
https://codesandbox.io/s/nameless-hill-p49shl?file=/src/App.css

Feel free to provide a repro if you still experience the issue.

Thanks,
Francisco Hodge
