### ISSUE TITLE
When the input box is focused, clicking the keyboard key input box will lose focus. Can you support the input box without losing focus when clicking the key?

### ISSUE THREAD

**Issue by Evie66** [hodgef/simple-keyboard#2064]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hodgef** [comment]
Hello @Evie66,

Check out the demos linked in the `preventMouseDownDefault` docs entry:
https://hodgef.com/simple-keyboard/documentation/options/preventmousedowndefault/

Regards,
Francisco Hodge

**Comment by grojguy** [comment]
> Hello @Evie66,
> 
> Check out the demos linked in the `preventMouseDownDefault` docs entry: https://hodgef.com/simple-keyboard/documentation/options/preventmousedowndefault/
> 
> Regards, Francisco Hodge

Hello @hodgef!

I have visited the link above, and I see...

![image](https://github.com/hodgef/simple-keyboard/assets/3414035/c55331a8-b66c-4b31-9b94-beab7cc77283)

However, I think the vue example has a problem. The "preventMouseDownDefault" option is nowhere to be found in that example. I was very bewildered until I decided to look at the other 2 examples (JS, react) and I saw the option used there.

Thank you

**Comment by hodgef** [comment]
@amitbk This is default browser behavior, for more info you can see this issue: https://github.com/hodgef/simple-keyboard/issues/80#issuecomment-495708880

In this thread I also shared the solution, please check out the existing answers.

Thanks!
Francisco Hodge
