### ISSUE TITLE
Add esm output in build/index.modern.esm.js

### ISSUE THREAD

**Issue by rwv** [hodgef/simple-keyboard#2070]
**Is your feature request related to a problem? Please describe.**
Could you please add esm js file in build folder? ESM enables `<script type="module">` in browser and avoid pollute `window` scope.

**Describe the solution you'd like**
Use webpack to output an esm file

**Describe alternatives you've considered**
```
<script type="module">
import simpleKeyboard from 'https://cdn.jsdelivr.net/npm/simple-keyboard@3.6.40/+esm'
</script>
```

This is a solution, but I want to enable SRI in my project therefore JsDelivr generated esm might not be suitable for me.

**Additional context**

**Comment by rwv** [comment]
https://webpack.js.org/configuration/output/#outputlibrarytype

**Comment by rwv** [comment]
Another related issue is that when I use 
``` js
const script=document.createElement("script");
script.src="https://cdn.jsdelivr.net/npm/simple-keyboard@latest/build/index.js";
document.body.appendChild(script);
```
to create SimpleKeyboard.

The creation seems to conflicts with [`js-dos`](https://github.com/caiiiycuk/js-dos) (a emscripten project). And `window.SimpleKeyboard` is `undefined` even after `script.onload`. I thought this may be related to some window scope pollution issue and `esm` may solve this issue.

**Comment by hodgef** [comment]
Hello @rwv thanks for the suggestion,

I have added [index.modern.esm.js](https://github.com/hodgef/simple-keyboard/blob/master/build/index.modern.esm.js) to version 3.7.0. Hopefully it does work (it appears [Webpack support is experimental](https://github.com/webpack/webpack/issues/2933) at this time). Let me know if you run into any issues.

Regards,
Francisco Hodge
