### ISSUE TITLE
space, <, > keys are not working as expected

### ISSUE THREAD

**Issue by vamsideepak** [hodgef/simple-keyboard#2080]
when I click on space , <, > on simple-keyboard instead of giving space it is displaying {space},<,> on the any input of angular form controls and also when I click on clear it is clearing the all the inputs.

`import { AfterViewInit, Component, OnInit, OnDestroy } from '@angular/core';
import Keyboard from 'simple-keyboard';
import { select, Store } from '@ngrx/store';
import { Observable } from 'rxjs';
import * as _actions from 'src/app/store/actions/auth.actions';
import { enrollmentSelector2 } from 'src/app/store/selectors/enroll/ui.Selectors';

import {
  inputFieldSelector,
  currentKeyboardSelector,
  currentPageSelector,
} from 'src/app/store/selectors/enroll/pinAndKeyboardSelectors';
import { updateEnrollmentAction } from 'src/app/store/actions/auth.actions';
import { CurrentPage } from 'src/consts/gameData/pageState';

@Component({
  selector: 'app-keyboard',
  templateUrl: './keyboard.component.html',
  styleUrls: ['./keyboard.component.scss'],
})
export class KeyboardComponent implements AfterViewInit, OnInit, OnDestroy {
  value = '';
  keyboard: Keyboard;
  keyboardClassName = 'kve-keyboard';
  keyboardFormat: any = {
    colorProperties: {
      '--primary-color': '#FFFFFF',
      '--primary-background': '#B89C40',
      '--standardBtn-background': '#EAEAEA',
      '--standardBtn-color': '#000000',
      '--font-size-key': '26px',
      '--font-size-small-key': '16px',
      '--font-family-text': 'Helvetica-Regular',
      '--width-key': '62px',
      '--width-backspace-key': '66px',
      '--width-net-key': '109px',
      '--width-mail-key': '119px',
      '--width-hotmail-key': '162px',
      '--width-space-key': '442px',
      '--width-at-key': '178px',
      '--width-clear-key': '100px',
      '--width-arrow-key': '80px',
      '--width-com-key': '109px',
      '--height-key': '62px',
      '--height-last-key': '52px',
    },
    maxLength: {
      phonenumber: 12,
    },
    inputpattern: {
      phonenumber: /^[0-9\-]+$/,
    },
    withEmail: [
      `1 2 3 4 5 6 7 8 9 0 {bksp} .net`,
      `q w e r t y u i o p @hotmail.com`,
      `a s d f g h j k l - _ @yahoo.com`,
      `z x c v b n m . @ @gmail.com`,
      `.com {space} {clear} @aol.com`,
    ],
    default: [
      `1 2 3 4 5 6 7 8 9 0 {bksp}`,
      `q w e r t y u i o p`,
      `a s d f g h j k l - _`,
      `z x c v b n m . @`,
      `< {space} > {clear}`,
    ],
    keyboardDefaultCAPS: [
      `1 2 3 4 5 6 7 8 9 0 {bksp}`,
      `Q W E R T Y U I O P`,
      `A S D F G H J K L - _`,
      `Z X C V B N M . @ `,
      `{shift} < {space} > {clear}`,
    ],
    keyboardDisplay: {
      '{bksp}': ' ',
      '{clear}': 'Clear',
      '{shift}': 'CAPS ',
    },

    keyboardBtntheme: [
      {
        class: 'hg-bg-color',
        buttons:
          "1 2 3 4 5 6 7 8 9 0 .net  @hotmail.com @yahoo.com @gmail.com @aol.com '{shift}'",
      },
      {
        class: 'hg-height',
        buttons:
          '{bksp} .net  @hotmail.com @yahoo.com @gmail.com @aol.com @ .com < > {clear} {space}',
      },
      {
        class: 'hg-round',
        buttons:
          '1 2 3 4 5 6 7 8 9 0 {bksp} q w e r t y u i o p a s d f g h j k l - _ z x c v b n m . ',
      },
      {
        class: 'hg-style',
        buttons:
          '1 2 3 4 5 6 7 8 9 0 q w e r t y u i o p - + a s d f g h j k l _ =  ^ z x c v b n m , .  .com < > {clear} {space}',
      },
      {
        class: 'hg-sm-text',
        buttons: '.net  @hotmail.com @yahoo.com @gmail.com @aol.com',
      },
      {
        class: 'hg-md-text',
        buttons: '.com @ {clear}',
      },
      {
        class: 'hg-width-arrow',
        buttons: '< >',
      },
      {
        class: 'hg-width-net',
        buttons: '.net',
      },
      {
        class: 'hg-width-hotmail',
        buttons: '@hotmail.com',
      },
      {
        class: 'hg-width-mails',
        buttons: '@yahoo.com @gmail.com @aol.com',
      },
      {
        class: 'hg-width-at',
        buttons: '@',
      },
      {
        class: 'hg-width-com',
        buttons: '.com',
      },
    ],
  };

  enrollmentFormObs$: Observable<any>;
  enrollmentFormValues: any;

  inputFieldObs$: Observable<any>;
  inputField: string = '';

  keyboardConfigObs$: Observable<any>;

  private pageStateObs$: Observable<any>;
  private pageState: CurrentPage;

  previousKeyboardConfig: string = '';
  keyboardConfig: string = 'default';

  previousInputField: string = 'keyboardDefault';
  currentInputField: string;
  resetInput: boolean = false;
  keyContainer: string[] = [];

  actions = _actions;

  resetState = {
    enrollmentUser: {
      address: '',
      apartment: '',
      city: '',
      stateCode: '',
      zip: '',
    },
  };

  resetPage = {
    enrollmentUser: {
      address: '',
      apartment: '',
      city: '',
      stateCode: '',
      zip: '',
    },
  };

  resetPage2 = {
    enrollmentUser: {
      email: '',
      phone: '',
    },
  };

  constructor(private store: Store) {}

  checkForInputFieldSwitch(theInput: string) {
    if (this.previousInputField !== this.currentInputField) {
      this.previousInputField = this.currentInputField;
      this.currentInputField = theInput;

      setTimeout(() => {
        this.value = '';
      }, 1000);
      this.keyContainer = [];
    }
  }

  checkForKeyboardSwitch(theInput: string) {
    if (this.previousKeyboardConfig !== theInput) {
      this.previousKeyboardConfig = this.keyboardConfig;
      this.keyboardConfig = theInput;
      setTimeout(() => {
        this.keyboard.setOptions({
          layoutName: theInput,
        });
      }, 1);
    }
  }

  ngOnInit(): void {
    this.inputFieldObs$ = this.store.pipe(select(inputFieldSelector));
    this.enrollmentFormObs$ = this.store.pipe(select(enrollmentSelector2));
    this.keyboardConfigObs$ = this.store.pipe(select(currentKeyboardSelector));
    this.pageStateObs$ = this.store.pipe(select(currentPageSelector));
  }

  ngOnDestroy() {
    this.keyboard = null;
  }

  ngAfterViewInit() {
    /* grab values from the ngrx store */
    this.inputFieldObs$.subscribe((val) => {
      this.inputField = val;
      this.checkForInputFieldSwitch(val);
    });

    this.enrollmentFormObs$.subscribe((val) => {
      this.enrollmentFormValues = val;
    });

    this.keyboardConfigObs$.subscribe((val) => {
      this.keyboardConfig = val;
      this.checkForKeyboardSwitch(val);
    });

    this.pageStateObs$.subscribe((val) => {
      this.pageState = val;
    });

    /* end values from the ngrx store */

    let options = {
      onChange: (input) => this.onChange(input),
      onKeyPress: (button) => this.onKeyPress(button),
      tabCharOnTab: true,
      disableButtonHold: true,
      inputPattern: this.keyboardFormat.inputpattern
        ? this.keyboardFormat.inputpattern
        : '',
      maxLength: this.keyboardFormat.maxLength
        ? this.keyboardFormat.maxLength
        : '',
      modules: [],
      inputMask: this.keyboardFormat.inputMask ? '999-999-9999' : '',
      layout: {
        default: this.keyboardFormat[this.keyboardConfig],
        shift: this.keyboardFormat.shift
          ? this.keyboardFormat.shift
          : this.keyboardFormat.keyboardDefaultCAPS,
        withEmail: this.keyboardFormat.withEmail,
      },
      display: this.keyboardFormat.keyboardDisplay
        ? this.keyboardFormat.keyboardDisplay
        : {
            '{bksp}': ' ',
            '{clear}': 'Clear',
            '{shift}': ' ',
          },

      buttonTheme: this.keyboardFormat.keyboardBtntheme
        ? this.keyboardFormat.keyboardBtntheme
        : [
            {
              class: 'hg-red',
              buttons:
                '1 2 3 4 5 6 7 8 9 0  \\ enter .com .net  @hotmail.com @yahoo.com @gmail.com @aol.com',
            },
            {
              class: 'hg-style',
              buttons:
                '1 2 3 4 5 6 7 8 9 0 @ q w e r t y u i o p a s d f g h j k l - _ l ^ z x c v b n m , . @',
            },
            {
              class: 'hg-style',
              buttons:
                "1 2 3 4 5 6 7 8 9 0 @ Q W E R T Y U I O P A S D F G H J K L - _ l  Z X C V B N M , . '{shift}'",
            },
            {
              class: 'hg-width-arrow',
              buttons: '< >',
            },
            {
              class: 'hg-width-net',
              buttons: '.net',
            },
            {
              class: 'hg-width-hotmail',
              buttons: '@hotmail.com',
            },
            {
              class: 'hg-width-mails',
              buttons: "@yahoo.com @gmail.com @aol.com '{clear}'",
            },
            {
              class: 'hg-width-at2nd',
              buttons: '@',
            },
            {
              class: 'hg-width-com',
              buttons: '.com',
            },
            {
              class: `hg-up-arrow`,
              buttons: `shift`,
            },
          ],
      theme: `simple-keyboard hg-theme-default hg-layout-default enroll-keyboard-instance`,

      // To keep inputs syncronized
      syncInstanceInputs: true,
    };

    this.keyboard = new Keyboard('.enroll-keyboard-instance', {
      ...options,
    });
  }

  onChange = (input: string) => {
    this.value = input;
  };

  onKeyPress = (button: string) => {
    const nonKeyNumbers = ['{shift}', '{bksp}', '{clear}', '<', '>'];
    if(button === '{space}'){
      this.keyContainer.push(' ');
    }
    else if (button === '{bksp}') {
      this.keyContainer.pop();
    } else if (!nonKeyNumbers.includes(button)) {
      this.keyContainer.push(button);
    } else if (button == '{clear}') {
      this.keyContainer = [];
      this.value = '';
    }
    let newSliceOfState = {
      enrollmentUser: {
        playerId: '',
        name: '',
        address: this.enrollmentFormValues.address || '',
        apartment: this.enrollmentFormValues.apartment || '',
        city: this.enrollmentFormValues.city || '',
        stateCode: this.enrollmentFormValues.stateCode || '',
        zip: this.enrollmentFormValues.zip || '',
        phone: this.enrollmentFormValues.phone || '',
        email: this.enrollmentFormValues.email || '',
      },
    };

    newSliceOfState['enrollmentUser'][`${this.inputField}`] =
      this.keyContainer.join('');

    if (button === '{clear}') {
      const pageGroups = {
        update: ['address', 'apartment', 'city', 'statecode', 'zip'],
        updatePhoneAndEmail: ['email', 'phone'],
      };

      if (this.pageState == CurrentPage.update) {
        for (let key in newSliceOfState['enrollmentUser']) {
          if (pageGroups.update.includes(key)) {
            newSliceOfState['enrollmentUser'][key] = '';
          }
        }
      } else if (this.pageState == CurrentPage.updateEmail) {
        for (let key in newSliceOfState['enrollmentUser']) {
          if (pageGroups.updatePhoneAndEmail.includes(key)) {
            newSliceOfState['enrollmentUser'][key] = '';
          }
        }
      }
    }

    this.store.dispatch(
      updateEnrollmentAction({ enrollmentState: newSliceOfState })
    );

    this.value = '';

    if (button === '{shift}' || button === '{lock}') this.handleShift();
  };

  onInputChange = (event: any) => {
    this.keyboard.setInput(event.target.value);
  };

  handleShift = () => {
    let currentLayout = this.keyboard.options.layoutName;
    let shiftToggle = currentLayout === 'default' ? 'shift' : 'default';

    this.keyboard.setOptions({
      layoutName: shiftToggle,
    });
  };
}
`

`

<div *ngIf="!fontsLoaded" class="font-loading">
  <img [src]="loadingDots" alt="" />
</div>

<form [formGroup]="enrollmentForm" *ngIf="fontsLoaded">
  <div class="bodyMain">
    <div class="pin-overlay" *ngIf="shouldShowModal"></div>
    <div class="pinErrorContainer" *ngIf="shouldShowModal">
      <div class="pinError">
        <div class="close-button" (click)="closeModal()">
          <img [src]="iconCloseButton" />
        </div>
        <app-dynamic-svg [type]="svgType"></app-dynamic-svg>

        <div class="modal-header">{{ modalHeader }}</div>
        <div>{{ modalMessage1 }}</div>
        <div>{{ modalMessage2 }}</div>
      </div>
    </div>

    <header>
      <div class="enroll-progress-bar">
        <div
          class="progress-box"
          [ngClass]="{ inactive: screenTwo, active: !screenTwo }"
        >
          <div class="progress-section">
            <div class="progress-verbiage">
              <img
                *ngIf="screenTwo"
                class="progress-checkmark"
                [src]="iconWhiteCircleCheckmark"
                alt="icon-white-circle-checkmark"
              />
              <span *ngIf="!screenTwo">1.</span>
              Verify Information
            </div>
          </div>
          <div class="arrow-section"></div>
        </div>
        <div
          class="progress-box"
          [ngClass]="{ inactive: !screenTwo, active: screenTwo }"
        >
          <div class="progress-section">
            <div class="progress-verbiage">2. Stay Connected</div>
          </div>
          <div class="arrow-section"></div>
        </div>
        <div class="progress-box">
          <div class="progress-section inactive">
            <div class="progress-verbiage">3. Create pin</div>
          </div>
        </div>
      </div>

      <div class="center-aligned-logo-container">
        <img id="logo" [src]="logo" alt="" />
      </div>
    </header>
    <main class="content-container">
      <div class="header-and-cog-wheel-container">
        <div class="cmsheading1 left-aligned" #pageTitleField>
          {{ pageTitle }}
        </div>
      </div>
      <div class="details update body-text-weight">
        
        <div *ngIf="screenOne" class="address-fields">
          <div class="address-row-one">
            <div class="street-address">
              <span for="street-address">{{ label1 }}</span>
              <input
                value="street-address"
                type="text"
                formControlName="address"
                (focus)="onInputFocus('ADDRESS')"
              />
            </div>
            <div class="apt-number">
              <span>{{ label2 }}</span>
              <input
                type="text"
                formControlName="apartment"
                (focus)="onInputFocus('APARTMENT')"
              />
            </div>
          </div>
          <div class="address-row-two">
            <div class="city">
              <span>{{ label3 }}</span>
              <input
                value="city"
                formControlName="city"
                (focus)="onInputFocus('CITY')"
              />
            </div>
            <div class="state">
              <span>{{ label4 }}</span>
              <select formControlName="stateCode" class="state-codes">
                <option *ngFor="let stateCode of stateCodes | keyvalue">
                  {{ stateCode.value }}
                </option>
              </select>
            </div>
            <div class="zip">
              <span>{{ label5 }}</span>
              <input formControlName="zip" (focus)="onInputFocus('ZIP')" />
            </div>
          </div>
        </div>
        

        
        <div *ngIf="screenTwo" class="address-fields">
          <div class="address-row-one phone-email">
            <div class="phone-container">
              <img [src]="phoneIcon" alt="phone" />
              <input
                [ngClass]="{ error: invalidPhone }"
                value="phone"
                type="text"
                formControlName="phone"
                (focus)="onInputFocus('PHONE')"
                #phoneInput
              />
            </div>

            <div class="email-container">
              <img [src]="emailIcon" alt="email" />
              <input
                [ngClass]="{ error: invalidEmail }"
                class="email"
                type="email"
                formControlName="email"
                (focus)="onInputFocus('EMAIL')"
                [email]="true"
                #emailInput
              />
            </div>
          </div>
          <div class="address-row-two" *ngIf="!emailAndPhoneAreHidden()">
            <div class="opt-in">
              <p *ngIf="enableDisclaimer">
                {{ optinMessage }}
              </p>
              <div class="opt-in-input">
                <input
                  *ngIf="enableEmailOptin"
                  formControlName="mailToAllowed"
                  type="checkbox"
                />
                <label
                  *ngIf="enableEmailOptin"
                  [ngStyle]="{ width: computeEmailLabelWidth() }"
                >
                  {{ emailLabel }}
                </label>
                <input
                  *ngIf="enableSMSOptin"
                  formControlName="messageToAllowed"
                  type="checkbox"
                />
                <label class="text-message-label" *ngIf="enableSMSOptin">
                  {{ phoneLabel }}*</label
                >
              </div>
            </div>
          </div>
        </div>
        

        <div class="keyboard">
          <app-keyboard></app-keyboard>
        </div>
      </div>
    </main>
    

    <div class="enroll-footer">
      <div
        class="start-over-container footer-button-container"
        [ngClass]="{ 'screen-two': screenTwo }"
      >
        <button
          class="start-over-button footer-button secondary-button"
          (click)="startOver()"
        >
          Start Over
        </button>
        <button
          class="start-over-button footer-button secondary-button"
          (click)="startOver()"
          *ngIf="screenTwo"
          [ngClass]="{ hidden: allowSkip() }"
        >
          skip >>
        </button>
      </div>

      <div
        class="next-button-container footer-button-container"
        [ngClass]="{ 'solo-button': screenOne }"
      >
        <button
          class="next-button footer-button primary-button"
          (click)="back()"
          *ngIf="screenTwo"
        >
          <img [src]="iconBackArrowWhite" alt="icon-arrow-back" />
          <div class="next-btn-label">Back</div>
        </button>
        <button
          class="next-button footer-button primary-button"
          (click)="next()"
        >
          <div class="next-btn-label">Next</div>
          <img [src]="iconArrowForward" alt="icon-arrow-forward" />
        </button>
      </div>
    </div>
    
  </div>
</form>
`

I am using 
angular version : 14.0.0,
node version :  18.16.0
simple keyboard : 3.4.141

**Comment by hodgef** [comment]
@vamsideepak Please provide a repro instead of pasting code

> **Provide a repro**
Providing a [sandbox example](https://codesandbox.io/s/vanilla) is important, as this will help us reproduce the issue. You can also provide a sample git repository. Without a full repro of your issue, we will not be able to debug and the ticket will be closed early.

https://github.com/hodgef/simple-keyboard/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by hodgef** [comment]
If you check out [this sandbox](https://codesandbox.io/s/fancy-dawn-gw652h), you'll see that clicking `{space}` does input a space character. If you are not getting this behavior, then it should have something to do with your implementation.

To debug these kinds of issues I would need a repro, then I will be able to use DevTools to look into your issue.
