### ISSUE TITLE
use layoutCandidatesPageSize style is no change

### ISSUE THREAD

**Issue by MightyTiger98** [hodgef/simple-keyboard#2102]
**Simple-keyboard version**
Some bugs are addressed in newer versions, therefore please ensure you are running the latest.
v3.7.10
**Describe the bug**
A short and clear description of what the bug is.
i use chinese layout and change layoutCandidatesPageSize but hg-candidate-box(style) max-width is not change
**Provide a repro**
Providing a [sandbox example](https://codesandbox.io/s/vanilla) is important, as this will help us reproduce the issue. You can also provide a sample git repository. Without a full repro of your issue, we will not be able to debug and the ticket will be closed early.

**Screenshots**
when layoutCandidatesPageSize = 5
![1695019904367](https://github.com/hodgef/simple-keyboard/assets/49520296/a5d754ed-36db-4bf3-8452-e0571ae33310)

when layoutCandidatesPageSize = 20
![1695019966713](https://github.com/hodgef/simple-keyboard/assets/49520296/023e239a-144f-4740-b0f8-6b0429f756c7)

**Comment by MightyTiger98** [comment]
![1695020396031](https://github.com/hodgef/simple-keyboard/assets/49520296/29394992-9377-4c73-9731-6a4204064ecc)
i attempt to modify hg-candidate-box but is not take effect （Vue）

**Comment by MightyTiger98** [comment]
when i set max-width none, it display normol

**Comment by hodgef** [comment]
Hello @MightyTiger98,

It appears to be a styling issue in the library. However, this seems to be low priority as the user can fix it through CSS. 
I will file this as a bug for tracking and address it as part of the next release.

Thanks,
Francisco Hodge
