### ISSUE TITLE
fullKeyboard，not  darkTheme  demo

### ISSUE THREAD

**Issue by aogg** [hodgef/simple-keyboard#2127]
base fullKeyboard demo

add class
```

  
/*
  Theme: myTheme1
*/
.simple-keyboard.myTheme1 {
    background-color: rgba(0, 0, 0, 0.8);
    border-radius: 0;
    border-bottom-right-radius: 5px;
    border-bottom-left-radius: 5px;
  }
  
  .simple-keyboard.myTheme1 .hg-button {
    /* height: 50px; */
    display: flex;
    justify-content: center;
    align-items: center;
    background: rgba(0, 0, 0, 0.5);
    color: white;
  }
  
  .simple-keyboard.myTheme1 .hg-button:active {
    background: #1c4995;
    color: white;
  }
  
  #root .simple-keyboard.myTheme1 + .simple-keyboard-preview {
    background: #1c4995;
  }

```

How to fully cover
![image](https://github.com/hodgef/simple-keyboard/assets/8998031/ae94d1bf-d0d1-4442-8fd9-0252b1cf6d83)

**Comment by hodgef** [comment]
Hey @aogg, I appreciate that you shared this - but the fullKeyboard demo does not have a dark mode example. I will file this as not a bug but people will still be able to find your example through search and hopefully benefit.

Thanks,
Francisco Hodge
