### ISSUE TITLE
Prevent showing system keyboard on tablets

### ISSUE THREAD

**Issue by despecial** [hodgef/simple-keyboard#2141]
Not sure if this is already possible or can be achieved.

If we use the simple keyboard on a (Surface) tablet, the virtual system keyboard shows up.
Since the js keyboard is customized, we do not need and want to show the windows keyboard.

We tried the inputmode='none' trick but the keyboard still shows up.

How can we force to hide it?

**Comment by hodgef** [comment]
Hello @despecial,

I would normally suggest inputmode, but if that doesn't work the alternative would be to make your input readonly.

Regards,
Francisco Hodge

**Comment by despecial** [comment]
Hi Francisco, unfortunately, inputmode does not work as descriped.
Readonly is no option, since the page can be accessed by other devices too, so physical keyboard would not work.

So there is really no option to hide the virtual system keyboard on mobile devices?
I assumed with pointer events there could be a trick :)

**Comment by hodgef** [comment]
Hello @despecial, besides the options discussed I don't know any other way unfortunately. I'd suggest posting on StackOverflow since this is a general question regarding inputs (and not an issue with the library). I think you'd get more potential solutions there.

Regards,
Francisco Hodge

**Comment by jonasdev** [comment]
@despecial did you find a solution for this? 🤞
