### ISSUE TITLE
Japanese Flick Input (Mobile)

### ISSUE THREAD

**Issue by IstoraMandiri** [hodgef/simple-keyboard#2171]
**Describe the solution you'd like**

Implement a commonly used Japanese mobile device input, the 12-key flick input.

I'm open to contributing this feature, if there's possibility it will be merged.

**Describe alternatives you've considered**

The full size keyboard works well for large devices like tablets but I can't find an example of this common input type that works well for small screens.

**Additional context**

![image](https://github.com/hodgef/simple-keyboard/assets/1696942/42b31e4b-cc75-457c-96e1-08f630c3053a)

**Comment by hodgef** [comment]
Hello @IstoraMandiri,

I would definitely be eager to merge such a feature. Do you think it can be done through an option without affecting too much the base functionality? I am mostly wary of regressions and huge refactors, but besides that I strongly encourage improvements.

Our support for [Japanese](https://hodgef.com/simple-keyboard/demos/?d=japanese) input [is not the best at the moment](https://github.com/simple-keyboard/simple-keyboard-layouts/issues/919#issuecomment-1115989277) and I would appreciate and credit any contributions that would improve this.

Thanks,
Francisco Hodge
