### ISSUE TITLE
excludeFromLayout doesnt work 

### ISSUE THREAD

**Issue by sharon-alexander** [hodgef/simple-keyboard#2174]
excludeFromLayout doesnt seem to work. 

**Usage in vue**
```
onMounted(() => {
  keyboard.value = new Keyboard({
    onChange,
    onKeyPress,
    excludeFromLayout: {
      default: [".com", "@", "=", "[", "]"],
      shift: [".com", "@", "=", "[", "]"],
    },
```

**Comment by hodgef** [comment]
Seems to work for me:

<img width="1078" alt="image" src="https://github.com/hodgef/simple-keyboard/assets/25509135/95fbbdf0-b8e6-4ff9-bc2b-13e173310308">

https://codesandbox.io/p/sandbox/flamboyant-mayer-yjw3hx?file=%2Fsrc%2FSimpleKeyboard.vue%3A30%2C9

Regards,
Francisco Hodge

**Comment by sharon-alexander** [comment]
Had to update to the 3.7.39 version. Thanks!
