### ISSUE TITLE
can i use in vue3?

### ISSUE THREAD

**Issue by changlinwu0122** [hodgef/simple-keyboard#2179]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hodgef** [comment]
Check out this comment, it works on Vue 3 per my tests:
https://github.com/hodgef/simple-keyboard/issues/2057#issuecomment-1652876443

Thanks,
Francisco Hodge
