### ISSUE TITLE
Keyboard button not showing with tailwind

### ISSUE THREAD

**Issue by dimaslanjaka** [hodgef/simple-keyboard#2206]
**Simple-keyboard version**
```json
{
    "react-simple-keyboard": "^3.7.78",
    "simple-keyboard": "^3.7.53"
}
```

**Describe the bug**
The button text not showing (conflict with tailwind class names).

but when I force the style of button, works like below screenshoot:

![image](https://github.com/hodgef/simple-keyboard/assets/12471057/14d73100-78bb-4dad-8b6e-92f8ae2dc427)

**Provide a repro**
https://github.com/dimaslanjaka/webpack-boilerplate/commit/2fe74b1185792b0fc8bbfa1c3eab7512bfde784a

**Screenshots**
![image](https://github.com/hodgef/simple-keyboard/assets/12471057/a7b31205-f334-4e61-ad34-cc8e92e64886)
![image](https://github.com/hodgef/simple-keyboard/assets/12471057/8266ef0a-284e-4331-a9a8-0ac583b282a4)

**Comment by dimaslanjaka** [comment]
for now i force the styling with

```scss
.hg-button,
.hg-functionBtn * {
  opacity: 1;
  color: black;
  display: inline-block;
}
```

![image](https://github.com/hodgef/simple-keyboard/assets/12471057/7e58b66c-b3e5-4bbe-bb1a-a506f36b32bf)

please fix

**Comment by hodgef** [comment]
If you have styling that is changing the simple-keyboard text color to white, that is not a bug in this library. 

Please only file reports for bugs in the library, otherwise I would be forced to close the tickets early.

Thanks!
Francisco Hodge
