### ISSUE TITLE
return key?

### ISSUE THREAD

**Issue by omarcostahamido** [hodgef/simple-keyboard#221]
**Is your feature request related to a problem? Please describe.**

I can't use return key - newline

**Describe the solution you'd like**

I would like to actually have a return key

**Describe alternatives you've considered**

**Additional context**

I'm using your numeric keyboard example: https://franciscohodge.com/projects/simple-keyboard/demos/numeric-layout-demo-js/
and I was able to add several keys. but not the return key. {enter} seemed like a good candidate but it does not create a newline. how can I add the return key?

**Comment by hodgef** [comment]
Hello @omarcostahamido,

To input a newline when you hit `{enter}`, you can use the `newLineOnEnter` option:

```
newLineOnEnter: true
```
https://simple-keyboard.com/documentation/#newLineOnEnter

Regards,
Francisco Hodge

**Comment by omarcostahamido** [comment]
terrific. thanks a lot.
