### ISSUE TITLE
CSS partialy Apply

### ISSUE THREAD

**Issue by Mahora974** [hodgef/simple-keyboard#2210]
**Simple-keyboard version**
3.7.54, on Angular 16.2

**Describe the bug**
I just installed the latest version of simple keyboard, and it seems like the css doesn't apply all the way. 

By trying to modify the code, I noticed that a few classes are applied, but the majority doesn't.

For exemple, the background color does apply, but if I try to add a border to .hg-theme-default .hg-button span il will not show up.

**Screenshots**
![image](https://github.com/hodgef/simple-keyboard/assets/115140201/f762de7c-174d-4fa7-9ce7-b2f25a007229)
![image](https://github.com/hodgef/simple-keyboard/assets/115140201/6c8768d8-ffd6-44aa-824e-03f85b0ebdf2)

**Provide a repro**
I'm afraid I can't provide a repository, as I use component that are own by my company and I'm not sure I can share it.
However, here is a list of modules that I use : 

- BrowserAnimationsModule,
- MatDatepickerModule,
- HttpClientModule,
- CommonModule,
- ReactiveFormsModule,
- FormsModule,
- NgxMaterialTimepickerModule.setOpts('fr-FR', 'arab'),
- HttpClientXsrfModule.withOptions({ headerName: 'X-CSRF-TOKEN' }),
- MatFormFieldModule,
- IconPickerModule,
- MatNativeDateModule,
- MatTableModule,
- NgxMatDatetimePickerModule,
- NgxMatNativeDateModule,
- MatRadioModule,

**Comment by hodgef** [comment]
Hello @Mahora974 ,

Please make sure you are disabling `ViewEncapsulation` as shown in the Angular demos.

![image](https://github.com/hodgef/simple-keyboard/assets/25509135/c91b0ff0-aa52-4658-9b6f-9ec37ba04540)


More info & alternate solution: https://github.com/hodgef/simple-keyboard/issues/580#issuecomment-641404568

Thanks,
Francisco Hodge
