### ISSUE TITLE
`layoutCandidates` is not case sensitive

### ISSUE THREAD

**Issue by Zerak630** [hodgef/simple-keyboard#2235]
**Simple-keyboard version**
I am using `react-simple-keyboard` v.3.7.94, but I think this bug is related to `simple-keyboard`.

**Describe the bug**
Giving accents variants to lowercase and uppercase letters, but only lowercase ones are used.
```javascript
layoutCandidates = {{
    a: "à â ä ã",
    //[More lowercase...]
    A: "À Â Ä Ã",
    //[More uppercase...]
}}
```

**Provide a repro**
[Sandbox repro](https://codesandbox.io/p/sandbox/brave-knuth-xs5jd3?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltr2buhh0006356hix916lzv%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltr2buhg0002356h6mo9mvh2%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltr2buhg0003356h53rjj576%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltr2buhg0005356hz7s4fuma%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltr2buhg0002356h6mo9mvh2%2522%253A%257B%2522id%2522%253A%2522cltr2buhg0002356h6mo9mvh2%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltr2chn1004u356hor8w5sqa%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A14%252C%2522startColumn%2522%253A22%252C%2522endLineNumber%2522%253A14%252C%2522endColumn%2522%253A22%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltr2chn1004u356hor8w5sqa%2522%257D%252C%2522cltr2buhg0005356hz7s4fuma%2522%253A%257B%2522id%2522%253A%2522cltr2buhg0005356hz7s4fuma%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltr2buhg0004356hzul4vodc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltr2buhg0004356hzul4vodc%2522%257D%252C%2522cltr2buhg0003356h53rjj576%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltr2buhg0003356h53rjj576%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Screenshots**
I clicked on A letter, but the keyboard propose me only lowercase variants
![image](https://github.com/hodgef/simple-keyboard/assets/48765511/226674d8-4553-4fdd-8f6f-2461e776a9b6)

**Comment by hodgef** [comment]
Hello @Zerak630 

Check out this option: https://github.com/hodgef/simple-keyboard/issues/1993#issuecomment-1574154889

Regards,
Francisco Hodge
