### ISSUE TITLE
When simple-keyboard is used with accessibility voice over turned on, hitting q enters 1 in input

### ISSUE THREAD

**Issue by ashivas** [hodgef/simple-keyboard#2237]
This is how my layout looks  

defaultLayout = {
    'default': [
      '` 1 2 3 4 5 6 7 8 9 0 - = {bksp}',
      '{tab} q w e r t y u i o p [ ] \\',
      '{lock} a s d f g h j k l ; \' {enter}',
      '{shift} z x c v b n m , . / {shift}',
      '.com @ {space}'
    ],
    'shift': [
      '~ ! @ # $ % ^ &amp; * ( ) _ + {bksp}',
      '{tab} Q W E R T Y U I O P { } |',
      '{lock} A S D F G H J K L : " {enter}',
      '{shift} Z X C V B N M &lt; &gt; ? {shift}',
      '.com @ {space}'
    ]
  }

 this.keyboard = new Keyboard({
         onChange: (input) => this.onChange(input),
         onKeyPress: (button) => this.onKeyPress(button),
         theme: "hg-theme-default hg-layout-default myTheme",
         useButtonTag: false,
         onModulesLoaded: () => {
         },
         preventMouseDownDefault: true,
       });

The issue is When simple-keyboard is used with accessibility voice over turned on, hitting q enters 1 in input.
Same behavior is observed for w enters 2, e enters 3

**Comment by hodgef** [comment]
Hello @ashivas, I don't think this is caused by simple-keyboard. You will need to do further debugging to find out the root cause.

If you debug your app and believe the library has an issue, please provide a repro so I can verify it.

Thanks!
Francisco Hodge
