### ISSUE TITLE
Not displaying keyboard outside app.component

### ISSUE THREAD

**Issue by MPapini91** [hodgef/simple-keyboard#2279]
**Simple-keyboard version**
3.7.80

**Describe the bug**
I am trying to insert simple-keyboard into an Angular application (v. 16.0.4) but the keyboard only works correctly when inserted at the app.component level.
In the last attempt I created a dedicated component using the code from the demo. If I insert that component into the app component it works correctly, if I try instead to insert it into any other component I get the error KEYBOARD_DOM_ERROR and only the input field is displayed.

**Provide a repro**
Unfortunately, I cannot share the application code outside the company

**Comment by hodgef** [comment]
Without a repro, it won't be possible to debug this, but I would suggest taking a look at this similar ticket:
https://github.com/hodgef/simple-keyboard/issues/57#issuecomment-471618877

Thanks,
Francisco Hodge
