### ISSUE TITLE
Virtual Keyboard, keys are coming all white

### ISSUE THREAD

**Issue by Sbasu2512** [hodgef/simple-keyboard#2286]
**Simple-keyboard version**
Some bugs are addressed in newer versions, therefore please ensure you are running the latest.
Currently running: "react-simple-keyboard": "^3.7.122",
**Describe the bug**
A short and clear description of what the bug is.
Virtual keyboard is coming fine somewhere, somewhere the keys are not coming correctly. Also I have noticed that if I pass class via theme prop then it losses all the CSS.
**Provide a repro**
Providing a [sandbox example](https://codesandbox.io/s/vanilla) is important, as this will help us reproduce the issue. You can also provide a sample git repository. Without a full repro of your issue, we will not be able to debug and the ticket will be closed early.
Unfortunately, I am unable to provide a repo or code sandbox as the code are private.
**Screenshots**
![Vk](https://github.com/hodgef/simple-keyboard/assets/81332793/7c306687-4043-4577-bffe-2cacc19800d3)
![Vk2](https://github.com/hodgef/simple-keyboard/assets/81332793/b7fb0e63-901f-4ec4-8aee-b2688fc9bdc9)

``
 return (
      <div>
        <Keyboard
          keyboardRef={(r) => (keyboard.current = r)}
          layoutName={keyboardLayout}
          onKeyPress={onKeyPress}
          layout={layoutDesigns}
          physicalKeyboardHighlight={true}
          display={{
            '{bksp}': renderToString(<BsBackspace />),
            '{shift}': renderToString(<BsShift />),
            '{tab}': 'Tab',
            '{lock}': 'Caps',
            '{space}': 'Space',
            '{enter}': renderToString(<BsArrowReturnLeft />),
            '{alt}': 'alt',
          }}
        />
      </div>
  );
  ``

If I pass a class via the theme, then it removes all the other css
![Screenshot 2024-05-28 104947](https://github.com/hodgef/simple-keyboard/assets/81332793/361bdb40-2e9a-4f36-a190-17e597817436)
`<div>
        <Keyboard
          keyboardRef={(ref) => (keyboard.current = ref)}
          layoutName={keyboardLayout}
          theme='background_blue'
          onKeyPress={onKeyPress}
          layout={layoutDesigns}
          physicalKeyboardHighlight={true}
          display={{
            '{bksp}': renderToString(<BsBackspace />),
            '{shift}': renderToString(<BsShift />),
            '{tab}': 'Tab',
            '{lock}': 'Caps',
            '{space}': 'Space',
            '{enter}': renderToString(<BsArrowReturnLeft />),
            '{alt}': 'alt',
          }}
        />
      </div>

css:
.background_blue {
  background-color: rgb(31, 34, 51) !important;
}

`

I want to know why in a certain place, the keys are losing their color while at other place it is not. Also upon providing additional css it is losing its original css.

Working on:
 "node": ">=16.6.0",
"npm": ">=8.11.0",
  "react-simple-keyboard": "^3.7.122",
"next": "12.3.0",

**Comment by hodgef** [comment]
Hello @Sbasu2512,

The white keys is due to `color: white` CSS somewhere in your application. You can confirm with DevTools inspector on your browser.

To keep the default styles when using the `theme` option, please refer to this doc entry:
https://hodgef.com/simple-keyboard/questions-answers/give-different-base-class-keyboard/

<img width="609" alt="image" src="https://github.com/hodgef/simple-keyboard/assets/25509135/cd9bec30-0a8a-41a7-afc3-ca8d3a5e97f3">
