### ISSUE TITLE
Can this component be dragged by the mouse motor?

### ISSUE THREAD

**Issue by susu-sama** [hodgef/simple-keyboard#2297]
Can this component be used for mouse, motor, keyboard, other areas, drag and drop? In F12 mobile device simulation, the keyboard can be dragged. How to achieve drag and drop in the browser interface

**Comment by hodgef** [comment]
Hello @susu-sama,

This is a functionality that is not available out of the box, but there are libraries out there that can provide this. 

You can also add it from scratch using plain JS. Here's an example for a draggable keyboard, you can modify it to fit your needs:
https://stackblitz.com/edit/hodgef-vue-simple-keyboard-wzahwa?file=src%2Fdraggable.js,src%2FSimpleKeyboard.vue,src%2FApp.css,src%2FApp.vue,src%2Fmain.js

Regards,
Francisco Hodge

**Comment by susu-sama** [comment]
Thank you. After completing the task at hand, I will study it based on the examples you provided. If there are any questions, I will raise them. Thank you very much to the author
