### ISSUE TITLE
Multiple Inputs in Vue environment

### ISSUE THREAD

**Issue by madhurikulkarni** [hodgef/simple-keyboard#232]
I was checking the documentation and saw that `inputName` can be used for multiple input. Could you please share a demo or some pointers, in regard with Vue.

**Comment by hodgef** [comment]
Hello @madhurikulkarni,

Here's an example I just set up:

https://codesandbox.io/s/github/simple-keyboard/vue-simple-keyboard-multiple-inputs/tree/master/?fontsize=14&module=%2Fsrc%2FApp.vue

I hope it helps as a base for your implementation.

Let me know if you come across any issues.

Regards,
Francisco Hodge

**Comment by madhurikulkarni** [comment]
Thank you for the demo .

**Comment by madhurikulkarni** [comment]
Follow up to this question, I am trying to create form elements like so without the `Input.vue` component.
```
<label>Firstname</label>
          <input
            id="firstname"
            :value="inputValue"
            inputName="firstname"
            @focus="onInputFocus"
            @input="onInputChange"
          />
```
But every field ends up having the same value. Is it the wrong usage of `inputName`. ?

**Comment by hodgef** [comment]
Hello @madhurikulkarni,

Here's an example without the input loop nor the Input component:
https://codesandbox.io/s/github/simple-keyboard/vue-simple-keyboard-multiple-inputs-example2/tree/master/?fontsize=14&module=%2Fsrc%2FApp.vue

Hope it helps!

Regards,
Francisco Hodge

**Comment by swthate** [comment]
Is there any reason why adapting this approach to a CDN-powered Vue instance would not work?

Everything works fine while you tap and enter text to the first input, but when you tap and move focus to the next input and try to type, focus shifts to the first input, and if you type again you see the new characters prepended to the previous value of the first input.

The code looks pretty spot-on to me, I cannot figure out why it would not work.

I tried recreating this in a basic html project, and then in a Vue-cli project with SFCs like your examples and those worked flawlessly.

sandbox: https://codesandbox.io/s/frosty-browser-v8nrw?file=/index.html

**Comment by hodgef** [comment]
Hello @swthate,

I recommend carefully following this example:
https://codesandbox.io/s/github/simple-keyboard/vue-simple-keyboard-multiple-inputs?file=/src/App.vue

To keep focus in the input, you can use [preventMouseDownDefault](https://hodgef.com/simple-keyboard/documentation/options/preventmousedowndefault/) (check out the JS demo in that doc). So you shouldn't need to call `focus` directly or anything like that.

Also, when debugging check out the console to see if the proper `inputName` is being set.

If you can't get it to work, please feel free to open a new issue. Thanks!
Francisco Hodge
