### ISSUE TITLE
buttons doubled when vue component used twice

### ISSUE THREAD

**Issue by dreamgear** [hodgef/simple-keyboard#2336]
simple-keyboard@3.7.102

Perhaps not a bug in the keyboard module itself, but in the .vue file provided in the demos

I have a vue component that uses the a simple-keyboard vue component within it.

I created a second vue component that also uses the same  simple-keyboard vue component.  When I did this the first component suddenly got twice as many buttons, and the second component got no buttons.
![simple-keyboard_doubled_buttons](https://github.com/user-attachments/assets/5551717b-d5c4-43f1-9d2f-86eb94cf85e8)

Hoping for a way to pass in something that will keep the two instances straight.

** no repro yet **
It will take a week or so to make a repro.  Asking my question here because I don't have another option

**Comment by hodgef** [comment]
Hello @dreamgear, the Vue component was very quickly put together just to show the basic usage, but it definitely needs modification.

I believe the issue you're encountering is that both `new Keyboard` instances are devoid of a class, so the same instance (`default`) is used twice. To fix this, you can pass a different class target in the constructor, like so:

```js
const keyboard = new Keyboard(".my-div-class-name", {
  // other options ...
});
```
Note: the element `.my-div-class-name` must exist in the page.

https://hodgef.com/simple-keyboard/questions-answers/give-different-base-class-keyboard/

**Comment by dreamgear** [comment]
Thanks for the quick response.  I'll give that a try.

**Comment by dreamgear** [comment]
I can confirm, passing in a class name fixed it.  Thanks again.
