### ISSUE TITLE
Keyboard not showing when changing pages whit ionic/angular

### ISSUE THREAD

**Issue by lechuit** [hodgef/simple-keyboard#2338]
**Simple-keyboard version**
"simple-keyboard": "^3.7.105"

**Describe the bug**
When I change pages with "router.navigate['pag2']" keyboard is not showing

**Provide a repro**
https://github.com/lechuit/demo.git

**Screenshots**
![image](https://github.com/user-attachments/assets/3487e10f-d340-486b-8905-fbcc64b5f568)
![image](https://github.com/user-attachments/assets/f98ff7a4-57e2-4010-b433-75dbcf639207)

**Comment by hodgef** [comment]
Take a look at the the following post where an solution is shared, it looks very similar to your issue: https://github.com/hodgef/simple-keyboard/issues/1467#issue-1157159109

Thanks,
Francisco Hodge

**Comment by lechuit** [comment]
Hi @hodgef  can you test it? dont work for me. this is the repo https://github.com/lechuit/demo.git

**Comment by hodgef** [comment]
Sorry for the delay. Ultimately I couldn't get the code to run.

![image](https://github.com/user-attachments/assets/7e1d4703-9c5d-4c5d-8481-f8bade4f01bc)

However I see that in home.page.ts and home2.page.ts you have the same instantiation:

```js
this.keyboard = new Keyboard({
  onChange: input => this.onChange(input),
  onKeyPress: button => this.onKeyPress(button)
});
```

You can try adding a different class to each instance as shown here:
https://hodgef.com/simple-keyboard/questions-answers/give-different-base-class-keyboard/

Regards,
Francisco Hodge

**Comment by lechuit** [comment]
thx for reply @hodgef, i will try that!
