### ISSUE TITLE
simple-keyboard - NG version for kiosk app

### ISSUE THREAD

**Issue by e404r** [hodgef/simple-keyboard#2351]
Hello, I would like to show you a small example using this plugin:
DEMO: [https://stackblitz.com/~/github.com/e404r/ngx-simple-keyboard-kiosk](https://stackblitz.com/~/github.com/e404r/ngx-simple-keyboard-kiosk)

- Lang Change ✅
- Detect input ✅
- Tested survey and formio✅

**Comment by hodgef** [comment]
Hey @e404r, this is awesome. I will soon start a Wiki page to bring people's attention to community creations. I will make sure to put yours in the list. Keep on building great stuff!

**Comment by e404r** [comment]
@hodgef  Thank you very much😇, I'm glad you liked it.   git url [ngx-simple-keyboard-kiosk](https://github.com/e404r/ngx-simple-keyboard-kiosk)

**Comment by hodgef** [comment]
Added Link in Readme with Wiki link to Community creations:
![image](https://github.com/user-attachments/assets/db0fa96f-8785-4c9b-8d01-3debf256d91b)
