### ISSUE TITLE
Toggle Keys On and Off?

### ISSUE THREAD

**Issue by jakesk43** [hodgef/simple-keyboard#2382]
You have to try to add an option or switch in the code to hold or toggle a key on the keyboard like pressing it repeatedly but only by pressing it on and off once. I read that this was solved in the layoutCandidates option but I don't see the option I want, sorry. Please check it out. Thanks.

**Comment by hodgef** [comment]
Hello @jakesk43,

If you want to disable the default button hold behavior, you can pass in the option [`disableButtonHold`](https://hodgef.com/simple-keyboard/documentation/options/disablebuttonhold/). Then, you can certainly add in your own logic to achieve your desired result.

Simple-keyboard was meant to be extensible by the user. Feel free to give it a try and if you come across a specific issue, please share a sandbox link with your issue and I can try to help.

Thanks,
Francisco Hodge
