### ISSUE TITLE
Errors with physicalKeyboardHighlight

### ISSUE THREAD

**Issue by ProggerPete** [hodgef/simple-keyboard#240]
**Simple-keyboard version**
Latest

**Describe the bug**
physicalKeyboardHighlight option doesn't highlight keys while shift is pressed.  
https://franciscohodge.com/projects/simple-keyboard/demos/physical-keyboard-highlight-demo/

The demo generates errors in IE and fails to run.

**Comment by hodgef** [comment]
Hello @ProggerPete,

Could you specify which keys? I can't seem to reproduce this here (I'm holding shift down the whole time):

https://www.loom.com/share/6f9e649cd8974b38b91f2eb182286f2c

The `physicalKeyboardHighlight` feature could be improved however. I've noted this [here](https://github.com/hodgef/simple-keyboard/projects/3#card-26802335) and will see how I can improve this feature sometime this week.

However, that might not address your specific issue. If you're testing simple-keyboard on IE, please note that it's not currently supported. I have declined support for it in the past (#227, #212) but I'll look harder into supporting it this week also.

Regards,
Francisco Hodge

**Comment by ProggerPete** [comment]
Your video demonstrates exactly the problem I'm referring to.  I can see you press A several times because it shows in the input field, but not once does it highlight on the keyboard image.

When I said IE, I actually meant Edge, but possibly that's what you mean too.

**Comment by hodgef** [comment]
Hello @ProggerPete,

"A" doesn't highlight since it doesn't exist on the layout ("a" is, but "a" !== "A").

Or did you mean something else?

Regards,
Francisco Hodge

**Comment by ProggerPete** [comment]
Ok, I get what you're saying.  It breaks my expectations, but whether I'm a valid yard stick for general opinion is up for debate.

**Comment by hodgef** [comment]
@ProggerPete,

If you find `physicalKeyboardHighlight` limiting, you can always go custom. Here's a custom implementation where the input keys are set to lowercase. It might be what you're looking to achieve:

https://codesandbox.io/s/github/simple-keyboard/simple-keyboard-custom-highlight-button-v2/tree/master/

Best,
Francisco Hodge
