### ISSUE TITLE
keyboard module

### ISSUE THREAD

**Issue by bluelemonade** [hodgef/simple-keyboard#2401]
Can the arrow navigation module be configured so that you can scroll through all the keys using the right or left arrow key, not just in one row?

I have the problem that I have to implement keyboard input using a jog shuttle wheel.

And can you integrate a key as a close button to close the keyboard?

**Comment by hodgef** [comment]
Hello @bluelemonade,

The keyNavigation module does not support this out of the box.

You can copy the contents of the [keyNavigation module](https://github.com/simple-keyboard/simple-keyboard-key-navigation/blob/master/src/index.js#L152), modify it and then use your custom module as shown in the "How to create my own module?" part of these docs: https://hodgef.com/simple-keyboard/modules/

Regarding the closing of the keyboard: you can simply put the keyboard in a container, [add a button in the keyboard](https://hodgef.com/simple-keyboard/questions-answers/edit-add-new-buttons-keyboard/) and then program it's functionality on the `onKeyPress`.

If you come across any issues, please share your code attempt in a sandbox.

Thanks,
Francisco Hodge
