### ISSUE TITLE
Issues with typing in the middle of a word using vue wrapper

### ISSUE THREAD

**Issue by ajmcgrail** [hodgef/simple-keyboard#2403]
As can be seen by the example here, it does not correctly handle putting the caret in a middle of a word and trying to type, as the caret will jump to the end. Any idea how to fix it for vue? I'm experiencing this on a personal project as well: https://hodgef.com/simple-keyboard/editor/?d=hodgef/vue-simple-keyboard/tree/master

**Comment by hodgef** [comment]
Hello @ajmcgrail,

To debug this, I set `debug: true` as an option in SimpleKeyboard.vue
![image](https://github.com/user-attachments/assets/f592fdaa-98f4-43d3-9692-07335633925e)

This gives me some extra logging. When I type 4 "e" and and put my caret at position 2, it correctly sets it to three. But then, the `selectionchange` event comes reporting a wrong position: 5

![image](https://github.com/user-attachments/assets/e35b67b9-0dd9-4fc7-85d7-ca718e5a3374)

What is weird here is that `selectionchange` has been already put behind an option here: https://github.com/hodgef/simple-keyboard/issues/2346#issuecomment-2347303708 - so it should not be set by default any more.

When I looked at the build that codesandbox is using (with browser cache off), I see that it's using 3.7, which does not have the fix:

![image](https://github.com/user-attachments/assets/11edf696-13f3-4d74-94a8-3158cbdd2d14)

So I would ask to check if you are indeed using simple keyboard@3.8.17.

Thanks!
Francisco Hodge

**Comment by ajmcgrail** [comment]
Hey there. I did test it with the newest library, but could you perhaps update the example to the newest and see if it works like intended?

**Comment by hodgef** [comment]
Yes I did update it on the demo fork, you can try it out here:

https://codesandbox.io/p/devbox/friendly-cray-xs7lyy?workspaceId=978412a4-0cf1-4bf2-a00f-2188314bde91

![image](https://github.com/user-attachments/assets/e57c2f5f-d481-409b-9e92-9f30908a5a33)

On the demo site however, I cannot update manually - will need to wait for Codesandbox to update the cache on its end.

**Comment by ajmcgrail** [comment]
Can confirm this works, and after redownloading my node folder, it works on my personal project as well. Thanks!
