### ISSUE TITLE
IE fails to render 

### ISSUE THREAD

**Issue by wolverline** [hodgef/simple-keyboard#241]
React-simple-keyboard version 2.0.4

IE 11 fails to render Keyboard object. It tosses:
SCRIPT65535: Argument not optional
index.js (788,1)

It seems this component doesn't support IE. It should have been described somewhere.

Also Backspace key still has issues.

**Comment by hodgef** [comment]
Hello @wolverline,

I currently have browserlist configured to support IE 11:
```
"browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ]
}
```
https://browserl.ist/?q=%3E0.2%25%2C+not+dead%2C+not+op_mini+all

In practice though, there's always something when testing with IE. Be it webpack DevServer not working for dev, polyfills to be added, demos to be changed, etc.

It's just too much of headache to support a browser with ~2% market share (IE 11).

I'll be adding messages to the demos and docs pages regarding lack of support for IE.

Sorry for the confusion!

Francisco Hodge

**Comment by hodgef** [comment]
Hello @wolverline ,

I have updated the READMEs to warn about the lack of support for IE:

https://github.com/hodgef/simple-keyboard/#dart-compatibility
https://github.com/hodgef/react-simple-keyboard#dart-compatibility

I have also added targeted warnings for IE users across relevant docs and demos.

![image](https://user-images.githubusercontent.com/25509135/65616941-dc3cda80-df89-11e9-8f5e-11a1396743a6.png)

![image](https://user-images.githubusercontent.com/25509135/65616978-ec54ba00-df89-11e9-93f0-a87472aa98cb.png)

I hope that this clears any confusion moving forward.

Thanks!

**Comment by hodgef** [comment]
Update: IE is now supported
Here's more info https://github.com/hodgef/simple-keyboard/issues/212#issuecomment-803670666

Regards,
Francisco Hodge
