### ISSUE TITLE
How to modify Chinese language pack for Chinese keyboard

### ISSUE THREAD

**Issue by susu-sama** [hodgef/simple-keyboard#2421]
Hello author, I would like to inquire about how to modify the Chinese language pack and implement the Chinese association function

**Comment by hodgef** [comment]
Hello @susu-sama,

You can create a partial options object containing your desired [layoutCandidates](https://hodgef.com/simple-keyboard/documentation/options/layoutcandidates/). For this, you can inspire yourself from [existing layouts](https://github.com/simple-keyboard/simple-keyboard-layouts/tree/master/src/lib/layouts) such as these ones:

PinYin: https://github.com/simple-keyboard/simple-keyboard-layouts/blob/master/src/lib/layouts/chinese.ts
Korean: https://github.com/simple-keyboard/simple-keyboard-layouts/blob/master/src/lib/layouts/korean.ts

Then, spread this object into your simple-keyboard options:

```js
const myPartialOptions = {
  layout: ...,
  layoutCandidates: ...
};
new SimpleKeyboard({
  ...myPartialOptions,
  // Other options
});
```

You can see this in action in the following Chinese layout sandbox:
https://codesandbox.io/p/sandbox/github/hodgef/simple-keyboard-layouts-demos/tree/chinese/?file=%2Fsrc%2Findex.js%3A13%2C42&from-embed

If you arrive to a good result and want to share it with the community, let me know and we can integrate it to the default layouts.

Thanks,
Francisco Hodge
