### ISSUE TITLE
Chinese keyboard optimization suggestions

### ISSUE THREAD

**Issue by susu-sama** [hodgef/simple-keyboard#2422]
Hello author, can the Chinese keyboard be optimized as follows?
1. It can support pinyin connections, for example: "rizi" appears on the day "womenchufaba". Let's go
2. Chinese can only have one character per pinyin, which is very uncomfortable
3. The Chinese keyboard interface supports touch movement and can be moved within the body browser

**Comment by hodgef** [comment]
Hello @susu-sama,

The [Chinese layout](https://github.com/simple-keyboard/simple-keyboard-layouts/blob/master/src/lib/layouts/chinese.ts) was created based on existing open source examples. I am not a Chinese speaker so any contribution would need to come from someone who understands the language and would like to contribute a new layout to the community.

If you'd like to take on this work, you are more than welcome! I am sure many would benefit from it.

Closing this ticket though as it's not something that I can do.

Thanks,
Francisco Hodge
