### ISSUE TITLE
Magic Mirror Integration

### ISSUE THREAD

**Issue by granthook73** [hodgef/simple-keyboard#2425]
Hi Would it be possible to write an idiots guid to using simple-keyboard with the Magic Mirror Module MMM-Keyboard. There are some instructions stating that simple keyboard is a dependence however this is limited. I feel this would be very useful and very frequently used.

This is the module: https://github.com/lavolp3/MMM-Keyboard

Many thanks

**Comment by hodgef** [comment]
Hello @granthook73,

While I made simple-keyboard/swipe-keyboard, I am not familiar with this integration (Magic Mirror). I would suggest reaching to the author on this: https://github.com/lavolp3

Now I know that I could read up on the project and try to put up some documentation together. But I'm trying to limit the time I spend on project maintenance to actual bugs. Hopefully the community can take up the work on this.

Thanks,
Francisco Hodge
