### ISSUE TITLE
Physical input to virtual keyboard?

### ISSUE THREAD

**Issue by pastuh** [hodgef/simple-keyboard#244]
**Is your feature request related to a problem? Please describe.**
If i press my keyboard, i see highlighted numbers on virtual keyboard, but i can't see updated inputs. 

If i click row off numbers, i can see in console: _Key pressed: 5_
If i click numeric keypad number, i see nothing.

**Describe the solution you'd like**
I need to program every input? Or there exists some code and i missed that..
( I want to fill pressed number in to input field, no matter if its numeric keypad or character keys)

**Comment by hodgef** [comment]
Hello @pastuh,

I'm not completely sure what you mean. If you are using the `physicalKeyboardHighlight` option, it will only highlight keys. It does not press them. There would need to be an extra option to press the highlighted keys, which is something I'm planning to eventually release here:

https://github.com/hodgef/simple-keyboard/projects/3#card-24458238

Please let me know if I understood the issue wrong or if you have more details to add.

Regards,
Francisco Hodge

**Comment by sleepindawg** [comment]
@hodgef If I read your comments here correctly you may have already been close to writing code for something that I would find very useful.

I would like to teach myself touch typing on my physical keyboard remapped to a DVORAK layout. However, I need a guide to make sure that I'm pressing the correct keys on the keys that are marked for QWERTY. If I had something onscreen that would highlight virtual keys as I press them on the keyboard I would be able to train my fingers to press the keys that I want to press. Back when I had Win 7 there was such a program named Frontype but it no longer is supported by the programmer and will not work on Win 10 or 11. If you would be willing to work in that direction I would be happy to help by testing the product. I personally doubt that 69 years old I could learn to code and write such a program in any reasonable time frame.
