### ISSUE TITLE
angular 7 issue

### ISSUE THREAD

**Issue by jschuenke1** [hodgef/simple-keyboard#256]
**Simple-keyboard version**
"version": "2.26.5"

**Describe the bug**
I get an error on compile:
src/app/views/form/form.component.ts(66,34): error TS2339: Property 'onKeyPress' does not exist on type 'FormComponent'.

this occurs for this call:
  ngAfterViewInit() {
    this.keyboard = new Keyboard({
      onChange: input => this.onChange(input),
      onKeyPress: button => this.onKeyPress(button)
    });
  }

**Comment by hodgef** [comment]
Hello @jschuenke1,

Have you created the `onKeyPress` method in your component?

In [this working demo](https://codesandbox.io/s/github/hodgef/angular-simple-keyboard/tree/master/?fontsize=14&module=%2Fsrc%2Fapp%2Fapp.component.ts) (line 29) you can see `onKeyPress` being defined.

Regards,
Francisco Hodge

**Comment by jschuenke1** [comment]
Thanks, I missed that but have it working now!

Jeff Schuenke
Senior Director of Software Development

M: 415 601 0860<tel:(415)%20601-0860> | @: jschuenke@viscira.com
Viscira, LLC | 909 Battery Street | San Francisco, CA 94111<https://maps.google.com/?q=901+Battery+Street+%7C+San+Francisco,+CA+94111&entry=gmail&source=g>
