### ISSUE TITLE
Is it possible to replace the input field on the fly leaving the keyboard up

### ISSUE THREAD

**Issue by grimace** [hodgef/simple-keyboard#274]
I would like to tab through  a number of fields in a form and leave the keyboard visible, applying the keyboard to each new field as I tab.  Is that possible?

**Comment by hodgef** [comment]
Hello @grimace,

To accomplish this, you can use the [`inputName`](https://simple-keyboard.com/documentation/#inputName) option. So when an input is focused, it will set that option to a value (the input's id for example).

Here's an example in vanilla js:
https://codesandbox.io/s/github/hodgef/simple-keyboard-npm-demos/tree/uc-multiple-inputs

Let me know if you have any questions!
Francisco Hodge

**Comment by grimace** [comment]
Thanks so much!
