### ISSUE TITLE
Keyboard size and font size issue

### ISSUE THREAD

**Issue by shrsulav** [hodgef/simple-keyboard#275]
**Simple-keyboard version**
Using CDN

**Describe the bug**
The keyboard looks very small. It was working fine in a webpage of size 800x480, but when the size is changed to 1920x1200, the keyboard size is not proper.

**Screenshots**
![kbd-bug](https://user-images.githubusercontent.com/23706555/66737658-49a6a180-ee8c-11e9-920b-a31833f9739b.JPG)

**Comment by hodgef** [comment]
Hello @shrsulav,

The keyboard is responsive, so this behavior is expected. Please feel free to adjust the CSS in your project so it fits your needs.

Thanks,
Francisco Hodge
