### ISSUE TITLE
I just want to make the buttons bigger. do I need a custom theme?

### ISSUE THREAD

**Issue by grimace** [hodgef/simple-keyboard#278]
also, with buttonTheme, I want to set a class.  do I have to define individual buttons?

 buttonTheme: [
        {
          class: "my-button",
          buttons: "{enter} {bksp} q Q"  <---  do I have to do this?
        },

**Comment by hodgef** [comment]
Hello @grimace ,

Indeed! That's how it's done :)

Regards,
Francisco Hodge
