### ISSUE TITLE
module listeners still active after keyboard destroy 

### ISSUE THREAD

**Issue by tehChromic** [hodgef/simple-keyboard#286]
2.26.17

Event listeners within a module are still attached after keyboard is destroyed. 

To replicate use the physical keyboard after the simple-keyboard is destroyed and watch the console - I have added a keyboard.destroy() call after one second: 

https://codesandbox.io/s/simple-keyboard-layouts-demo-npm-ogbut

**Comment by hodgef** [comment]
Hello @tehChromic,

`destroy` only removes the listeners set by the main simple-keyboard process. Any given module would need to implement their own destruction method (or override the default one) depending on what it does, if it sets any listeners, etc.

I will add a note in the `destroy` docs shortly to clarify this.

Thanks!
Francisco Hodge

**Comment by tehChromic** [comment]
Ah makes perfect sense, thanks!
