### ISSUE TITLE
Navigation through keys within keyboard

### ISSUE THREAD

**Issue by hasibr** [hodgef/simple-keyboard#29]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like to be able to toggle to a mode where I can navigate through the keys in the keyboard using some configurable input. For example, a cursor would start at the top-left most key in the keyboard [0,0]. Pressing the right arrow key on the physical keyboard as an input (or any other configurable input) would move the cursor one column to the right to [0,1]. For example, on a QWERTY layout: if cursor is on 's', moving right will move cursor to 'd'.

**Describe alternatives you've considered**
The Motte keyboard offers a similar feature: https://jsfiddle.net/Mottie/c6ftvy7r/

**Additional context**
![image](https://user-images.githubusercontent.com/34137148/48094422-25543680-e1e0-11e8-9dd0-9e19b9ff3a57.png)

**Comment by hodgef** [comment]
Thanks for creating a ticket for this @hasibr !

I will probably start working on this later today or tomorrow. Stay tuned for updates.

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
Hello @hasibr,

**simple-keyboard-key-navigation** has been released!
https://github.com/hodgef/simple-keyboard-key-navigation

If you have any issues with the module, feel free to open an issue on that repo and I'll check it out.

Regards,
Francisco Hodge
