### ISSUE TITLE
Keyboard stays in memory

### ISSUE THREAD

**Issue by mmben** [hodgef/simple-keyboard#294]
**Simple-keyboard version**
2.26.24

**Describe the bug**
I can't get the keyboard instance out of memory. I noticed 2 possible issues:

1. Simple-Keyboard-Instances in the window are never removed.
If you check line 132 of the keyboard class, the instance is added to the window.
`window["SimpleKeyboardInstances"][
      this.utilities.camelCase(this.keyboardDOMClass)
    ] = this;`
But I can't see where that is ever removed again. Should this be added to the destroy method?

If I remove my keyboard instance from the window instances, it is still not garbage-collected,
thus there is more that retains the object in memory:

2. Handling parent events
It seems some event listeners are registered at the end of the render-method (line 1309ff). I could not see where they are unregistered again.
In my case the keyboard seems to be retained by the callbacks registered to onPointerUp and onPointerDown. (Probably the same issue applies for touch or mouseup.)

I hope you can confirm and fix this. That would help me a lot. Cheers!

**Comment by hodgef** [comment]
Hello @mmben,

Thanks for the detailed report. Indeed, simple-keyboard only removes the listeners that are set [here](https://github.com/hodgef/simple-keyboard/blob/6fe56c3abc4f7843926ea417bda5ffae02318959/src/lib/components/Keyboard.js#L632).

I will release a fix tackling the issue this evening. I'll keep you posted!

Thanks,
Francisco Hodge

**Comment by hodgef** [comment]
Hello @mmben,

I have pushed [this commit](https://github.com/hodgef/simple-keyboard/commit/d92f84f5c3aac250b382775ab3e0bdb00ab2c2c2) which should improve garbage collection.

You can try it out by updating to `simple-keyboard@latest`.

Feel free to reach out if you find any issues.

Thanks!
Francisco Hodge

**Comment by mmben** [comment]
Wow! Your dedication and response time is really awesome! Thank you so much. I will try it out right away.

**Comment by mmben** [comment]
And yes, I can confirm that none of my objects are retained in memory anymore after using your update. Awesome work. Thanks again.

**Comment by hodgef** [comment]
Glad to hear! Thanks again for reporting this 🎉

**Comment by mmben** [comment]
The fix for this bug contains a subtle difference in behavior. 
When creating the keyboard, you can pass the class-name of an element that should host the keyboard.
Before the fix for this bug, the keyboard would leave this element alone when destroying the keyboard. So creating and destroying the keyboard could be done repeatedly.
After the fix, this might not work anymore, since the keyboard will remove the element given to it from the dom. So you have to make sure it is re-created when you plan on repeatedly creating the keyboard.
Not a bug, but maybe a breaking change.

**Comment by hodgef** [comment]
Hello @mmben,

Sorry about that. I've pushed https://github.com/hodgef/simple-keyboard/commit/c36acbb5f6a5ffd8995eb885ca3dfc9df44be350 which should fix this. It's now released under version 2.27.4.

Regards,
Francisco Hodge
