### ISSUE TITLE
If keyboard already has input value. Backspace key doesn't work and keyboard entirely starts new input on pressing any key

### ISSUE THREAD

**Issue by saic77** [hodgef/simple-keyboard#295]
Simple-keyboard version:: 2.26.20

Description-

If keyboard already has value. Following things happen:

1) Backspace doesn't work.
2) If user presses any key it starts new input instead of appending to existing input.

Sandbox link-

https://codesandbox.io/s/github/hodgef/angular-simple-keyboard/tree/master/?module=%2Fsrc%2Fapp%2Fapp.component.ts

Assign any input to "value" variable and issue will be reproduced.

**Comment by hodgef** [comment]
Hello @saic77,

If you want to set simple-keyboard's input to a value, you can use `this.keyboard.setInput("My Value")`

https://simple-keyboard.com/documentation/#setInput

Thanks,
Francisco Hodge

**Comment by saic77** [comment]
Above sandbox link already have setInput method but issue is still there. How to use this method?

**Comment by hodgef** [comment]
Hello @saic77,

I don't get what's the issue with that sandbox. Backspace is working in there and if you type and tap simple-keyboard's keys, the input is appended.

Now, if you edit that sandbox and change the input value, then that value will be out of sync with simple-keyboard. So to put them in sync, you need to *also* call `setInput`.

So any time you change the input value outside simple-keyboard, you need to sync that value with simple-keyboard by using setInput.

Regards,
Francisco Hodge
