### ISSUE TITLE
How to get cursor position in simple keyboard

### ISSUE THREAD

**Issue by saic77** [hodgef/simple-keyboard#296]
Is there is any way to get cursor position in simple keyboard?
Didn't found one in documentation

**Comment by hodgef** [comment]
Hello @saic77,

There's `keyboard.getCaretPosition()` but it's an internal method for which there are no types declared.

I'll track this issue [here](https://github.com/hodgef/simple-keyboard/projects/3#card-29001234) so it can be included in a future release.

Thanks,
Francisco Hodge
