### ISSUE TITLE
 Build error / error file does not exist

### ISSUE THREAD

**Issue by gre0071** [hodgef/simple-keyboard#305]
**Current version 2.27.10 - does not exist:**
/node_modules/simple-keyboard/build/css/**simple-keyboard.css**
/node_modules/simple-keyboard/build/**simple-keyboard.js**

**Version 2.25.3 - is correct**

**Comment by hodgef** [comment]
Hello @gre0071,

The unminified sources have been removed as of version 2.26.0:

>💥 Breaking Changes
>The following changes affect lesser known features and require no action from most users :
>
>Removed unminified dist in order to reduce package size and build times. (d186fb1)

https://github.com/hodgef/simple-keyboard/releases/tag/2.26.0

You can use these assets instead:

JS: `https://cdn.jsdelivr.net/npm/simple-keyboard@latest/build/index.js`
CSS: `https://cdn.jsdelivr.net/npm/simple-keyboard@latest/build/css/index.css`

Regards,
Francisco Hodge
