### ISSUE TITLE
integration with vuex

### ISSUE THREAD

**Issue by Youhan** [hodgef/simple-keyboard#316]
Thanks for the nice package!

I am trying to create a keyboard for all inputs of a Vue app on different pages.
I intend to have it so that on `@focus` of an `input` the keyboard shows up. 
The keyboard components will be placed at the top level of the DOM in the `layout.vue` and the methods would be handled by `Vuex`. 
Is there any example fo this?

**Comment by hodgef** [comment]
Hello @Youhan,

I don't have a vuex example handy. However, there's a vue example about how to handle multiple inputs with a single keyboard instance:

https://codesandbox.io/s/github/simple-keyboard/vue-simple-keyboard-multiple-inputs-example2/tree/master/?fontsize=14&hidenavigation=1&module=%2Fsrc%2FApp.vue&theme=dark

You can also check out the following Q&A entries for more info:
- [Q : How to use simple-keyboard with multiple inputs](https://franciscohodge.com/projects/simple-keyboard/qa-use-cases/simple-keyboard-how-to-use-simple-keyboard-with-multiple-inputs/)
- [Q : How to implement show/hide toggling](https://franciscohodge.com/projects/simple-keyboard/qa-use-cases/show-hide-toggle/)

I hope that these can help you craft a solution for your use-case. If you get stuck along the way, feel free to send me a sandbox with the issue and I'll do my best to help with the debugging.

Regards,
Francisco Hodge

**Comment by b-karin** [comment]
I've forked a sandbox example to show how you can easily integrate simple-keyboard with Vuex.
No changes to SimpleKeyboard component, but in App.vue you change data to computed from mapGetters
```
<script>
import SimpleKeyboard from "./SimpleKeyboard";
import "./App.css";
import { mapGetters } from 'vuex';

export default {
  name: "App",
  components: {
    SimpleKeyboard
  },
  computed: {
    ...mapGetters('keyboard', [
      'isOpen',
      'inputs', 
      'inputName'
    ]),
  },
  methods: {
    onChange(input) {
      this.$store.dispatch('keyboard/updateInput', input);
    },
    onKeyPress(button) {
      console.log("button", button);
    },
    onInputChange(input) {
      this.$store.dispatch('keyboard/updateInput', input.target.value);
    },
    onInputFocus(input) {
      this.$store.dispatch('keyboard/updateInputName', input.target.id);
      this.$store.dispatch('keyboard/openKeyboard');
    }
  }
};
</script>
```

and in your store:
```
const state = {
  isOpen: false,
  inputs: {
    firstName: "",
    lastName: ""
  },
  inputName: ""
};

const getters = {
  isOpen: (state) => state.isOpen,
  inputs: (state) => state.inputs,
  inputName: (state) => state.inputName
};

const actions = {
  updateInput(context, input) {
    context.commit("setInput", input);
  },
  updateInputName(context, inputName) {
    context.commit("setInputName", inputName);
  },
  openKeyboard(context) {
    context.commit("setKeyboardStatus", true);
  },
  closeKeyboard(context) {
    context.commit("setKeyboardStatus", false);
  }
};

const mutations = {
  setInput(state, input) {
    state.inputs[state.inputName] = input;
  },
  setInputName(state, inputName) {
    if (Object.keys(state.inputs).indexOf(inputName) !== -1) {
      state.inputName = inputName;
    }
  },
  setKeyboardStatus(state, status) {
    state.isOpen = status;
  }
};

export default {
  state,
  getters,
  actions,
  mutations,
  namespaced: true
};
```

In my example keyboard opens on focus. You can then add smth. like vue-click-outside to close the keyboard, but make sure not to fire it when user clicks on keyboard itself.

**Comment by Youhan** [comment]
This one is pretty old but maybe good to get the idea
https://codesandbox.io/s/demo-nuxt-spa-simplekeyboard-vuex-wi3kk
