### ISSUE TITLE
 preventMouseDownDefault: true  issue

### ISSUE THREAD

**Issue by dedosmedia** [hodgef/simple-keyboard#319]
Whenever I use  preventMouseDownDefault: true I can see the caret all the time, but if at the time of writing I change the caret to the middle of the word to add some missing letters, once I press a key the caret will be placed at the end of the string although the characters will be added ad the right place.

https://codesandbox.io/s/simple-keyboard-npm-demos-7mzqe?fontsize=14&hidenavigation=1&theme=dark

**Comment by hodgef** [comment]
Hello @dedosmedia,

Indeed, when the focus is kept on the input, it is necessary to adjust the element's caret position.

There's an example of caret position handling in the [`preventMouseDownDefault` docs entry](https://simple-keyboard.com/documentation/#preventMouseDownDefault). Here's the sandbox in question:

https://codesandbox.io/s/github/simple-keyboard/simple-keyboard-preventmodefault-caret-pos/tree/master/

However I think it would be useful to have this functionality built-in. I'm going to track this in "Enhancements" for a future release.

Regards,
Francisco Hodge

**Comment by dedosmedia** [comment]
Thanks so much for your Super Quick answer!!!.
Yes, I agree it would be useful to have this as built-in functionality. Anyway, I am going to use this workaround at this moment.
