### ISSUE TITLE
Bootstrap Typeahead is not working with simple-keyboard, why ?

### ISSUE THREAD

**Issue by seAfnan** [hodgef/simple-keyboard#329]

**Comment by hodgef** [comment]
Hello @seAfnan,

I think bootstrap-typeahead might be listening to the input's ["change"](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event) event or something like that. In all the simple-keyboard demos, input is changed via Javascript which do not trigger any such events. These you would need to [trigger yourself](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events) within the `onChange` method.

That is not really a bug in simple-keyboard, just a custom implementation that would be needed to accommodate that plugin.

If you can provide a sandbox demo or repro showing the issue I can help with the debugging.

Regards,
Francisco Hodge

**Comment by seAfnan** [comment]
@hodgef can you help in how I can trigger keyboard key when using simple-keyboard ? I just simply want to get typeahead working with simpel-keyboard. It will be a great regard.

**Comment by flakobatako** [comment]
> Hello @seAfnan,
> 
> I think bootstrap-typeahead might be listening to the input's ["change"](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event) event in order to start showing suggestions. In all the simple-keyboard demos, input is changed via Javascript (`input.value = "..."`) which do not trigger any such events. These you would need to [trigger yourself](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events) within the `onChange` method.
> 
> That is not really a bug in simple-keyboard, just a custom implementation that would be needed to accommodate that plugin.
> 
> If you can provide a sandbox demo or repro showing the issue I can help with the debugging.
> 
> Regards,
> Francisco Hodge

I believe it is in the input event, becuse the input event input triggers when we modify the input.

Look at this fiddle: https://jsfiddle.net/flakobatako/fp7x1rho/

 Right now i'm exactly in the middle of a similar requirement, so i'm gonna try this.

**Comment by hodgef** [comment]
Hello guys,

@seAfnan, as linked above, you can trigger events with Javascript:
https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events

e.g:
```
input.dispatchEvent(new KeyboardEvent("keyup", { key: "a" }));
```

Simple-keyboard has a rough utility function to turn KeyboardEvents to layout buttons [(`this.keyboard.physicalKeyboard.getSimpleKeyboardLayoutKey`)](https://github.com/hodgef/simple-keyboard/blob/master/src/lib/services/PhysicalKeyboard.js#L59) but not the other way around.

I guess an imperfect way to trigger a keyboard event from clicking a simple-keyboard key would be to do this:

```
const onKeyPress = (button) => {
  input.dispatchEvent(new KeyboardEvent("keyup", { key: button }));
};

this.keyboard({ onKeyPress });
```
________

@flakobatako I really hope that works. Before responding on your [ticket](https://github.com/hodgef/simple-keyboard/issues/343) I was testing here:
https://codesandbox.io/s/vue-select-comparison-y4l3e

And sadly didn't get anywhere :\ That's why I was hoping the devs of the autosuggestion plugin could clarify (to avoid the trial and error).

Regards,
Francisco Hodge

**Comment by flakobatako** [comment]
> Hello guys,
> 
> @seAfnan, as linked above, you can trigger events with Javascript:
> https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events
> 
> e.g:
> 
> ```
> input.dispatchEvent(new KeyboardEvent("keyup", { key: "a" }));
> ```
> 
> Simple-keyboard has a rough utility function to turn KeyboardEvents to layout buttons [(`this.keyboard.physicalKeyboard.getSimpleKeyboardLayoutKey`)](https://github.com/hodgef/simple-keyboard/blob/master/src/lib/services/PhysicalKeyboard.js#L59) but not the other way around.
> 
> I guess an imperfect way to trigger a keyboard event from clicking a simple-keyboard key would be to do this:
> 
> ```
> const onKeyPress = (button) => {
>   input.dispatchEvent(new KeyboardEvent("keyup", { key: button }));
> };
> 
> this.keyboard({ onKeyPress });
> ```
> 
> @flakobatako I really hope that works. Before responding on your [ticket](https://github.com/hodgef/simple-keyboard/issues/343) I was testing here:
> https://codesandbox.io/s/vue-select-comparison-y4l3e
> 
> And sadly didn't get anywhere... That's why I was hoping the devs of the autosuggestion plugin could clarify (to avoid the trial and error).
> 
> Regards,
> Francisco Hodge

Thanks i forked your codesandbox and i could so far pass the value to the autocomplete, but now we need to focus the input programatically. 

But somehow don't work 

So i'm assuming this soehow has to do with the component onfocus/onblur behavior.

Right now i believe it would be better if i create a custom autocomplete component.

Thanks again.

**Comment by flakobatako** [comment]
@seAfnan 
I managed to make it work. It feels very hacky but it works:
https://codesandbox.io/s/vue-select-comparison-phvpk

The only thing missimg is the backspace function, but sould be rather simple.

I ended using bootstrap-vue typeahead, beacuse the vue select was too much restrictive.

Thanks @hodgef for the support.

**Comment by hodgef** [comment]
Hey @seAfnan,

Indeed, bootstrap-vue-typeahead looks much easier to work with.

Here's a slightly tweaked version of your example: https://codesandbox.io/s/vue-select-comparison-0umvi

Hope it helps!
Francisco Hodge

**Comment by flakobatako** [comment]
> Hey @flakobatako,
> 
> Indeed, bootstrap-vue-typeahead looks much easier to work with.
> 
> Here's a slightly tweaked version of your example:
> https://codesandbox.io/s/vue-select-comparison-0umvi
> 
> Hope it helps!
> Francisco Hodge

Hi brother. 

Thanks. It's much better.

It seems that vue-bootstrap typeahead component is deprected, they indeed mention here https://github.com/alexurquhart/vue-bootstrap-typeahead/issues/7#issuecomment-493673426 that it would be better to use the vue-simple-suggest.

I'll give it a shot, but thanks to that not mature state of the typeahead component, ironically it's much more flexible.

Thanks for your support.
