### ISSUE TITLE
Use touch events

### ISSUE THREAD

**Issue by MadDeveloper** [hodgef/simple-keyboard#34]
I'm actually working on adding an option `useTouchEvents`, because I need it for my project. Are you interested to see it as PR?

**Comment by hodgef** [comment]
Could you elaborate a bit about the feature? And of course PR are always welcome :+1:

**Comment by MadDeveloper** [comment]
Instead of just having `onclick` and `onmousedown` events, I would like to add the possibility to handle same events with `ontouchstart`, `ontouchend` and `ontouchcancel` (will permits to handle many touch events in the same time, and having many keyboards on the same app (that's one of my today problem))

**Comment by hodgef** [comment]
That would be perfect, looking forward to it!
By the way, if you want to instantiate multiple keyboards, check out these:

react-simple-keyboard:
https://codesandbox.io/s/github/hodgef/demo_npm_react-simple-keyboard_multiple-instances

simple-keyboard:
https://codesandbox.io/s/github/hodgef/demo_npm_simple-keyboard_dispatch-method

**Comment by MadDeveloper** [comment]
I saw this example about multi keyboards, but in my case I don't want to synchronise them, it an interactive tactile table, and two clients in the same time can play with it, so I need to be able to handle two different input at the same time (which is not able by the native way).

**Comment by MadDeveloper** [comment]
Indeed I've one question, I don't see the `build` directory in the `.gitignore`, is it an oversight or voluntary? Is it required in order to be deployed on npm?

**Comment by hodgef** [comment]
Yup it's intentional - just so those that want to self-host can download the release and use the assets on the `./build` folder. They're pretty light assets too I thought it was fair enough to add them to version control

**Comment by MadDeveloper** [comment]
Ok, thank's you!
