### ISSUE TITLE
Change position.

### ISSUE THREAD

**Issue by flakobatako** [hodgef/simple-keyboard#340]
Is it possible to make the keyboard fixed to the bottom (A la Windows 10/Android virtual keyboard)?

Thanks in advance.

Wonderful library!

**Comment by hodgef** [comment]
Hey @flakobatako,

I'd recommend accomplishing this with CSS.

That'll give you more flexibility to achieve many use-cases, such as this one by @Youhan:

![customize](https://user-images.githubusercontent.com/25509135/70482818-95ed1700-1ab4-11ea-9da0-6b16d9c606c5.gif)

Regards,
Francisco Hodge
