### ISSUE TITLE
Is it possible to use the virtual keyboard with an autocomplete control?

### ISSUE THREAD

**Issue by flakobatako** [hodgef/simple-keyboard#343]
I have this use case:

i' m trying to use the virtual keyboard with a vue-select control with AJAX autocomplete, but i can't change the text in the search box programatically, and the search don't get updated.

Is it possible or has anyone implemented this succesfully? It doesn't have to be the v-select component, any control would do, as long it has autosearch.

Thanks.

**Comment by hodgef** [comment]
Hello @flakobatako, I think the maintainer of `vue-select` would be your best bet, as the unknown seems to be how to trigger vue-select programmatically.

My guess is that only internal key listeners have access to this: https://github.com/sagalbot/vue-select/blob/master/src/components/Select.vue#L27

Once we can trigger vue-select programmatically, then the rest is much easier to handle.

_________

On the other hand, If you'd like to create your own solution, perhaps something like `simple-keyboard-autocorrect` can help. I think it can be made to fit your use case, although it requires custom development to turn it into what you want:

Demo: https://codesandbox.io/s/00jzw1ry70
Usage: https://franciscohodge.com/projects/simple-keyboard/modules/autocorrect/

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
For anyone who finds this issue from search:

Further solutions discussed here
https://github.com/hodgef/simple-keyboard/issues/329#issuecomment-564808656
