### ISSUE TITLE
Custom button theme not working in vue with complex/custom buttons.

### ISSUE THREAD

**Issue by flakobatako** [hodgef/simple-keyboard#348]
**Simple-keyboard version**
2.27.37

**Describe the bug**
I'm trying to customize my keyboard passing the following option in my VUE mounted hook.
buttonTheme: [
        {
          class: "hg-red",
          buttons: "Q q 1 {bksp} {enter} {space}"
        }
      ]

https://codesandbox.io/s/vue-layout-54b8l

The style is aplied to the Q, q and 1 keys, but is not aplied for the "named" buttons.

**Screenshots**
![image](https://user-images.githubusercontent.com/28810524/70867178-23f35280-1f38-11ea-9d8a-309131f5a53c.png)

In the render method, inside the react example  (i even removed  some options):
![image](https://user-images.githubusercontent.com/28810524/70867256-26a27780-1f39-11ea-86c1-32f539661575.png)

**Comment by flakobatako** [comment]
Nevermind this css from the example did work:

.simple-keyboard.hg-layout-default .hg-button.hg-red {
  background: rgb(255, 0, 0, 0.7);
  color: white;
}

**Comment by spook1** [comment]
I tried this and it works half...
I set the buttonTheme using the options method:

 let buttonTheme = [{
                class: "simple_keyboard-button",
                buttons: "A B C D E F G H I J K L M N O P  Q R S T U V W X Y Z {enter} {bksp} "
            },
            {
                class:"weetniet-button",
                buttons:"{weetniet}"
            } ];

**css:**
.simple_keyboard-button {
    background: #9ab6f1;
    color: #100b88;
  }
  
  This changes the text color but not the background.  !?

**Comment by hodgef** [comment]
> I tried this and it works half... I set the buttonTheme using the options method:
> 
> let buttonTheme = [{ class: "simple_keyboard-button", buttons: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z {enter} {bksp} " }, { class:"weetniet-button", buttons:"{weetniet}" } ];
> 
> **css:** .simple_keyboard-button { background: #9ab6f1; color: #100b88; }
> 
> This changes the text color but not the background. !?

Maybe you need to make your CSS selector more specific, like `.hg-button.simple_keyboard-button`. Feel free to experiment in DevTools, or create a new issue with a sandbox example and I can help debug. Thanks
