### ISSUE TITLE
Multiple Dynamic inputs using a textarea element

### ISSUE THREAD

**Issue by Xenoha** [hodgef/simple-keyboard#363]
**Simple-keyboard version**
As some bugs have been addressed in later versions, please ensure you are running the latest.

I am not sure if this is a bug or a poor use of your software. However, I am having trouble implementing your multiple inputs solution from the below sandbox with minor differences including textarea boxes and dynamic inputs property. Simple Keyboard version 2.27.6 | Vue version: 2.6.10

https://codesandbox.io/s/github/simple-keyboard/vue-simple-keyboard-multiple-inputs/tree/master/?fontsize=14&module=%2Fsrc%2FApp.vue

**Describe the bug**
Like the example you have provided above I am using multiple inputs. However, the main difference is that I am using textarea elements not input elements and the inputs object is a data property that starts off empty. If the user touches a button I add a UUID value and a property in the inputs object as a key and and empty string as the value through a watcher in the main view. 

Like your example, I use a watch in the SimpleKeyboard component to watch input and inputName. 

The Problem (I think):
The watch for the input never fires. So when I type on the keyboard the code that executes in your code will not update the textarea element. The inputName watcher fires and outputs in the console the correct name of the component.

Thank you for your assistance and any suggestions would be greatly appreciated.

**Screenshots**
SimpleKeyboard Component:
![image](https://user-images.githubusercontent.com/36129208/71184227-0a575100-223f-11ea-970b-712dbc311501.png)
![image](https://user-images.githubusercontent.com/36129208/71184265-1e02b780-223f-11ea-9d98-4a0ce3a76e5c.png)

Main view:
![image](https://user-images.githubusercontent.com/36129208/71184328-38d52c00-223f-11ea-8899-803c364ecdad.png)
![image](https://user-images.githubusercontent.com/36129208/71184453-6a4df780-223f-11ea-9fc0-ccf40c4f38a5.png)

AnnotationTextArea Component:
![image](https://user-images.githubusercontent.com/36129208/71184584-95d0e200-223f-11ea-8750-a58846278dfd.png)
![image](https://user-images.githubusercontent.com/36129208/71184658-b5680a80-223f-11ea-98a7-b79aff8bf907.png)
![image](https://user-images.githubusercontent.com/36129208/71184695-c44ebd00-223f-11ea-83f3-0ff24f3cda82.png)

**Comment by hodgef** [comment]
Hey, can you edit the sandbox you linked and provide the new link:
https://codesandbox.io/s/github/simple-keyboard/vue-simple-keyboard-multiple-inputs/tree/master/?fontsize=14&module=%2Fsrc%2FApp.vue

Without this repro, I'd have to recreate the sandbox from your images and that'll take time.

Best,
Francisco Hodge

**Comment by Xenoha** [comment]
https://codesandbox.io/s/nervous-merkle-3dc20

https://codesandbox.io/embed/nervous-merkle-3dc20?fontsize=14&hidenavigation=1&theme=dark

I didn't bother with the keyboard CSS. The keyboard will appear at the top of the pink container, so if you want to see the box appear click the screen some where in the middle of the container.

**Comment by hodgef** [comment]
Hello @Xenoha,

I think there's an issue with deep watching of objects in vue, I've seen this issue before and can't really explain why it's happening. It doesn't seem to be anything to do with simple-keyboard, as the methods that concern it are being fired.

Anyway, here's a workaround:
https://codesandbox.io/s/heuristic-voice-tdy72

Hope it helps!
Francisco Hodge

**Comment by Xenoha** [comment]
I agree that there is something going on with the watchers in vue. I tried .sync as well as making them deep and immediate with no luck. Thank you for such a quick reply! As a final thought, where do you suggest I place the setInput call for when the user clicks back into the text area? In the onFocus method just take the current textarea value and set it?

**Comment by Xenoha** [comment]
@hodgef the example you provided I have implemented in my project with a tweak to allow me to better track the annotation textarea (available in the workaround you sent). The problem is that if you switch back and forth to previous boxes, the input update of the keyboard doesn't seem to track the value in the box and the backspace stops working. Am I missing a prop in the keyboard to handle the provided input values?

**Comment by hodgef** [comment]
Hello @Xenoha,

I took a look and had to comment this to get it to work:

![image](https://user-images.githubusercontent.com/25509135/73796118-625bff80-477a-11ea-90c3-e3baa7eed0e0.png)

https://codesandbox.io/s/nervous-frog-4v3mw

Hope that helps!
Francisco Hodge

**Comment by Xenoha** [comment]
@hodgef 
I would have never thought to remove setting the input to the keyboard.

I'm not entirely sure how this works, but thanks a lot for assisting!

**Comment by hodgef** [comment]
Hmm, I might have to revisit the Vue demos. I added that input watcher to fix an issue, but I can't remember what. It seems not to be needed (even in the basic demo). I'll take a look, but at least I hope that the quick fix gets you going in the meantime :)

Best,
Francisco Hodge
