### ISSUE TITLE
Update Vuejs demo showcase

### ISSUE THREAD

**Issue by fabiiomiiguel** [hodgef/simple-keyboard#372]
**Is your feature request related to a problem? Please describe.**
Keep input focused after click keyboard key.

**Describe the solution you'd like**
I made a Vuejs version based on yours with persistent focus on input after touch on keyboard, if you want I can pull request that. :)

**Describe alternatives you've considered**
None.

**Additional context**
No context, just thank you by this amazing job.

**Comment by hodgef** [comment]
Hey @fabiiomiiguel ,

That would be awesome. Do feel free to create a PR / share the link here and I'll check it out :)

I'll close the ticket but tag it as follow up so I can keep track.

Best,
Francisco Hodge

**Comment by fabiiomiiguel** [comment]
[https://codesandbox.io/embed/vue-simple-keyboard-zsrek?fontsize=14&hidenavigation=1&theme=dark](url)

Simply added onKeyReleased() and emited an event to focus the pretend input, if you want i have more code like, selection delete or replace with one charecter :)

**Comment by hodgef** [comment]
Thanks for this @fabiiomiiguel ! I like this very straightforward approach.

Currently to keep the focus on the input there's the setting [`preventMouseDownDefault`](https://franciscohodge.com/projects/simple-keyboard/documentation/#preventMouseDownDefault) but if you look at the demo [here](https://franciscohodge.com/projects/simple-keyboard/demos/preventmousedowndefault-demo/) there's extra logic to put the cursor in the right place. Your example is a lot simpler, I'll add it to the docs shortly!

Feel free to share any other demos, it's really appreciated!

Regards,
Francisco Hodge

**Comment by fabiiomiiguel** [comment]
Sorry I forgot the caret, check it now :)
