### ISSUE TITLE
onKeyPress function to be fired by pressing Enter key- requested

### ISSUE THREAD

**Issue by RajniPal** [hodgef/simple-keyboard#373]
Hi, 

on mouse click, onkeypress function is calling. but when press enter, it does not fire. 
I want to do this behavior , that when user press enter, then it's onkeypress fire. because we are devleoping application for Ada. means user just hear and perform action. 

Please help as it's very urgent

**Simple-keyboard version**
As some bugs have been addressed in later versions, please ensure you are running the latest.

**Describe the bug**
A clear and concise description of what the bug is. Providing a [sandbox example](https://codesandbox.io/s/vanilla) or code depicting the issue is important, as this will help us reproduce the issue.

**Screenshots**

**Comment by hodgef** [comment]
Hello @RajniPal,

`onKeyPress` does fire when you click `{enter}` or any other key.

Check out this demo, and you can see the console.logs firing:
https://codesandbox.io/s/github/hodgef/simple-keyboard-npm-demos/tree/master/?from-embed

If your implementation is not behaving like this, feel free to share it with me so I can investigate.

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
Now I understand your request better. You mean "press" as in "pressing the physical keyboard key should trigger a press on the virtual keyboard". Right?

Here's how you can accomplish that:
https://codesandbox.io/s/simple-keyboard-npm-demos-ftnwi

Please refer to [the docs](https://simple-keyboard.com/documentation) for any other options you can use.

Regards,
Francisco Hodge
