### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by matths** [hodgef/simple-keyboard#391]
Hello,

I've just clone the repo and tried to do a `npm install`, which automatically tries to run a `node scripts/build.js`but fails with the following error:

```
$ npm install

> simple-keyboard@2.27.70 prepare /Users/d433890/Desktop/simple-keyboard
> npm run build


> simple-keyboard@2.27.70 build /Users/d433890/Desktop/simple-keyboard
> node scripts/build.js

Creating an optimized production build...
Failed to compile
./src/lib/index.js
Error: Package exports for '/workspace/simple-keyboard/node_modules/@babel/helper-compilation-targets' do not define a '.' subpath
```
I just want to be able to make a production ready build by myself.
Any help welcome.

Thanks, Matthias

**Comment by matths** [comment]
Sorry, seems to be an issue with node version 13.1 only. Upgraded to 13.6 and it works like a charm.
I'll close the issue.

**Comment by hodgef** [comment]
Glad that it's fixed now @matths !

Best,
Francisco Hodge
