### ISSUE TITLE
Question: why doesn't hit enter in default mode go to new line?

### ISSUE THREAD

**Issue by JeffWinder** [hodgef/simple-keyboard#403]
In default mode hit enter doesn't go to new line in the demo and in my app with an html text area. In the Apple/iOS demo it does when the return button is clicked. I'm on a Mac, just wondering if this is expected behaviour? Great lib, thanks!

**Comment by hodgef** [comment]
Hello @JeffWinder,

For that functionality you need to enable the option `newLineOnEnter`.
https://simple-keyboard.com//documentation/#newLineOnEnter

Best,
Francisco Hodge
