### ISSUE TITLE
Dynamic node to insert the keyboard

### ISSUE THREAD

**Issue by leticia-p** [hodgef/simple-keyboard#416]
**Problem description**
I'm using v2.27.0 with Vanilla js.

I was trying to use the keyboard into an application that uses shadow DOM, and I got stuck in this problem:
![image](https://user-images.githubusercontent.com/34240738/73793941-2333ab80-4786-11ea-909f-f60e4789aece.png)
That happens because the `querySelector` doesn't get the node because of shadow DOM.

**Describe the solution you'd like**
I was thinking, and would really awesome if we can set to keyboard, the node that we want to use. So, if `keyboardDOMQuery` was an attribute, and we could configure it as the current node, sending the whole node, the keyboard was going to work even with shadow DOM.

Thanks in advance for your help, the project is amazing.
Any suggestion is welcome (:

**Comment by hodgef** [comment]
Hello @leticia-p,

This feature has been released as of v2.28.0.

Some caveats though: The node must be a `div` and have a class!
**More info and usage:** https://github.com/hodgef/simple-keyboard/releases/tag/2.28.0

Note: The docs will be updated soon with this change.

Regards,
Francisco Hodge

**Comment by leticia-p** [comment]
Hello, @hodgef,

Thank you so much for implementation and also for the speed. 
I've already used whith the new changes, it helped a lot!!

Regards,
Letícia C. Pereira
