### ISSUE TITLE
Increase size of specific buttons

### ISSUE THREAD

**Issue by FringeCoder** [hodgef/simple-keyboard#420]
![merge height](https://user-images.githubusercontent.com/5707766/74032836-36788e00-49b5-11ea-9f36-e655b3037641.png)

I would like some of the buttons to span two rows in height. In the screenshot I would like to have one button for DEL and one button for OK spanning both rows leaving the other buttons where they are. Is there a way to do this?

**Comment by hodgef** [comment]
Hey @FringeCoder,

The [button grouping feature](https://franciscohodge.com/projects/simple-keyboard/qa-use-cases/style-customize-group-of-buttons/) can take care of that. Check out this demo:

https://codesandbox.io/s/github/simple-keyboard/sk-numeric-row-button-container-demo/tree/master/

Best,
Francisco Hodge
