### ISSUE TITLE
How can I enable caret ?

### ISSUE THREAD

**Issue by luatnd** [hodgef/simple-keyboard#43]
Hi, 
I see some caret implementation in the code but I don't know how to handle the caret or at least show it to the users.
Thanks.

**Comment by luatnd** [comment]
Ah, After read the code I can see caret position is handled but package doesn't have any feature to reflect caret to UI.

**Comment by hodgef** [comment]
Hey @luatnd, could you elaborate on what you mean by "reflect caret to UI"? As you have correctly noted, the keyboard just handles caret positioning. There's an option to disable this handling (which reverts to always adding text at the end of the string).

Regards,
Francisco Hodge

**Comment by luatnd** [comment]
Sorry, I described my problem carelessly.
My case is: I'm using this virtual keyboard on touch devices (mobiles) so users can see both virtual and devices keyboard.
That's why I need to call `element.blur()` to hide the device keyboard. 
For sure, I cannot see the caret.
--> So I'm asking you.
But after thinking and re-read your code, I know I should forget the caret :( 
I could not find a way to hide device keyboard while remaining the caret.
Do you have another workaround?
Anw, thank for your actively supporting.

**Comment by hodgef** [comment]
Hey @luatnd. I've been trying this out and it seems there's no way to do this. The device's keyboard will appear whenever element.focus() is called. I've tried setting readonly="true" then triggering a `.focus` with `event.preventDefault()`, but still the device keyboard comes back.

If you find a way to get this use-case to work. Do let me know and I'll add it to the docs. Thanks

**Comment by luatnd** [comment]
Yes. It's impossible.
Luckily we're running our app via webview so we can ask for help from native code.
Thanks.

**Comment by raeffs** [comment]
@hodgef you mentioned that "There's an option to disable this handling (which reverts to always adding text at the end of the string)." How can this be enabled?

**Comment by hodgef** [comment]
Hey @raeffs ,

Sorry, I forgot to add this one to the docs. The option is called `disableCaretPositioning`.
I will add it to the docs shortly.

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
Hello @raeffs ,

Thanks for the heads up! I've just added the types for this method (^2.13.3).

Regards,
Francisco Hodge
