### ISSUE TITLE
Replace Shift and Alt keys with icons

### ISSUE THREAD

**Issue by CHANDRAKANTHREDDY93** [hodgef/simple-keyboard#433]
Is there a way to replace Shift, Enter and Alt button symbols with custom icons? 
I'm trying to implement it in Angular, would be great if you point me with a working example.

**Comment by hodgef** [comment]
Hey @CHANDRAKANTHREDDY93,

You can just pass in html to the `display` option, like so:
```
{
  display: {
    '{shift}': '<img src="shift.png" />',
    ...
  },
  mergeDisplay: true
}
```
https://simple-keyboard.com/documentation/#display

You can also add an icon through CSS, the choice is yours.

Regards,
Francisco Hodge

**Comment by CHANDRAKANTHREDDY93** [comment]
Thank you. But what if I've pass those icons dynamically in Angular? Can I use some thing like this
{
display: {
`{shift`: `<img [src]="shift">`
}
}

**Comment by hodgef** [comment]
Hey @CHANDRAKANTHREDDY93,

The library will set the value directly in the DOM with innerHTML, so it won't be processed by Angular.

I would recommend just passing a raw HTML to that field. e.g:

```
display: {
  {shift: `<img src="${myImage}" />`
}
```

Regards,
Francisco Hodge

**Comment by antlam** [comment]
Hey @hodgef ! thank you for putting this together.

Along the same lines, I'm trying to replace the alphabet keys (a, b, c, d, etc) with an image. What's the easiest way to do that?
