### ISSUE TITLE
camelCase function is broken

### ISSUE THREAD

**Issue by mkusher** [hodgef/simple-keyboard#44]
**Simple-keyboard version**
1.14 and 1.13 versions of react-simple-keyboard are affected

**Describe the bug**
function `camelCase`(https://github.com/hodgef/simple-keyboard/blob/master/src/lib/services/Utilities.js#L362) from utils will fail on a class name with two dashes, e.g. 'my--weird--class`

**Comment by mkusher** [comment]
So what needs to be added is length check on a word:
```js
const camelCase = (string) => {
  return string
    .toLowerCase()
    .trim()
    .split(/[.\-_\s]/g)
    .reduce((string, word) => word.length ? string + word[0].toUpperCase() + word.slice(1) : string)
}
```

**Comment by hodgef** [comment]
Hey @mkusher, thanks for the fix! Do you mind sending in a PR so you can be credited as collaborator?
If you don't have the time, I can take care of it.

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
Fix now released to npm as of
- simple-keyboard `2.13.1`
- react-simple-keyboard `1.14.1`

Thanks!
