### ISSUE TITLE
keyboard-popup

### ISSUE THREAD

**Issue by brkicmilan** [hodgef/simple-keyboard#440]
**Describe the solution you'd like**
Hello @hodgef ,

I think it is necessary to add this functionality to the keyboard as well to avoid character buildup.

**Additional context**
![keyboard-popup](https://user-images.githubusercontent.com/36232421/75791949-9b819280-5d6d-11ea-8072-c6dcd3609bc7.png)

**Comment by hodgef** [comment]
Hello @brkicmilan,

I agree that this would be a nice addition, perhaps as a [module](https://franciscohodge.com/projects/simple-keyboard/modules/). I will track this item in the [Enancement Proposals](https://github.com/hodgef/simple-keyboard/projects/3#column-3744996) and pick it up when I have some time to implement it. I will also consider any PRs for such a feature.

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
Potentially fixed by v3.0.0 and its new option `layoutCandidates`
https://hodgef.com/simple-keyboard/documentation/options/layoutcandidates/
