### ISSUE TITLE
Adding  material svg instead of button hex values

### ISSUE THREAD

**Issue by CHANDRAKANTHREDDY93** [hodgef/simple-keyboard#446]
Hi
I'm trying to add svg dynamically instead of buttons. But I wasn't able to do so. Please help me with this.
Below is the snippet of what I tried

{
  display: {
'{shift}': '<mat-icon [svgIcon]=shift'/>'
}
}

**Comment by hodgef** [comment]
@CHANDRAKANTHREDDY93,

Like I said on #433, you can only pass raw html to that property. No Angular code.

Regards,
Francisco Hodge

**Comment by CHANDRAKANTHREDDY93** [comment]
@hodgef 
Thanks for the response.
I tried to create mat-icon dynamically using Renderer2 in Angular and passing that element to the display but it doesn't work. Below is the snippet of it.
     
Example:
     const div = this.renderer.createElement('div');
      const matIcon = this.renderer.createElement('mat-icon');
      this.renderer.appendChild(matIcon, this.renderer.createText('home'));
      this.renderer.addClass(matIcon, 'mat-icon');
      this.renderer.addClass(matIcon, 'material-icons');
      this.renderer.appendChild(div, matIcon);
       this.renderer.appendChild(this.elRef.nativeElement, div);

{
   "display: div
}

But in the Dom I'm seeing something like this

<span<[object HTMLDivELement]</span>.

 Please help

**Comment by hodgef** [comment]
I think the issue is that you're passing a div's _object_ to an option that expects raw a raw html _string_.

Can you try passing `div.outerHTML` or `div.innerHTML` instead?

**Comment by CHANDRAKANTHREDDY93** [comment]
I tried both this. But it is not displaying the icons. It is displaying text only.

**Comment by hodgef** [comment]
Hmm, how about using just the plain material icons in html?

https://material.io/resources/icons/?style=baseline

eg:
```
<i class="material-icons">
cached
</i>
```

**Comment by CHANDRAKANTHREDDY93** [comment]
Ya unfortunately that didn't help either. But this is working in stackblitz

**Comment by hodgef** [comment]
Did you add `encapsulation: ViewEncapsulation.None,` in your component? I see no reason why that shouldn't work in your env while it works in StackBlitz 🤔 At that point I think it's not an issue with simple-keyboard

```
@Component({
  selector: "app-root",
  encapsulation: ViewEncapsulation.None, // <<<<<<<<<<<
  templateUrl: "./app.component.html",
  styleUrls: [
    "../../node_modules/simple-keyboard/build/css/index.css",
    "./app.component.css"
  ]
})
```

**Comment by CHANDRAKANTHREDDY93** [comment]
![keyboard code](https://user-images.githubusercontent.com/23726910/76102417-f994bc80-5f9d-11ea-95dc-6879a78a7e60.PNG)
![Uploading Keyboard Err.PNG…]()

Yes I've encapsulation set to none in my component. I've added the image of the keyboard on the browser and its code in the Dom.

**Comment by hodgef** [comment]
I don't see any `ics-image-uppercase` in material-design. Are you sure you got it from here?
https://material.io/resources/icons/?icon=compare_arrows&style=baseline

**Comment by CHANDRAKANTHREDDY93** [comment]
No that's our custom icon. I've it inside my assets folder and registered inside the icon registry module

**Comment by hodgef** [comment]
Does it work when you use a standard material icon?

**Comment by CHANDRAKANTHREDDY93** [comment]
No it doesn't work either.

**Comment by hodgef** [comment]
In that case I would need from you a test repository or at least a sandbox demo that shows the issue. Otherwise I can't help much sadly. I don't like having a long back and forth, looking at the code is way faster than guessing.

**Comment by CHANDRAKANTHREDDY93** [comment]
Will give you test repo in just a bit

**Comment by CHANDRAKANTHREDDY93** [comment]
@hodgef 
It is working with icons from here. 
https://material.io/resources/icons/?icon=compare_arrows&style=baseline

But it doesn't work icons from Assets folder. Not sure why? Any suggestion would be greatly appreciated.

**Comment by hodgef** [comment]
Once again: Please provide a repo or sandbox where I can see the issue happening and debug it. We've already done some back and forth guessing here and I don't want to continue doing that.

Regards,
Francisco Hodge
