### ISSUE TITLE
Two simple-keyboards in a form

### ISSUE THREAD

**Issue by ngoctrunght19** [hodgef/simple-keyboard#447]
**Simple-keyboard version**
2.28.24

**Describe the bug**
I have two div boxes with class 'simple-keyboard', but only the first shows the virtual keyboard, the second does not shows.

**Screenshots**
![image](https://user-images.githubusercontent.com/20590769/76069727-e3025b80-5fc5-11ea-90fe-f669b21820b2.png)

**Comment by hodgef** [comment]
Hello @ngoctrunght19,

Check out this Q&A entry:
<https://franciscohodge.com/projects/simple-keyboard/qa-use-cases/multiple-keyboard-instances/>

Regards,
Francisco Hodge
