### ISSUE TITLE
Hide mobile keyboard

### ISSUE THREAD

**Issue by truonganhhoang** [hodgef/simple-keyboard#450]
Could you have a flag to allow hiding the virtual keyboard of mobile devices when your keyboard is active.

**Comment by hodgef** [comment]
Hey @truonganhhoang,

I think what you're asking is for the mobile keyboard not to show up when you tap on an input. This is something you would have to fix on the input itself and it's out of scope for simple-keyboard.

Check out this StackOverflow solution:
https://stackoverflow.com/a/7610923/1467941

Thanks,
Francisco Hodge
