### ISSUE TITLE
Getting a compile error when trying to use the new element constructor in TypeScript

### ISSUE THREAD

**Issue by patrickjholloway** [hodgef/simple-keyboard#452]
**2.28.27**

**Describe the bug**
Getting a compile error when trying to use the new element constructor in TypeScript:
Argument of type 'Element' is not assignable to parameter of type 'string'.

**Screenshots**
<img width="1086" alt="Screen Shot 2020-03-12 at 6 54 11 PM" src="https://user-images.githubusercontent.com/1310877/76574512-e9e01100-6492-11ea-9913-66acb27453bc.png">

**Comment by hodgef** [comment]
@dependabot-bot rebase

**Comment by hodgef** [comment]
Thanks for the PR @patrickjholloway ! I'm looking into this right away.
