### ISSUE TITLE
Error integrating in Angular 9

### ISSUE THREAD

**Issue by atifsaddique211f** [hodgef/simple-keyboard#454]
**Simple-keyboard version**
  "simple-keyboard": "^2.28.31",

**Describe the bug**
Issue integrating in Angular 9 app.
https://github.com/CTemplar/webclient

**Screenshots**
<img width="1381" alt="Screenshot 2020-03-18 at 2 09 17 PM" src="https://user-images.githubusercontent.com/8865972/76943999-162bdf80-6922-11ea-826b-7de7cdda550e.png">

**Comment by atifsaddique211f** [comment]
After spending a bit of time, I fixed the issue, thank you. no worries.

**Comment by hodgef** [comment]
Glad it works now!
