### ISSUE TITLE
Trouble using w/NextJS

### ISSUE THREAD

**Issue by ajoslin103** [hodgef/simple-keyboard#476]
using react-simple-keyboard with NextJS fails with 

> ReferenceError: window is not defined

I will update this issue with my solution shortly

Al;

starting from the NextJS tutorial, create an app & add this as the pages/index.js file

```
import React from 'react';

import Keyboard from 'react-simple-keyboard';
// import 'react-simple-keyboard/build/css/index.css'; // NOTE: load from _app.js

export default function Index() {

  onKeyPress = (button) => {
    console.log("Button pressed", button);
  }


  return (
    <div>
      <Keyboard
        onChange={this.onChange}
        onKeyPress={this.onKeyPress}
      />
    </div>
  );
}

```

and add this as the pages/_app.js file

```
import '../styles.css'

import 'react-simple-keyboard/build/css/index.css';

export default function MyApp({ Component, pageProps }) {
  return <Component {...pageProps} />
}

```
 
The result is this error:

```
ReferenceError: window is not defined
(anonymous function)
/Users/ajoslin/Documents/Als/Development/EPC/Development/mobile-remote-activation/node_modules/react-simple-keyboard/build/index.js:12:292
Module._compile
internal/modules/cjs/loader.js:688:30
Module._extensions..js
internal/modules/cjs/loader.js:699:10
Module.load
internal/modules/cjs/loader.js:598:32
tryModuleLoad
internal/modules/cjs/loader.js:537:12
Function.Module._load
internal/modules/cjs/loader.js:529:3
Module.require
internal/modules/cjs/loader.js:636:17
require
internal/modules/cjs/helpers.js:20:18
react-simple-keyboard
webpack:/external "react-simple-keyboard":1
> 1 | module.exports = require("react-simple-keyboard");
View compiled
__webpack_require__
./webpack/bootstrap:21
  18 | // Execute the module function
  19 | var threw = true;
  20 | try {
> 21 | 	modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
     | ^  22 | 	threw = false;
  23 | } finally {
  24 | 	if(threw) delete installedModules[moduleId];
View compiled
Module../pages/index.js
/_next/development/server/static/development/pages/index.js:108:79
__webpack_require__
./webpack/bootstrap:21
  18 | // Execute the module function
  19 | var threw = true;
  20 | try {
> 21 | 	modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
     | ^  22 | 	threw = false;
  23 | } finally {
  24 | 	if(threw) delete installedModules[moduleId];
View compiled
3
/_next/development/server/static/development/pages/index.js:148:18
__webpack_require__
./webpack/bootstrap:21
  18 | // Execute the module function
  19 | var threw = true;
  20 | try {
> 21 | 	modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
     | ^  22 | 	threw = false;
  23 | } finally {
  24 | 	if(threw) delete installedModules[moduleId];
View compiled
▶ 2 stack frames were collapsed.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.
```

**Comment by ajoslin103** [comment]
yeah, came to the same conclusion -- now I've wrapped the simple-keyboard

```
import React, { Component } from "react"

// import this via _app.js
// import "simple-keyboard/build/css/index.css"

class NextSimpleKeyboard extends Component {
  constructor(props) {
    super(props)
  }

  componentDidMount() {
    if (window) {
      import("simple-keyboard").then(KeyboardClass => {
        const Keyboard = KeyboardClass.default;
        const keyboardProps = this.keyboardProps;
        this.keyboard = new Keyboard({ ...keyboardProps });
      })
    }
  }

  render() {
    return (
      <div className="simple-keyboard" />
    )
  }
}

export default NextSimpleKeyboard

```
and use it thusly


```
import NextSimpleKeyboard from '../components/next-simple-keyboard';

export default function Index() {

  const onKeyPress = button => {
    console.log("Button pressed", button)
  }

  const keyboardProps = {
    onKeyPress
  };

  return (
    <div>
      <p>Hello Next.js</p>
      <NextSimpleKeyboard keyboardProps={keyboardProps} />
    </div>
  );
}

```

which is basically the same as your src/lib/components/Keyboard.js

but that is not in your build folder...

**Comment by ajoslin103** [comment]
I used your simple-keyboard with Aurelia the week before last - and got around the needing multiple keyboard with this: 

> <template class="${domClass}" containerless> </template>

which is the same as yours:   

> return <div className={cssClass} />;

So I keep ending up where you've been 

(I did say you were fast :) 

Wish your build included a wrapper of some sort

At your speed I bet you're handling some React requirements that I don't know about yet

🥇

**Comment by hodgef** [comment]
Excellent, I'm glad it's working!

Regarding the wrapper, it really makes sense to have that built-in. The reason I'm only adding those to demos (such as [this one](https://franciscohodge.com/projects/react-simple-keyboard/demos/typescript-hooks-demo/) and [this one](https://franciscohodge.com/projects/simple-keyboard/demos/vue-basic-setup/)) is just to help with the maintainability of the project.

My approach is to keep simple-keyboard and the react version/wrapper (react-simple-keyboard) 1:1 and very lean/generic. In some cases, this results in the developer having to adapt demos to their needs. It's not ideal, but it really saves time and allows me to focus on responding to issues faster.

So I hope you don't mind that this stays like that. Of course if you come across an issue or error with the project, I'll be here to help.

Cheers

**Comment by ajoslin103** [comment]
I totally understand!  Each keystroke takes physical time and [dammit] we must sleep at some point.  You've only got so many keystrokes in a day -- this one took time, so did that one !!

How can I contribute what works for me by the end of this project -- be it to a demo or whatever?

**Comment by hodgef** [comment]
Agreed 😄 About contributing, if you want to share a NextJS demo/sandbox, feel free to link in here and I can add it to the getting started guide. Thanks a lot!

**Comment by ajoslin103** [comment]
https://codesandbox.io/s/nextjs-cevwj

(I think...)

it's not working yet for me and I'm out of time for tonight

**Comment by alejandroclaro** [comment]
Please consider reopen this issue.

The proposed solution is not complete and it's more like a hack than another thing.

For example, we need to have a reference to the instance of the widget in a Vue.js component that is written in Typescript. We can use dynamic import in the mounted hook, or use `require('simple-keyboard').default`. However,  when that is done, the typescript declaration is not imported, so we have to copy and paste part of the typescript declaration (.d.ts) into a shim to make it work.

I see no real reason to have to do this. The problem looks like the module is only available as a UMD bundle. It would be nice if a ES6 module, or CommonJS, is also distributed so it can be used in environments where 'window' is not defined yet when the module is imported.

**Comment by hodgef** [comment]
Hello @alejandroclaro,

Simple-keyboard requires a browser (`window`) to function. Adding a dummy `window` object so that a build doesn't fail actually seems more like a hack to me. Instantiating simple-keyboard only when the minimal requirements to run it are met seems to be better practice.

I think this is basically an argument about convenience, and I'm not against convenience.

I committed in #520 to releasing an update to support this without any need for conditional imports. I'm already tracking this in the [Enhancements project](https://github.com/hodgef/simple-keyboard/projects/3#card-36655260), so there's no need to keep the tickets open.

If you want this to be released asap, please feel free to submit a pull request. Otherwise it will be released when I get time for it, which might not fit your timeline.

Regards,
Francisco Hodge

**Comment by alejandroclaro** [comment]
Hi @hodgef 

We are not using any SSR. It happens in a traditional electron application setup. I also answer with the details here https://github.com/hodgef/simple-keyboard/issues/557#issuecomment-629185031
