### ISSUE TITLE
Module Parse Failing during Production Build

### ISSUE THREAD

**Issue by CPMikeAmato** [hodgef/simple-keyboard#48]
Hi all-

I'm using the on-screen keyboard for a project I've been working on that will be displayed on a touch screen monitor in the cafeteria at my company for employees to enter in their e-mail address and send themselves an email with some info about various topics. I built this web app using Ionic 4 and am running into an issue while building a production version of the application.

The error I'm seeing is as follows:
`
Error: ./node_modules/simple-keyboard/build/css/index.css Module parse failed: Unexpected token (12:10) You may need an appropriate loader to handle this file type. 
`

I've done some messing around myself and can't seem to figure out the issue. Has anyone seen this issue thus far?

Thanks all,
-Mike

**Comment by hodgef** [comment]
Hello @CPMikeAmato,

I haven't tried simple-keyboard in Ionic, but generally in Webpack projects you have a module called ["css-loader"](https://github.com/webpack-contrib/css-loader) which handles css imports.

If you don't have this kind of module in your project (e.g: if you're not using Webpack), you can just download this css file and load it locally in your project, a bit like in the ["Usage with CDN"](https://franciscohodge.com/projects/simple-keyboard/getting-started/#usage-cdn) docs.

Hope that helps, if not let me know and i'll reopen the issue.

Regards,
Francisco Hodge
