### ISSUE TITLE
Auto-size to fit container width

### ISSUE THREAD

**Issue by ajoslin103** [hodgef/simple-keyboard#482]
Is there any way to setup a numeric keypad to expand to fit the size of the enclosing div ?

**Comment by hodgef** [comment]
@ajoslin103 That would probably be done with CSS. If you want me to be more specific, I would need more specific information (e.g: A screenshot of what you have to see what exactly needs adjusting).

**Comment by ajoslin103** [comment]
thanks, I can provide an URL tomorrow
