### ISSUE TITLE
Negative, Floating number value in number type field

### ISSUE THREAD

**Issue by appskitchen** [hodgef/simple-keyboard#49]
**Simple-keyboard version**
v2.13.4

**Describe the bug**
I tried to put a negative or floating point number in a number type input field, when I put - or .(for example only -, or only 2.), the input field comes empty.

Also if i enter a negative number(lets say -9) and try to use backspace, I can't remove that character. Seems only work around is to define that input as text field.

Please let me know any solution.

**Comment by hodgef** [comment]
Hello @appskitchen,

Could you provide a sandbox example of your issue? You can edit the following one for instance then share its link: https://codesandbox.io/s/github/hodgef/simple-keyboard-npm-demos/tree/master/

I will swiftly reopen the issue once you provide a sandbox example.

Thank you,
Francisco Hodge

**Comment by appskitchen** [comment]
@hodgef Here is the code example - 
[https://codesandbox.io/s/n4ymr273nj](https://codesandbox.io/s/n4ymr273nj)

Also caret positioning doesn't work either, if i move the cursor at different position and enter new data, cursor moves at the end although input goes on expected position. You can see this issue on the code sample above.

Thanks for your fast response.

**Comment by hodgef** [comment]
Hello @appskitchen ,

Thank you for providing the sandbox!

**1. Regarding giving simple-keyboard's input to a `input[type="number"]` element**

- simple-keyboard saves all input inside an internal variable (`keyboard.input`). You can see it's contents by setting option `debug` to true. This input is a string.
- What's happening here is that, on the `onChange` method, we're setting this string as the value of an input that is _supposed_ to be taking numbers only. As expected, this is rejected by the browser (as shown in the console).
- Therefore, either your layout should be comprised only of numbers ([like this example](https://codesandbox.io/s/7yzz8r4906)), or you need to further process this string you get at the `onChange` callback, making sure you only pass a number value to that input.

I don't think this is something that I could add to the core library, as simple-keyboard keeps its internal input value and has no awareness of what you do with this value afterward.

**2. Regarding caret positioning not working:**
Caret positioning (selectionStart) seems not to be supported for input having a "number" type. Check out these links for more info:

> https://stackoverflow.com/a/25371702
> https://html.spec.whatwg.org/multipage/input.html#input-type-attr-summary

Please let me know if you have any further questions.

Regards,
Francisco Hodge

**Comment by appskitchen** [comment]
Thanks @hodgef for your prompt response. Trying to find out an workaround.

**Comment by hodgef** [comment]
The new option `inputPattern` has been added as of 2.14.0, hopefully it helps in your implementation !

**Docs:** https://simple-keyboard.com/documentation/#inputPattern
**Sandbox:** https://codesandbox.io/s/github/hodgef/simple-keyboard-npm-demos/tree/uc-inputPattern/

Regards,
Francisco Hodge
