### ISSUE TITLE
Caps Lock should not trigger alternative characters for numeric buttons

### ISSUE THREAD

**Issue by m1gu3l** [hodgef/simple-keyboard#5]

**Comment by hodgef** [comment]
Hello @m1gu3l, thanks for submitting this issue!

By having caps lock do the same behavior as shift, I tried to simplify the layouts and make it easier for those coming over from Mottie Keyboard.

simple-keyboard fully supports a different layout for caps lock however. Here's an example:
[![Edit simple-keyboard handling shift and caps lock demo - npm](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l3n84qn5oq)

I will be adding this use-case to the docs for the sake of clarity.

Regards
