### ISSUE TITLE
Can not include multiple keyboards in an Angular component

### ISSUE THREAD

**Issue by ddahan** [hodgef/simple-keyboard#50]
**Simple-keyboard version**
2.14.3

**Describe the bug**
In Angular 6, when trying to include multiple keyboards in a component (embedding simple keyboard as a component itself), only the first one is displayed/working.
Here is a minimal Github project that shows the issue: https://github.com/ddahan/pockey

**Screenshots**

![image](https://user-images.githubusercontent.com/1933516/52712568-4a9dd100-2f95-11e9-845e-89948e0c8fb3.png)

**Debug**

![image](https://user-images.githubusercontent.com/1933516/52714730-ed0c8300-2f9a-11e9-8589-bd5d29f0c908.png)

As you can see, the first `app-simple-component` div contains a keyboard html content, but the second div contains nothing.

**Comment by hodgef** [comment]
Hey @ddahan,

You need to give a different class to each keyboard instance, otherwise the second instance will just override the first one.

For example:
```
<div class="simple-keyboard"></div>
<div class="keyboard2"></div>
```

```
let keyboard = new Keyboard({
// Options here
});

let keyboard2 = new Keyboard(".keyboard2", {
// Options here
});

```

Docs:
https://franciscohodge.com/projects/simple-keyboard/qa-use-cases/#give-different-class-keyboard

Demo:
https://codesandbox.io/s/github/hodgef/simple-keyboard-npm-demos/tree/uc-dispatch/

This should fix your issue, but if it doesn't let me know and we can look at this further.

Regards,
Francisco Hodge

**Comment by ddahan** [comment]
Hi @hodgef and thanks for quick reply (and for your amazing job on this).

I understand that there is a conflict between 2 keyboards and I think I understood your code samples.

However, in Angular, the clean way to work when you want to use the same stuff several times is to create a unique component (this is what I did with [`SimpleKeyboardComponent`](https://github.com/ddahan/pockey/blob/master/src/app/simple-keyboard/simple-keyboard.component.ts)) and then, to include it with an app selector (here: `<app-simple-keyboard></app-simple-keyboard>`, as many times as you want, in another component.

Looking at your code samples, it seems you want me to instanciate the component twice, which is impossible because the instanciation is made in the component itself.

So, the only two workarounds I can see right now would be :

1. to NOT create a component at all for using keyboards in my app.
2. to duplicate the `SimpleKeyboardComponent` into 2 different components.

In both cases, I think it's not ideal because it breaks the "Don't repeat Yourself" philosophy, if I want to use the same exact keyboard more than once.

Maybe this issue could be marked as "enhancement to respect Angular right way to do"
However, I'm not an expert at all in Angular so I let other people give their opinion about this.

Thanks again.

**Comment by hodgef** [comment]
Hey @ddahan,

I understand what you mean. To accomplish this use case in react for example, I pass the class name though a parameter (prop). Like so:

https://simple-keyboard.com/react/qa-use-cases/#give-different-class-keyboard

I wonder if using a similar approach would work for your use-case.

In any case, for multiple keyboards you do need multiple instances, as the event listeners are bound to each keyboard's DOM element. Another option would be to have a single keyboard to serve all the inputs, like so:

https://simple-keyboard.com.com/qa-use-cases/#using-several-inputs

Hope this helps,
Francisco Hodge

**Comment by ddahan** [comment]
You're right it's the way to go for sure.
In Angular, we have `@input` to provide data to children components.
I tried to use `@Input` to provide class name to the keyboard component., I think it's almost done, but something's wrong with the keyboard component instanciation, I got a DOM error:

![image](https://user-images.githubusercontent.com/1933516/52719425-e8999780-2fa5-11e9-8bd8-bec25bc33c19.png)



Could you take a look to the updated code here please? https://github.com/ddahan/pockey
Thanks!!!

**Comment by ddahan** [comment]
The error makes senses because at `OnInit` level, DOM is not created.
Still investigating how to process, using another lifecycle event (like `AfterViewInit`)

**Comment by hodgef** [comment]
Awesome! Glad you got it figured out. I will update the Angular demos soon to use `ngAfterViewInit` instead of `onInit`. Thanks!

**Comment by ddahan** [comment]
You are the one to thanks ;) 
I updated the Github repo if it can help you to make the demo :)
