### ISSUE TITLE
custom button label and value

### ISSUE THREAD

**Issue by mbretter** [hodgef/simple-keyboard#509]
**Is your feature request related to a problem? Please describe.**
When adding a custom button is there any possibility to define the value which will be written into the input box?
I've added a new button named "clear", within the onKeyPress event I'm handling the action (clearing the input field in this case), but the keyboard writes the name of the button into the input field.

**Describe the solution you'd like**
Distinguishing between label and value for a button, or adding the possibility to change the value inside the onKeyPress event handler, or stopping the default action for a button. Currently the click event object is not passed to onKeyPress, there is no possibility to stop the event propagation.

**Describe alternatives you've considered**
non

**Additional context**
none

**Comment by hodgef** [comment]
Hey @mbretter,

When you call your button `clear`, clicking it will append that exact word to your input.
To have a "function button", you have to add the curly braces to the name: `{clear}`.

Then in your `onKeyPress`, you can do:

```
onKeyPress: (button) => {
  if(button === '{clear}'){
    // ....
  }
}
```

Check out the [`layout`](https://simple-keyboard.com/documentation/#layout) docs for a layout example.

If you'd like to edit the label of the button, you can use the [`display`](https://simple-keyboard.com/documentation/#display) option.

Regards,
Francisco Hodge

**Comment by mbretter** [comment]
thanx for the info with the curly braces, this seems to work, but clearing the inputfield does not work then:

```
        if (button === "{clear}") {
            keyboardRef.current.clearInput()
        }
```

when removing the curly braces the clearInput works, but the word "clear" will be written into the field as described above

cheers
