### ISSUE TITLE
2 keyboards are not visible in browser

### ISSUE THREAD

**Issue by vatsalnarry2** [hodgef/simple-keyboard#511]
Hi,

I have created 2 keyboard in app.js ,only 1 keyboard is visible.
Could you please let me know whther
![1 keyboard displayed](https://user-images.githubusercontent.com/63771450/79420321-57bdb200-7fd6-11ea-9525-f3f053dad349.PNG)
 we can have 2 simple keyboard in app.js file or not

**Comment by hodgef** [comment]
Hello @vatsalnarry2,

Take a look at this Q&A entry:
https://franciscohodge.com/projects/simple-keyboard/qa-use-cases/multiple-keyboard-instances/

Regards,
Francisco Hodge

**Comment by vatsalnarry2** [comment]
I am able to display 2 keyboard.But unable to bind to 2 input.Could you please let me how to do that my code is below


import React, { Component } from "react";
import { render } from "react-dom";
import Keyboard from "react-simple-keyboard";
import "react-simple-keyboard/build/css/index.css";
import "./index.css";

class App extends Component {
  state = {
    layoutName: "default",
    input1: "",
    input2: ""
  };

  onChange = input1 => {
    this.setState({
      input1: input1
    });
    console.log("Input1 changed", input1);
  };

  onChange = input2 => {
    this.setState({
      input2: input2
    });
    console.log("Input2 changed", input2);
  };
  onKeyPress = button => {
    console.log("Button pressed", button);
    if (button === "{shift}" || button === "{lock}") this.handleShift();
  };

  handleShift = () => {
    let layoutName = this.state.layoutName;

    this.setState({
      layoutName: layoutName === "shift" ? "default" : "shift"
    });
  };

  onChangeInput1 = event => {
    let input1 = event.target.value;
    this.setState(
      {
        input1:input1
      },
      () => {
        this.keyboard.setInput(input1);
      }
    );
  };
  onChangeInput2 = event => {
    let input2 = event.target.value;
    this.setState(
      {
        input2: input2
      },
      () => {
        this.keyboard.setInput(input2);
      }
    );
  };
  render() {
    let sharedProps = {
      layoutName: this.state.layoutName,
      onChange1: input1 => this.onChange(input1),
      onChange2: input2 => this.onChange(input2),
      onKeyPress: button => this.onKeyPress(button),

      // This syncs the input of all keyboards
      syncInstanceInputs: true
    };

    return (
      <div>
        <input
          value={this.state.input1}
          placeholder={"Tap on the virtual keyboard1 to start"}
          onChange={e => this.onChangeInput(e)}
        />
         <input
          value={this.state.input2}
          placeholder={"Tap on the virtual keyboard3 to start"}
          onChange={e => this.onChangeInput(e)}
        />

        <div className={"container"}>
          <h3>Keyboard 1</h3>
          <Keyboard keyboardRef={r => (this.keyboard = r)} {...sharedProps} />

          <h3>Keyboard 2</h3>
          <Keyboard {...sharedProps} baseClass={"keyboard2"} />
        </div>
      </div>
    );
  }
}

render(<App />, document.getElementById("root"));
export default App;
