### ISSUE TITLE
How to implement functions keys (F1 to F24)

### ISSUE THREAD

**Issue by tprophet74** [hodgef/simple-keyboard#514]
Hello,

My name is Carles and I usually work with customers using the IBM i midrange system.

I write mobile web applications and I was wondering if there's a way to implement functions keys (Fx) from F1 to F24.

Thanks so much in advance.

**Comment by hodgef** [comment]
Hello @tprophet74,

If by implement you mean to display them in your layout, check out these demos:
https://franciscohodge.com/projects/simple-keyboard/demo-showcase/full-keyboard/
https://codesandbox.io/s/n5mllkkmyl?file=/src/index.js

However if you want these virtual keys to work just like the physical keys (e.g: Pressing F5 refreshes, etc), that's a Javascript question out of scope for this library (and outside of my knowledge sadly).

I recommend you ask on StackOverflow for guidance. As far as I know though, JS in the browser is restricted in what it can call (for example you can't call Alt+F4).

Regards,
Francisco Hodge

**Comment by tprophet74** [comment]
Hi again,
What I just need is the keyboard to send the corresponding keycode ot the browser, not to execute the typical function F5=refresh.
Regards,
Carles

**Comment by hodgef** [comment]
Hey Carles,

In this example you can see (among other things) the keycodes in the console when you press the keys:

https://codesandbox.io/s/n5mllkkmyl?file=/src/index.js:2925-2930

![image](https://user-images.githubusercontent.com/25509135/79679981-a63a9e80-81d8-11ea-88a7-0bb3d55ce583.png)

If you want to dispatch/trigger a keyboardEvent in JS, check out this StackOverflow answer:
https://stackoverflow.com/a/12187302

Regards,
Francisco Hodge
