### ISSUE TITLE
2 keyboard instance are not binding to 2 input field

### ISSUE THREAD

**Issue by vatsalnarry2** [hodgef/simple-keyboard#515]
Hi,

I am able to display 2 keyboard in browser, but when i click.In browser console i see clicked button details are displayed, but not binded to my input fields. My code is below

import React, { Component } from "react";
import { render } from "react-dom";
import Keyboard from "react-simple-keyboard";
import "react-simple-keyboard/build/css/index.css";
import "./index.css";

class App extends Component {
  state = {
    layoutName: "default",
    input1: "",
    input2: "",

  };

  onChange1 = input1 => {
    this.setState({
      input1: input1
    });
    console.log("Input1 changed", input1);
  };
  onChange2 = input2 => {
    this.setState({
      input2: input2
    });
    console.log("Input2 changed", input2);
  };

  onKeyPress = button => {
    console.log("Button pressed", button);
    if (button === "{shift}" || button === "{lock}") this.handleShift();
  };

  handleShift = () => {
    let layoutName = this.state.layoutName;

    this.setState({
      layoutName: layoutName === "shift" ? "default" : "shift"
    });
  };

  onChangeInput1 = event => {
    let input1 = event.target.value;
    this.setState(
      {
        input1: input1
      },
      () => {
        this.keyboard.setInput(input1);
      }
    );
  };
  onChangeInput12 = event => {
    let input2 = event.target.value;
    this.setState(
      {
        input2: input2
      },
      () => {
        this.keyboard.setInput(input2);
      }
    );
  };

  render() {
    let sharedProps = {
      layoutName: this.state.layoutName,
      onChange1: input1 => this.onChange1(input1),
      onChange2: input2 => this.onChange2(input2),
      onKeyPress: button => this.onKeyPress(button),

      // This syncs the input of all keyboards
      syncInstanceInputs: true
    };

    return (
      <div>
       

        <div className={"container"}>
        <input
          value={this.state.input1}
          placeholder={"Tap on the virtual keyboard2 to start"}
          onChange={e => this.onChangeInput1(e)}
        />
          <h3>Keyboard 1</h3>
          <Keyboard keyboardRef={r => (this.keyboard = r)} {...sharedProps} />
          <input
          value={this.state.input2}
          placeholder={"Tap on the virtual keyboard2 to start"}
          onChange={e => this.onChangeInput2(e)}
        />
          <h3>Keyboard 2</h3>
          <Keyboard {...sharedProps} baseClass={"keyboard2"} />
        </div>
      </div>
    );
  }
}

render(<App />, document.getElementById("root"));

export default App;
![2 keyboard error](https://user-images.githubusercontent.com/63771450/79739499-e191b600-831b-11ea-9b1c-e74b591a5133.PNG)

**Comment by hodgef** [comment]
Hello @vatsalnarry2,

It seems you have based your code on [this example](https://franciscohodge.com/projects/react-simple-keyboard/demos/multiple-instances-demo/), but you need to adjust it to work with two inputs. For example:

If you want each keyboard to target a different input, you can't use `sharedProps`. You need to provide different onChange handlers to each instance, different inputs, etc.

You also have this
```
// This syncs the input of all keyboards
syncInstanceInputs: true
```

Which will make all keyboard inputs the same. I think this is not what you want in this case.

Here's an example, feel free to adjust it to your needs:
https://codesandbox.io/s/react-simple-keyboard-demo-8wbu7?file=/src/index.js

If you have issues, please refer to that example and make sure you follow it closely.

Regards,
Francisco Hodge
