### ISSUE TITLE
[Documentation update] CSS is not loaded in Angular6+

### ISSUE THREAD

**Issue by ddahan** [hodgef/simple-keyboard#52]
**Simple-keyboard version**
2.14.2

**Bug**
Following [this reddit thread](https://www.reddit.com/r/Angular2/comments/a2q10z/virtual_keyboard_for_angular/), some users (including me) reported that CSS is not loaded in Angular 6+ using an import statement to load CSS file.

**Solution**
Just don't import the css using `"import 'simple-keyboard/build/css/index.css';"` in the component file. Instead, open `angular.json` at the root of your project, find the `styles` array, and add `"node_modules/simple-keyboard/build/css/index.css"` to it.

It seems it's a new way to load CSS files in new angular. Doing this, I had no further problems with CSS loading.

**Comment by hodgef** [comment]
Hey @ddahan,

Thank you so much for this fix! Indeed I had come across this issue and didn't find a solution for it. I thought it just happened to a few people, but I was wrong.

Thanks a lot for investigating and providing the solution. I'll change the demos right away.

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
The Angular demos are now up to date! Here are the changes:

1. CSS now linked in the component
```
@Component({
  selector: "app-root",
  ...
  styleUrls: [
    "../../node_modules/simple-keyboard/build/css/index.css", <---
    "./app.component.css"
  ]
})
```

2. ngAfterViewInit used instead on ngOnInit
As per #50 :)


**Demos (Angular 5):**
https://simple-keyboard.com/demo/

**Angular 7 demo**
https://codesandbox.io/s/github/simple-keyboard/angular7-simple-keyboard-demo

Thanks again!

Regards,
Francisco Hodge
