### ISSUE TITLE
Tabbed/spatial navigation focus lost

### ISSUE THREAD

**Issue by jeroentradecast** [hodgef/simple-keyboard#53]
I'd like to use this keyboard when mouse is not available (e.g. keyboard, controller, remote control only). Im currently trying to combine this library with [this spatial navigation library](https://github.com/luke-chang/js-spatial-navigation). That works great, except onClick the key loses its focus. 

I've read the source, and it doesn't look like you're rerendering the DOM every press, so do you have any idea what could be causing this?

I'm using this library with react-simple-keyboard by the way, but since that React Component is only some small wrapper for this library, I'm asking here :)

My current options are

````
      useButtonTag={true}
      preventMouseDownDefault={true}

````

**Comment by hodgef** [comment]
Hello @jeroentradecast,

Could you edit [this sandbox](https://codesandbox.io/s/github/hodgef/react-simple-keyboard-demos/tree/master/) as to show the issue, then provide the link?

This will make it easier to track down what's causing the issue.

I'll reopen this ticket once you provide the edited sandbox link.

Regards,
Francisco Hodge

**Comment by jeroentradecast** [comment]
Hi @hodgef 

[https://codesandbox.io/s/nrqo8l4noj](https://codesandbox.io/s/nrqo8l4noj) here's the sandbox. I've only added some css though.

To reproduce:
Focus the sandbox. Press tab multiple times until it focuses a button (red background). Click enter, which will activate one of the keyboard keys but it'll reset the focussed element. *Something* happens which unfocuses/blurs the key.

**Comment by jeroentradecast** [comment]
Small update, this does not happen in the non-React version with the following settings
````
      newLineOnEnter: false,
      physicalKeyboardHighlight: false,
      useButtonTag: true,
      preventMouseDownDefault: true,
````
When I use Chrome devtools in the React version, tab to a button and press enter, it does seem like the full keyboard gets re-rendered by the way. Chrome devtools "unfolds" the keyboard DOM, which afaik means there's a full rerender from scratch.

**Comment by hodgef** [comment]
Yup I noticed by adding the `onRender` method.
https://codesandbox.io/s/lp65o572pq

Seems to be an instance of:
https://franciscohodge.com/projects/react-simple-keyboard/qa-use-cases/#avoid-unintentional-rendering

I'll come back shortly with a fixed version of the sandbox you've provided.

**Comment by jeroentradecast** [comment]
Ah allright, thanks!

**Comment by hodgef** [comment]
Indeed! The issue was the re-rendering caused by onChangeInput's call to this.setState.

Fixed here:
https://codesandbox.io/s/github/simple-keyboard/react-simple-keyboard-github-is-53/tree/master/

The permanent fix to this issue would be to change the demos, but I'm afraid that will make them more difficult to follow (telling people to add keyboard wrapper and whatnot, most users won't need it). I'll consider changing the demos if more issues like this pop up.

Regards,
Francisco Hodge

**Comment by jeroentradecast** [comment]
Yeah, got it. This probably isn't a usecase a lot of people are going to have. 

So, if you're interested, [here's](https://codesandbox.io/s/81mk6qm5l2) what I was going for, with spatial-navigation.js hacked in. I'm very, very happy this works so well! 
I've been using terrible and device-specific code to control badly performing native onscreen keyboards for Smart TVs (samsung, lg, etc). Your library will let me drop all that mess and use this virtual keyboard. 

Again, thanks a lot!

**Comment by hodgef** [comment]
Very nice! Thanks for sharing. I definitely see the use case there. I had coded a module like this a bit ago (not sure if it works on react though), but this looks definitely cleaner. Feel free to take a look at the module:

Sandbox:
https://codesandbox.io/s/zx58y62xwm

Usage:
https://github.com/hodgef/simple-keyboard-key-navigation

Cheers,
Francisco Hodge
