### ISSUE TITLE
how to useoptions in vuejs component

### ISSUE THREAD

**Issue by bluelemonade** [hodgef/simple-keyboard#544]
**Simple-keyboard version**
its not an bug, I tried to change some behaviours in the options like the used buttons and change the displayed name. Where can I change these options!

by the way, really great work!

**Describe the bug**
 this.keyboard.setOptions({
        layoutName: shiftToggle,
        theme: "hg-theme-default",
        maxLength: 40,
        display: {
            '{bksp}': '<<<',
            '{enter}': 'submit',
            '{shift}': 'gross',
        },
        layout: {
            'default': [
                '` 1 2 3 4 5 6 7 8 9 0 - = {bksp}',
                '{q w e r t y u i o p',
                '{lock} a s d f g h j k l',
                '{shift} z x c v b n m {shift}',
                '.de @ {space}'
            ],
            'shift': [
                '~ ! @ # $ % ^ & * ( ) _ + {bksp}',
                ' Q W E R T Y U I O P ',
                '{lock} A S D F G H J K L  {enter}',
                '{shift} Z X C V B N M {shift}',
                '.de@ {space}'
            ]
        }
      });

**Screenshots**

**Comment by hodgef** [comment]
Hey @bluelemonade,

You can set these options when instantiating the Keyboard for the first time, e.g:

```
this.keyboard = new Keyboard({
  onChange: input => this.onChange(input),
  onKeyPress: button => this.onKeyPress(button),
  // More options here, such as
  display: {
    '{bksp}': '<<<',
    '{enter}': 'submit',
    '{shift}': 'gross',
  },
});
```

**Comment by bluelemonade** [comment]
thanks!
