### ISSUE TITLE
Add possibility to hold {arrowleft} and {arrowright} 

### ISSUE THREAD

**Issue by flemgs** [hodgef/simple-keyboard#548]
**Is your feature request related to a problem? Please describe.**
User can't move the cursor inside the input by holding left arrow or right arrow on the virtual keyboard.

**Describe the solution you'd like**
I want `{arrowright}` and `{arrowleft}` to be added to the list of keys that can be held, so I could implement in the `onKeyPress` callback the cursor moving behavior.

**Describe alternatives you've considered**
Let the user click several time the arrows to have the cursor positioned where he wants.

**Additional context**
N/A

Thanks for the great work!

**Comment by hodgef** [comment]
Hey @flemgs,

This should now be working as of 2.29.18. I added the buttons to the list as a quick fix, but eventually I'll put out an option to make this configurable.

Thanks!
Francisco Hodge
