### ISSUE TITLE
can't delete from last character if a value exist 

### ISSUE THREAD

**Issue by isdiop** [hodgef/simple-keyboard#55]
Hi, 
I can't delete from last character if a value exist in my input 
`<input class="input" type="text" name="lastName" value="FOO" id="lastName">`
any idea ?

**Comment by hodgef** [comment]
Hello @isdiop,

Simple-keyboard has an internal input value and sets its caret position according to it. Therefore it doesn't really know about your input elements.

To set simple-keyboard's internal input to a default value, you can use `setInput`:
https://franciscohodge.com/projects/simple-keyboard/documentation/#setInput

Regards,
Francisco Hodge

**Comment by isdiop** [comment]
Fixed ! thx 

FYI 
I modified the function onKeyPress like this and it works, thx 

`function onKeyPress(button) {
    console.log("Button pressed", button);

    if (button === "{bksp}")  {

        let inputId = selectedInput.replace('#','');
        let val = document.getElementById(inputId).value;

        keyboard.setInput(val,inputId);
    }
    /**
     * Shift functionality
     */
    if (button === "{lock}" || button === "{shift}") handleShiftButton();
}`

**Comment by kevzlou7979** [comment]
@isdiop THe code does not work as it will set the value with the current text so nothing happens.
@hodgef Is there an update on this? thanks
