### ISSUE TITLE
Unable to launch simple-keyboard [Error: 'undefined' is not a function (evaluating 'e.includes("[")')]

### ISSUE THREAD

**Issue by vineshbc** [hodgef/simple-keyboard#553]
Simple-keyboard version
latest version v2.29.20

I have used simple-keyboard in my application and is deployed in Dish TV, browser version(Firefox 16.0.1). I am getting issue related to CDN. PFA below.

![Screenshot from 2020-05-07 16-54-26](https://user-images.githubusercontent.com/36573730/81394206-37999280-913f-11ea-934e-63736f4b4264.png)

**Comment by hodgef** [comment]
Hey @vineshbc, since you've reached out in Discord I'll close this issue and respond there. Thanks
