### ISSUE TITLE
With v-model.trim the value disappears

### ISSUE THREAD

**Issue by lima66** [hodgef/simple-keyboard#562]
Simple-Keyboard: 2.29.25

I have different input field and i use v-model.trim for automatically remove the whitespace from user input.
After typing the value disappears.
If i remove .trim it works perfectly.

 Great lib, thanks!

**Comment by hodgef** [comment]
Hey @lima66, thanks for the heads up! I'll set up a demo and see if I can fix it on my end.

**Comment by hodgef** [comment]
Hey @lima66, sorry for the delay. I was able to reproduce this, but I don't think I can fix this within the library. I think the best approach will be a docs entry to warn about it. I'll flag it as such and track it here: https://github.com/hodgef/simple-keyboard/projects/3#column-3774141

Thanks,
Francisco Hodge
