### ISSUE TITLE
Angular tests fail: Error: KEYBOARD_DOM_ERROR

### ISSUE THREAD

**Issue by digilab2017** [hodgef/simple-keyboard#57]
Hi,
the simple keyboard works very good, but unfortunately now all tests of components that use it fail like this:

WARN: '".simple-keyboard" was not found in the DOM.'
HeadlessChrome 72.0.3626 (Mac OS X 10.14.3) RegistrationComponent should create FAILED
	Error: KEYBOARD_DOM_ERROR

Is there a good solution to this?

**Comment by hodgef** [comment]
@digilab2017 

`KEYBOARD_DOM_ERROR` means that `<div class="simple-keyboard"></div>` was not found in the dom at instantiation.

To make the error go away, simple-keyboard needs to find that element when it's run.
https://github.com/hodgef/simple-keyboard/blob/master/src/lib/components/Keyboard.js#L115

You can have a look at my unit tests here:
https://github.com/hodgef/simple-keyboard/blob/master/src/lib/components/tests/Keyboard.test.js#L15

As you see, `testUtil.setDOM();` is being called, which in turn does this:

```
const div = document.createElement('div');
div.className += divClass || "simple-keyboard";
document.body.appendChild(div);
```

Regards,
Francisco Hodge

**Comment by digilab2017** [comment]
Adding that code into the beforeEach of the failing component test fixed it. Thanks

**Comment by andrelutza** [comment]
Hello,
I'm having the same error, but your fix did not solve my issue. Here is my test repository: https://github.com/andrelutza/keyboard-test 
Any ideas what it might be?
Thanks!

**Comment by hodgef** [comment]
@andrelutza It's an issue with your Jest config
In jest.config.js, find this:
```
moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1'
},
```
and replace it with this
```
moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "jest-transform-stub",
    "\\.(css|less)$": "jest-transform-stub"
},
```
