### ISSUE TITLE
'Could not find a declaration file for module 'simple-keyboard-input-mask' in angular8

### ISSUE THREAD

**Issue by ayalaSuperUser** [hodgef/simple-keyboard#578]
**Simple-keyboard version**
 "simple-keyboard": "2.29.24"
 "simple-keyboard-input-mask": "2.2.71"

I have problems when i use 'simple-keyboard-input-mask' package in angular 8.
The installation end successfully, but when i am trying to use the module in the code, i have few errors:

1. Module declaration : _import inputMask from "simple-keyboard-input-mask";_
error:  **"Could not find a declaration file for module 'simple-keyboard-input-mask'."**

2. inputMask keyboard option :  modules:[inputMask],
      inputMask:'(99) 9999999'
error:  '**inputMask' does not exist in type 'KeyboardOptions'**

thanks in advanced.

**Comment by ayalaSuperUser** [comment]
Hi hodgef,

do you have any answer for me?

**Comment by hodgef** [comment]
Hey @ayalaSuperUser, sorry I've been a bit busy. Regarding the first point, the modules do not have types for now. I recommend you to declare this module as shown here:
https://stackoverflow.com/a/50516783

For the second point, this is something I'd have to fix within simple-keyboard. I'll try to get this fixed today.

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
Hello @ayalaSuperUser, the second issue should be fixed as of the latest release. However please apply the workaround detailed above the first issue.

Best,
Francisco Hodge

**Comment by ayalaSuperUser** [comment]
Hey @hodgef,

Thanks a lot for your very quick and  clear answers!

1.  I declared the module as you pointed me here: https://stackoverflow.com/a/50516783 
2.  I reinstalled simple-keyboard

It was compiled successfully!

Thanks,
Ayala.
