### ISSUE TITLE
How to add keyboard as attribute to input element? (In Angular)

### ISSUE THREAD

**Issue by Centaurnia** [hodgef/simple-keyboard#579]
I have created a component (one ts file) for simple-keyboard. It has html, css and ts functionalities and selector name is 'input[simple-keyboard]'.
Trying to add this component as attribute to input element in other pages.
In this way: <input [simple-keyboard] />
Please help to do the same in angular.

Note: It works for Div element 'div[simple-keyboard]'. not for Input element.

**Comment by hodgef** [comment]
Hey @Centaurnia, sorry I'm not sure how to accomplish that. I've never added simple-keyboard as an attribute to inputs before.

I'd suggest asking on StackOverflow, so someone with more knowledge on that can help.

Regards,
Francisco Hodge

**Comment by Centaurnia** [comment]
No problem. I'll post in StackOverflow. Thank you.
