### ISSUE TITLE
Change the style of the whole page when integrating the virtual keyboard in Angular

### ISSUE THREAD

**Issue by Kimp-hub** [hodgef/simple-keyboard#580]
When I integrated the virtual keyboard, it changed the style of the whole page in Angular 8/9, how could I avoid this? I think it was because I used ViewEncapsulation.None as the demo code for Angular.
Thank you so much for answering my problem.

**Comment by hodgef** [comment]
Hello @Kimp-hub,

Simple-keyboard writes directly to DOM, so it doesn't get the Angular artifacts needed for ViewEncapsulation. 

However, one clever dev in the simple-keyboard Discord (Luke) wrote this:

>Have you tried getting rid of ViewEncapsulation on Angular with importing your CSS at a higher level (i.e. angular.json or styles.scss)? I'm doing a lot of custom angular material style overrides and it seems the two methods are either (1) ViewEncapsulation & within the component or (2) At a higher level, angular.json/styles.scss

So if you're having difficulties setting ViewEncapsulation to None, I would suggest linking to simple-keyboard's css in your angular.json or importing it in your styles.scss

Hope that helps,
Francisco Hodge
