### ISSUE TITLE
Can I add custom action buttons to the Keyboard?

### ISSUE THREAD

**Issue by juanMorenoDev** [hodgef/simple-keyboard#588]
I would like to add custom buttons to the keyboard, something like {Accept} {insert} or another kind of shift to switch between difrente layouts, or lenguages like {spanish} etc..

**Comment by hodgef** [comment]
Hello @juanMorenoDev,

Check out the following Q&A page, it also has some demos:
https://hodgef.com/simple-keyboard/questions-answers/edit-add-new-buttons-keyboard/

Regards,
Francisco Hodge

**Comment by juanMorenoDev** [comment]
Thanks!
