### ISSUE TITLE
Korean layout support >2 letter syllables block?

### ISSUE THREAD

**Issue by angga-dev** [hodgef/simple-keyboard#595]
Hi,

I type (ᄀ, ᅥ, ᄂ), I want results like (건) but the end result becomes (거 ᄂ). Is there a way to get the desired results?

English isn't my first language, so please excuse any mistakes.

**Comment by hodgef** [comment]
hello @angga-dev,

Sadly we don't support this yet. We only support the unicode characters that stack by themselves (e.g: https://hodgef.com/simple-keyboard/demos/?d=hindi) but that's about it.

This means that you'll have to do some **custom implementation** to achieve this.

For example, adding custom logic in [`onChange`](https://hodgef.com/simple-keyboard/documentation/options/onchange/) or [`onKeyPress`](https://hodgef.com/simple-keyboard/documentation/options/onkeypress/), manipulating then overriding input ([`keyboard.setInput`](https://hodgef.com/simple-keyboard/documentation/methods/setinput/)) and changing the caret position (`keyboard.caretPosition`).

The logic I would use is basically, checking the last 3 letters entered, if these 3 letters match a combination (eg: 거 ᄂ), then I'd replace these letters with the desired result (건).

Something like (not tested or complete):
```
const combos = {
  '거 ᄂ': '건'
}

// ... then in simple-keyboard
onChange: (input) => {
  const last3Chars = input.substr(-3);
  let newInput = input;
  Object.keys(combos).forEach(combo => {
      newInput = newInput.split(combo).join(combos[combo]);
  });
  
  if(newInput !== input){
      keyboard.setInput(newInput);
      keyboard.caretPosition = null;
      // Would also need to update DOM input element
  }
}
```

I know this custom stuff is a bit tedious so I would ideally create a module/plugin for it, but that won't be anytime soon as I'm quite overloaded with tasks at the moment.

Regards,
Francisco Hodge

**Comment by gsouf** [comment]
@hodgef just fyi, the keyboard cannot be used for korean without this feature. Most of korean words are formed of 3 characters in a stack

**Comment by hodgef** [comment]
Thanks for the heads up @gsouf,

My approach for simple-keyboard is to provide generic modules and to keep the codebase lean... sadly this combos change I feel is quite language specific and would add to the maintenance concerns. Unless someone who needs this wants to help by putting forward a PR or to releasing a module/plugin I don't think this functionality will be supported any time soon.

I would say if this functionality is something you need now and built-in/without extra coding effort, then your best bet would be to seek another library for this purpose.

Thanks,
Francisco Hodge

**Comment by hodgef** [comment]
Update: The Korean keyboard is supported:
https://hodgef.com/simple-keyboard/demos/?d=korean (https://github.com/hodgef/simple-keyboard/issues/1398#issuecomment-1013803909)
