### ISSUE TITLE
How can i configure bengali language?

### ISSUE THREAD

**Issue by MDALIMULALRAZY** [hodgef/simple-keyboard#6]

**Comment by hodgef** [comment]
Hello @MDALIMULALRAZY,

I personally do not know bengali, but here's a layout that can work for that language:

[![Edit Use-case: simple-keyboard layout customization demo - cdn](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/v388k9zvk0)

Basically the important part is this option:
```
layout: {
    default: [
      "1 2 3 4 5 6 7 8 9 0 - \u09c3 {bksp}",
      "{tab} \u09cc \u09c8 \u09be \u09c0 \u09c2 \u09ac \u09b9 \u0997 \u09a6 \u099c \u09a1 \u09bc",
      "\u09cb \u09c7 \u09cd \u09bf \u09c1 \u09aa \u09b0 \u0995 \u09a4 \u099a \u099f {enter}",
      "{shift} \u0982 \u09ae \u09a8 \u09ac \u09b2 \u09b8 , . / {shift}",
      ".com @ {space}"
    ],
    shift: [
      "\u09cd\u09b0 \u09b0\u09cd \u099c\u09cd\u09b0 \u09a4\u09cd\u09b7 \u0995\u09cd\u09b0 \u09b6\u09cd\u09b0 ( ) \u0983 \u098b {bksp}",
      "{tab} \u0994 \u0990 \u0986 \u0988 \u098a \u09ad \u0999 \u0998 \u09a7 \u099d \u09a2 \u099e",
      "\u0993 \u098f \u0985 \u0987 \u0989 \u09ab \u0996 \u09a5 \u099b \u09a0 {enter}",
      "{shift} \u0981 \u09a3 \u09b6 \u09b7 { / {shift}",
      ".com @ {space}"
    ]
  }
```

Feel free to tweak and configure it to fit your needs.

To get Unicode characters in Javascript-readable format (example from "ৌ" to "\u09cc", you can use this tool:

https://r12a.github.io/app-conversion/

Regards
