### ISSUE TITLE
Custom caret implementation

### ISSUE THREAD

**Issue by oleksii-shaposhnikov** [hodgef/simple-keyboard#609]
**Is your feature request related to a problem? Please describe.**
The "simple keyboard" works very well. But how did you guys solve the problem with missing caret cursor?

**Describe the solution you'd like**
If the field should be read-only, what are the ways to see the caret cursor? I tried to implement a simple HTML-based solution, but it works quite buggy and it would be good if you tried to implement this.

**Describe alternatives you've considered**

**Additional context**

**Comment by hodgef** [comment]
Hello @oleksii-shaposhnikov,

What do you mean by "missing caret cursor"?

If you're referring to the input losing focus when the keyboard is used, check out the `preventMouseDownDefault` option
https://hodgef.com/simple-keyboard/documentation/options/preventmousedowndefault/

Regards,
Francisco Hodge

**Comment by oleksii-shaposhnikov** [comment]
> Hello @oleksii-shaposhnikov,
> 
> What do you mean by "missing caret cursor"?
> 
> If you're referring to the input losing focus when the keyboard is used, check out the `preventMouseDownDefault` option
> https://hodgef.com/simple-keyboard/documentation/options/preventmousedowndefault/
> 
> Regards,
> Francisco Hodge

Let's imagine, that the input must always be read-only because the app should control what the user is typing.
In this case, while using the simple-keyboard, the caret cursor (the one that flashes near the text) is missing, because of the read-only field. Hope it makes sense

**Comment by hodgef** [comment]
Hm this seems to be more of a general question about making a cursor display on a read-only input field. simple-keyboard is just where you type stuff, anything input-related is left to the user to handle.

That being said, I think you can just send the simple-keyboard value to a `div` which has a fake `::after` CSS cursor. That should do the trick.

Regards,
Francisco Hodge
