### ISSUE TITLE
Can we have spatial navigation support?

### ISSUE THREAD

**Issue by balasacoe** [hodgef/simple-keyboard#613]
Can we have spatial navigation support for this keyboard to support in Web TV? If this is already available can you please help me for the document.

**Comment by hodgef** [comment]
Hey @balasacoe ,

Check out [simple-keyboard-key-navigation](https://hodgef.com/simple-keyboard/modules/key-navigation/). There's some demos included there as well.

Regards,
Francisco Hodge
