### ISSUE TITLE
Right mouse click on a keyboard key causes infinite input (key is being jammed)

### ISSUE THREAD

**Issue by ianidi** [hodgef/simple-keyboard#627]
Title says it all.

**Comment by hodgef** [comment]
Hello @ianidi,

I haven't been able to reproduce this in the demos: https://hodgef.com/simple-keyboard/editor/?d=hodgef/simple-keyboard-npm-demos/tree/master

Could you provide a sandbox demo with the issue happening? More infos such as browser, OS would also help.

Note: If the browser doesn't fire the onpointerup for some reason (e.g: tab being pressed, mouse going out of window) this might happen. You can use `mouseEvents: true` to use mouse events instead.

Regards,
Francisco Hodge
