### ISSUE TITLE
How to add Icon in the layout

### ISSUE THREAD

**Issue by Centaurnia** [hodgef/simple-keyboard#636]
Hi @hodgef, I'm trying to add an Icon to the layout. Can I do the same.

In the below layout instead of one shift key I wanted to add one icon. Kindly give some idea how to place it.
                                default: [
					"q w e r t y u i o p {bksp}",
					"a s d f g h j k l {enter}",
					"{shift} z x c v b n m , . {shift}",
					"{alt} {space} {downkeyboard}"
				],

**Comment by Centaurnia** [comment]
Sorry I have seen your reply from other Icon issue.  
I'll open the issue again If I am not getting the result after trying the below one.
(https://github.com/hodgef/simple-keyboard/issues/433)

Thank you 👍

**Comment by Centaurnia** [comment]
Hi @hodgef I need to combine these two icon and show it as the attached image. Can you please help on this.
<img width="27" alt="downKeyboard" src="https://user-images.githubusercontent.com/64918196/89398385-abdbd600-d72e-11ea-92da-7a3ed1efad63.PNG">

"{downkeyboard}": "⌨",
"{downkeyboard}": "🞃",

**Comment by hodgef** [comment]
Hello @Centaurnia,

You can either include both icons and style them:

```
display: {
"{downkeyboard}": '<span>⌨</span><span>🞃</span>'
}
// Then add some css to style as desired
```

... or you can add the image directy, but with a backtick ( ` ) if you want to put a variable in it.
```
display: {
"{downkeyboard}": `<img src="${downKeyboardLogo}">`
}
```

Note: The display option takes in [Raw HTML](https://github.com/hodgef/simple-keyboard/issues/433#issuecomment-594992889). If it doesn't work you'd have to check in the inspector what it is actually outputting.

Regards,
Francisco Hodge

**Comment by Centaurnia** [comment]
Yes. It works fine in both way. Thank you so much @hodgef 👍
