### ISSUE TITLE
Backspace button is bugged when switching focus with javascript .focus() method

### ISSUE THREAD

**Issue by LakeQueen** [hodgef/simple-keyboard#64]
**Simple-keyboard version**
Latest build from the CDN.

**Describe the bug**
The backspace button doesn't work if input focus is changed by JavaScript. It still works if the input is focused by a mouse click though.
Demo: https://codesandbox.io/s/3y2r1lzlpq

**Comment by hodgef** [comment]
Hello @LakeQueen,

Thanks for reporting this issue. Ideally when the `inputName` option is changed, the internal caret position should be reset. However it was not.

This has been fixed as of `simple-keyboard@2.20.8`. Feel free to try it out and let me know if you're still having the problem.

Regards,
Francisco Hodge
