### ISSUE TITLE
inputMask with multiple input fields

### ISSUE THREAD

**Issue by digvijayad** [hodgef/simple-keyboard#646]
**Simple-keyboard version**
Simple Keyboard- v2.29.96
simple-keyboard-input-mask v2.2.121

**Describe the bug**
Following the example of "How to use simple-keyboard with multiple inputs", I tried using the input mask with one of the input fields by setting the input mask in the `onInputFocus` event. However no inputMask is applied. If input mask is set as provided in the inputMask example. Both the fields have input mask. 

https://codesandbox.io/s/simple-keyboard-inputmask-multiple-inputforked-crzjx?file=/src/index.js 

**Screenshots**
![image](https://user-images.githubusercontent.com/19765483/90143963-36828d80-dd4c-11ea-969a-30163d711a8e.png)

**Comment by hodgef** [comment]
Hey @digvijayad,

Thanks for reporting this. A similar issue has been raised last week in the [simple-keyboard chat](https://simple-keyboard.com/chat), I'm currently rewriting the input-mask module which should address these issues.

I'll let you know here when that's ready. Hopefully by the end of the week I'll have a release out.

Thanks,
Francisco Hodge

**Comment by digvijayad** [comment]
Hey @hodgef ,
I think i have found the culprit. 

When module is initialized. You are returning false if `keyboard.options.inputMask` option is not available. Since module is not initialized, mask is not set when you change it dynamically in the `onInputFocus` event. 

The workaround  for this is to initialize the inputMask in the constructor, and then remove it in the `onInputFocus` when not needed.

```
let keyboard = new Keyboard({
  onChange: (input) => onChange(input),
  onKeyPress: (button) => onKeyPress(button),
  modules: [InputMask],
  inputMask: "(999) 999-9999"
});
```
```
function onInputFocus(event) {
  selectedInput = `#${event.target.id}`;

  var options = {
    inputName: event.target.id
  };
  if (document.querySelector(selectedInput).classList.contains("phone-mask")) {
    console.log("contains phone-mask");
    options.inputMask = "(999) 999-9999";
  } else {
    options.inputMask = "";
  }
  keyboard.setOptions(options);
}
```
![image](https://user-images.githubusercontent.com/19765483/90178966-bfb0b900-dd7a-11ea-85d0-faeb1d42c551.png)

**Comment by hodgef** [comment]
Hello @digvijayad, thanks for the workaround!

I have published new versions of simple-keyboard (2.30.0) and simple-keyboard-input-mask (3.0.0) that should support multiple inputs out of the box.

Here's the new usage:
```
inputMask: {
    "default": {
      mask: '+1 (999) 999-9999',
      regex: /^[0-9]+$/
    },
    "input3": {
      mask: 'abcde-fghi-0000-00',
      regex: /^[a-z0-9]+$/
    }
},
```

Here's a multi-inputs example:
https://github.com/simple-keyboard/simple-keyboard-input-mask/blob/master/demo/main.js

I have updated the module docs and demos with the new usage instructions:
https://hodgef.com/simple-keyboard/modules/input-mask/

Regards,
Francisco Hodge

**Comment by EugenGedroyc** [comment]
@hodgef, hello! 

I use vue3 and multiple mask does not work.
This work fine with all the inputs:
```
default: {
    mask: '+370 (000) 000-00-00',
    regex: /^[0-9]+$/,
  },
```
But this code not work:

 ```
phone: {
        mask: '+370 (000) 000-00-00',
        regex: /^[0-9]+$/,
      },
      transport: {
        mask: '00-00-000000',
        regex: /^[0-9]+$/,
      },
```

for this inputs:

```
        <input
          id="phone"
          v-model="inputsKeyboard.phone"
          class="mask-input"
          placeholder="+370 (000) 000-00-00"
          type="text"
          @focus="onInputFocus"
        />

        <input
          id="transport"
          v-model="inputsKeyboard.transport"
          placeholder="00-00-000000"
          class="mask-input"
          type="text"
          @focus="onInputFocus"
        />
```

I couldn't find any instructions:
https://hodgef.com/simple-keyboard/modules/input-mask/

And related [example](https://codesandbox.io/s/aged-frog-r67hsp?file=/src/index.js:601-604) don't help me

**Comment by EugenGedroyc** [comment]
I fix my code with help:
  
  ```
watch(
    () => props.inputName,
    (inputName) => {
      keyboard.setOptions({ inputName });
    },
  );
```
The keyboard working without 'props.inputName' 

@hodgef, I suggest add this [example](https://codesandbox.io/s/vue-simple-keyboard-forked-lff8tz)

to [Demos vue](https://hodgef.com/simple-keyboard/modules/input-mask/)
