### ISSUE TITLE
Not working on Apple Safari 13.x (desktop and mobile)

### ISSUE THREAD

**Issue by mgesmundo** [hodgef/simple-keyboard#660]
Hi there,
very best project! I'm sorry but the version 2.29.106 is not working on Apple Safari: the function buttons (e.g. {shift}) do not change the layout. Please try to press the shift button on the online demo. It works fine on Google Chrome and Mozilla Firefox (both on the same Apple MacBook).
Thank you.

**Comment by hodgef** [comment]
Hello @mgesmundo,

For some reason in the main demo the shift key is not working (only on Mac):
https://hodgef.com/simple-keyboard/demos/

However, it does seem to work in the sandbox:
https://codesandbox.io/s/github/hodgef/simple-keyboard-npm-demos/tree/master/?from-embed

![clicktest](https://user-images.githubusercontent.com/25509135/91727719-14707400-eb70-11ea-9c55-725e218ecc5f.gif)


This is probably just an issue with the demo, which I'll take care of soon. However if you have the issue locally, try using the option [`useMouseEvents`](https://hodgef.com/simple-keyboard/documentation/options/usemouseevents/).

Regards,
Francisco Hodge

**Comment by mgesmundo** [comment]
Wow! Super fast answer! Yes I've the same issue but the useMouseEvents option fix it.
Thank you.
