### ISSUE TITLE
How i can use with angular 7 version?

### ISSUE THREAD

**Issue by leandrosouza0786** [hodgef/simple-keyboard#67]
Hey, can i use that keyboard with angular 7 version or  do you have in that version? the projet i start not work version 5.2 =/

Excellent work!

**Comment by hodgef** [comment]
Hello @leandrosouza0786,

Check out this Angular 7 demo:
https://codesandbox.io/s/github/simple-keyboard/angular7-simple-keyboard-demo

Let me know if you run into any issues!

Regards,
Francisco Hodge
