### ISSUE TITLE
Modules - multiple masks

### ISSUE THREAD

**Issue by raffademello** [hodgef/simple-keyboard#682]
Hi Hodgef !

Is there a way to add more mask modules ?
ex:
modules: [inputMaskPhone][inputMaskDate],
inputMaskPhone: {
            "default": {
                mask: '+1 (999) 999-9999',
                regex: /^[0-9]+$/
            }
        },
inputMaskDate: {
            "default": {
                mask: '99/99/9999',
                regex: /^[0-9]+$/
            }
        },

I would like to change the mask according to the component, it is possible ? How can I make this ?

thank you !

**Comment by hodgef** [comment]
Hello @raffademello,

I created this module with multiple inputs in mind, but I'm not sure if the multiple components use-case will also work.

However, you could to set the new options with [`setOptions`](https://hodgef.com/simple-keyboard/documentation/methods/setoptions/).

```
keyboard.setOptions({
  inputMask: {
      "default": {
        mask: '+1 (999) 999-9999',
        regex: /^[0-9]+$/
      },
      "myOtherInput": {
        mask: 'AAAA-BBBB-CC',
        regex: /^[A-Z]+$/
      }
  },
})
```

This way you can change the config on the fly. Another way is to use [`keyboard.destroy()`](https://hodgef.com/simple-keyboard/documentation/methods/destroy/) to discard the old instance and to create a new instance with your desired configuration.

Regards,
Francisco Hodge
