### ISSUE TITLE
Changing caret position requires double click on touchscreen?

### ISSUE THREAD

**Issue by tuomassa** [hodgef/simple-keyboard#695]
**Simple-keyboard version**
2.30.18

**Describe the bug**
After updating to this version, I have to click twice (not double-click per se) to update caret position when using device mode (touch emulation) in Chrome. Unfortunately I cannot test on real touch screen, but I suppose same issue is there. If I single click somewhere between letters and input text, it is appended to the last caret position (typically in the end of input). Works properly without device mode ("toggle device toolbar" in Chrome devtools)

**Comment by Mathaeusxs** [comment]
I can verify that on real touch screen there is same problem as described. Same in Chorme using device mode.. used version was "2.29.43".

Using version 2.29.0 fixes that problem for me.

**Comment by hodgef** [comment]
Hello guys, this would need further investigation and probably a little refactor. For now I added a temp fix (released in 2.30.21) but I'll follow up and push a proper solution soon.

Best,
Francisco Hodge

**Comment by hodgef** [comment]
Hey @tuomassa and @Mathaeusxs, I reverted some of the caret handling code to what we had in 2.29. This should fix the issues on mobile. This proper fix is on **v2.30.24** and onward. Feel free to try it out.

Thanks!
Francisco Hodge
