### ISSUE TITLE
console.log on input focus

### ISSUE THREAD

**Issue by seal62** [hodgef/simple-keyboard#7]
Hey,

Firstly, thanks for sharing this awesome library. Very nice keyboard.

I think there might be a console log in the code. Every time I focus on an input Im seeing a log in the console as screenshot shows. Would you be able to remove this? Thanks.
![image](https://user-images.githubusercontent.com/5068912/45994551-7e0bbc00-c0d7-11e8-8fb0-887c825ad620.png)

**Comment by hodgef** [comment]
Hello @seal62,

Sorry about that! You're using react-simple-keyboard right?

I had pushed version 1.4.2 and when I noticed this console log I quickly pushed 1.4.3.

https://github.com/hodgef/react-simple-keyboard/commit/b10cd932f1144e45091e6ba33fda3d3c122bd9e3

Let me know if the log is gone after an update, if not I'll re-open the issue :)

Regards

**Comment by seal62** [comment]
Whoops! Sorry opened the issue on the wrong repo! Yeah it was for react-simple-keyboard. I’ve tested and seems to be resolved. Thanks for the speedy response!
