### ISSUE TITLE
Can we also support something similar to 'preventMouseDownDefault' for touch event also?

### ISSUE THREAD

**Issue by yzy0704YZY** [hodgef/simple-keyboard#700]
**Is your feature request related to a problem? Please describe.**
I would like to integrate the keyboard onto a smart display device which only has touch screen.

**Describe the solution you'd like**
For example, when detected 'touchend' event, it will call preventDefault().

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by hodgef** [comment]
Hello @yzy0704YZY ! `preventMouseDownDefault` is already called for the events corresponding to "mousedown", e.g: touchstart, pointerdown, etc. 

touchend and touchcancel fires up the "mouseup" event handler instead. For these events, I've added the following new options:

- [preventMouseUpDefault](https://hodgef.com/simple-keyboard/documentation/options/preventmouseupdefault/)
- [stopMouseUpPropagation](https://hodgef.com/simple-keyboard/documentation/options/stopmouseuppropagation/)

These are live as of version 2.30.27. Hope this helps!

Francisco Hodge

**Comment by yzy0704YZY** [comment]
Good to know! Thank you Francisco!
