### ISSUE TITLE
Go to Next and Go to Previous input field 

### ISSUE THREAD

**Issue by vineethma** [hodgef/simple-keyboard#703]
Is it possible to give a next and previous button for going to next input field and previous input fields of a form group in Angular 5

The feature I required is something that is available in angular and IOS default keyboard

**Comment by hodgef** [comment]
Closing this as it was answered in the Discord chat:

>Sorry @vineethma this is out of scope for simple-keyboard - but you can add this custom functionality with plain javascript, there are some examples of it online.

Regards,
Francisco Hodge
