### ISSUE TITLE
Hebrew keyboard showing special character to wrong side

### ISSUE THREAD

**Issue by soumen-cn** [hodgef/simple-keyboard#712]
**Describe the bug**
When I type and special character in Hebrew keyboard it is placing the special character to the wrong side until I type any Hebrew character. Like if I try to enclose the word within a bracket []. But in some situations, the special character may the last character of the sentence. In this scenario, the special character cannot be placed in the proper position. 

**Screenshots**
![Screenshot 2020-10-07 at 10 57 41 AM](https://user-images.githubusercontent.com/56528088/95290960-21c60000-088c-11eb-8835-820d56293db8.png)

**Comment by hodgef** [comment]
Hello @soumen-cn,

I am able to reproduce this with the following hebrew virtual keyboards:

https://www.branah.com/hebrew
https://www.lexilogos.com/keyboard/hebrew.htm
https://gate2home.com/Hebrew-Keyboard

This leads me to believe that this is not a simple-keyboard issue but an issue with Chrome in general.

You can report a chrome bug here:
https://bugs.chromium.org/p/chromium/issues/list

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
Hey @soumen-cn, sorry I for some reason thought you were talking about the text orientation. Let me have a second look at this.

**Comment by soumen-cn** [comment]
Hi @hodgef 

Thanks for the reply. `direction: rtl;` fixed my issue in the input box.
But if you look at `onChange` method on it is returning the wrong input. The position of any special character is not in the proper position initially.

Open the link: https://hodgef.com/simple-keyboard/demos/?d=hebrew and check the console.
Try with trying special characters with Hebrew characters.

**Comment by soumen-cn** [comment]
Hello @hodgef 

I have noticed that when I press any brackets like `[ ] ( ) {  }`  they are showing wrong brackets, the opposite one. Also showing different in the console.

**Comment by hodgef** [comment]
Hello @soumen-cn, this is probably because of the `direction: rtl` CSS that we talked about before.

I think what we need here is an `rtl: true` option in simple-keyboard. This way the input will be entered correctly from the source. I'll work on it and release an update this week.

Thanks!
