### ISSUE TITLE
this component can be implemented as a Web Component.

### ISSUE THREAD

**Issue by Rabbitzzc** [hodgef/simple-keyboard#725]
**Is your feature request related to a problem? Please describe.**
I think this component can be implemented as a Web Component. This makes it easier to cross - end.

**Comment by hodgef** [comment]
Hello @Rabbitzzc,

Thanks for the suggestion! I currently have no plans to turn simple-keyboard into a Web Component, but I might revisit this in the future.

Regards,
Francisco Hodge
