### ISSUE TITLE
Can physical keyboard actually input text through simple keyboard instance?

### ISSUE THREAD

**Issue by dblachut-adb** [hodgef/simple-keyboard#735]
**Is your feature request related to a problem? Please describe.**
On devices without keyboards and mouse (e.g TV) this module can be used together with simple-keyboard-key-navigation and it works great.

Sometimes in is handy to run the app on PC browser to test something quickly. For such case the physical keyboard could imitate the same behavior as on button pressing,

**Describe the solution you'd like**
New option ```physicalKeyboardInput``` next to ```physicalKeyboardHighlight```.
When ```physicalKeyboardInput``` is set to true pressing keys on physical keyboard would actually modify the internal input & fire ```onChange``` event.

**Describe alternatives you've considered**
Manual document onkey listener.

**Additional context**
I am developing app for TV device.

**Comment by hodgef** [comment]
Hey @dblachut-adb, thanks for this proposal - I think it will be useful indeed.

One think to note with `physicalKeyboardHighlight` is that is has some limitations. Basically what it does it take your physical keyboard `keyCode` and searches a button in your simple-keyboard layout with the same name, then applies highlighting to it.

https://github.com/hodgef/simple-keyboard/blob/f4b87e76a8251b695d56f5e38b01dd2cd9261d52/src/lib/services/PhysicalKeyboard.js#L23

So if you press a key in your physical keyboard that does not exist in the simple-keyboard layout, the button won't be found and nothing will happen.

With that note out of the way, I think we could add something like `physicalKeyboardHighlightPress: true`. So when the button is found, it will not only highlight it but press it also. If you're ok with the shortcomings of the whole highlighting system described above, I think this addition could be useful.

I'll see if I can provide a release for it this week. Let me know if there's something I missed.

Thanks!
Francisco Hodge

**Comment by dblachut-adb** [comment]
Sounds great, but maybe together with ```physicalKeyboardHighlightPress``` there could also be ```physicalKeyboardInput``` which would work on all physical keyboard keys (not only those in layout)?
My point with such approach is that you will not have to switch to e.g. numeric key layout to enter some number.

I think this may violate some other options like ```inputPattern``` though... Let me know what you think, I don't insist on my proposal.

> I'll see if I can provide a release for it this week. Let me know if there's something I missed.

No rush with the update, this is just a small improvement that would make my life easier. ;)

Once again: great job with the module, it works and looks great!

**Comment by hodgef** [comment]
Hmm I think my issue with `physicalKeyboardInput` is pretty similar than in https://github.com/hodgef/simple-keyboard/issues/734 - I only call `onChange` when a simple-keyboard button is pressed, since there's a flow and checks that happen on each button press and I wouldn't like a potential `physicalKeyboardInput` to bypass those.

So when it comes to composing text I would definitely route it through button press (even though that's not a perfect solution).

I would say this approach is about reducing effort and risk for bugs. My goal really is to keep simple-keyboard as low maintenance and stable as possible 😄 

I'll go ahead and implement `physicalKeyboardHighlightPress: true` sometime this week, hopefully that'll help a bit!

Best,
Francisco Hodge

**Comment by hodgef** [comment]
The option `physicalKeyboardHighlightPress` is now live as of v2.32.0. Here are docs for it:
https://hodgef.com/simple-keyboard/documentation/options/physicalkeyboardhighlightpress/

Thanks!
Francisco Hodge

**Comment by dblachut-adb** [comment]
> Hmm I think my issue with `physicalKeyboardInput` is pretty similar to #734 - I only call `onChange` when a simple-keyboard button is pressed, since there's a flow and checks that happen on each button press and I wouldn't like a potential `physicalKeyboardInput` to bypass those.
> 
> So when it comes to composing text I would definitely route it through button press (even though that's not a perfect solution).
> 
> I would say this approach is about reducing effort and risk for bugs. My goal really is to keep simple-keyboard as low maintenance and stable as possible smile
> 
> I'll go ahead and implement `physicalKeyboardHighlightPress: true` sometime this week, hopefully that'll help a bit!
> 
> Best,
> Francisco Hodge

Perfectly understandable, thank you for the change I will start using it right away!

**Comment by dblachut-adb** [comment]
@hodgef I am having trouble with verifying your change. It seems that neither ```onKeyPress``` nor ```onChange``` callback is called. Is this intended?

**Comment by dblachut-adb** [comment]
@hodgef Alright, my bad, I was using ```useMouseEvents``` option for some reason. It works! Thank you!
