### ISSUE TITLE
Auto Scroll is not happening when using simple keyboard

### ISSUE THREAD

**Issue by vineethma** [hodgef/simple-keyboard#742]
I have a form group. where there is multiple input fields. But when I click a input field in the bottom of the window, the keyboard comes over the input field. I want the page to be scrolled and keyboard should always come below the selected input field.

Can Someone please help me with this

**Comment by hodgef** [comment]
Hello @vineethma,

This is custom behavior that you would have to implement into your application.

- One approach would be to insert a simple-keyboard target div (`<div class="simple-keyboard"></div>`) inside your input group.
So when you focus the input, you would initialize the keyboard, and when you click outside you would call `keyboard.destroy()`

- Another (easier) approach would be to just pin the keyboard instance to the bottom of the screen using CSS (`position: absolute; bottom: 0`).

Feel free to experiment with these approaches and adapt them to your needs.

Regards,
Francisco Hodge
