### ISSUE TITLE
Feature request: Bind microphone key on physical keyboard (iPhone, iPad, Android) to a custom key

### ISSUE THREAD

**Issue by inglesuniversal** [hodgef/simple-keyboard#749]
For years I have tried to find a way to bind the microphone key on my iphone to a html5 element, button and your amazing script would be so much more enhanced if this can become a reality.

As an Educator (ESL) mobile apps can benefit by having a direct button or key binding directly to the mobile devices key which controls the voice over or speech recognition feature of the phone while dictating a message for example.

Can this be achieved by your script?

STAY SAFE!!!

**Comment by hodgef** [comment]
Hello @inglesuniversal, sadly I don't think this is possible. Perhaps a native keyboard app would have access to this kind of integration. Simple-keyboard runs in a browser, therefore it can't bind itself to events outside of the browser.

Regards,
Francisco Hodge
