### ISSUE TITLE
Doesnt work simple-keyboard on iframe 

### ISSUE THREAD

**Issue by behzadsoleimani** [hodgef/simple-keyboard#758]

**Comment by hodgef** [comment]
@behzadsoleimani, please provide more details on what your trying to achieve specifically. The issue template was added for a reason!

**Comment by behzadsoleimani** [comment]
Ui on Our React Project open in a Frame (Iframe), but simple-keyboard crashed in Iframe probably because simple-keyboard search div with "simple-keyboard" class on window.document not Iframe content. please fix it.
