### ISSUE TITLE
maxLength validation not working for .com button if the last button pressed is .com

### ISSUE THREAD

**Issue by kirty0110** [hodgef/simple-keyboard#759]
We have a usecase where user can enter max 50 characters in an input field, but if the user pressed .com as 50th character then keyboard allows user to add any number of characters.

sandbox- https://hodgef.com/simple-keyboard/editor/?d=hodgef/simple-keyboard-npm-demos/tree/uc-maxlength

**Comment by hodgef** [comment]
Hello @kirty0110, I was able to confirm this. I'll have the fix released later this evening. Thanks!

**Comment by kirty0110** [comment]
Hello @hodgef, Thanks for your prompt response. Also need to provide yahoo.com, hotmail.com and gmail.com buttons. Can the maxlength property function be made flexible enough to incorporate all this.

**Comment by hodgef** [comment]
Yes it will be a generic fix that addresses any maxLength overflows of the sort. I thought I had fixed this already before but I'll double check later today. When the release is out I'll post an update here. Cheers

**Comment by hodgef** [comment]
Hello @kirty0110, this should be fixed as of version 2.32.10. Feel free to give it a try.

Thanks!
Francisco Hodge

**Comment by kirty0110** [comment]
Its works now..Thanks:)
