### ISSUE TITLE
Open link on keypress

### ISSUE THREAD

**Issue by superhackerboy** [hodgef/simple-keyboard#762]
Where would I go to assign a key to function as a link? Right now I have the code shown as below in the component using react-simple-keyboard. It works on Chrome, however, Safari blocks popups such as this.

```js
  const onKeyPress = letter => {
    if (letter === "☕️") {
      window.open("http://2spacemilk.com", "_blank");
    } 
  };
```

**Comment by hodgef** [comment]
Hello @superhackerboy,

If you don't want your button to input text you should wrap it in curly braces (e.g: `{mybtn}`). Then you would change the displayed label for this button by using the `layout` option: https://hodgef.com/simple-keyboard/documentation/options/display/

Regarding opening as a link, that's more of a general Javascript question. If you want to avoid popup blockers you'll need to avoid opening a link as a popup (`_blank`). Probably by using `window.location.href = 'https://...` instead.

Regards,
Francisco Hodge
