### ISSUE TITLE
Why is the input not updating / cursor being set to the correct position? (Vue 2)

### ISSUE THREAD

**Issue by ZaneL** [hodgef/simple-keyboard#774]
Hello,

I'm new to this reactive stuff so I might just be doing something completely dumb. I've attached a gif so that you can see what I'm trying to do, and what isn't working. Essentially I want the user to be able to click on each input and it loads the label + value of the input into the dialog input and lets them edit the value from the dialog. It's almost working except for the fact that the keyboard input buffer isn't being updated.

The dialog opens depending on the value of this "dialog" prop.
`<q-dialog v-model="dialog" persistent>`

I define it in the parent like this:
```
    <InputDialogFullKeyboard
      :inputLabelName.sync="currentInputLabel"
      :inputValue="currentInputValue"
      :dialog.sync="inputDialogOn"
    />
```

...and then in the dialog component I've created a watcher that looks like this:

```
  watch: {
    dialog() {
      if (this.dialog) {
        this.input = this.$props.inputValue;
      }
    }
  }
```

So the idea is that "dialog" is set to true, the dialog opens, the watcher updates this.input with the new prop value. It kinda works -- you can see that the value gets loaded into the input box, but for some reason the keyboard never gets this input change. Any idea what I'm doing wrong? It almost seems like it's related to the dialog opening and the input is updated before the keyboard is rendered, and then once the keyboard is rendered it wipes the input. Not sure...

Any help would be appreciated. Thanks!

![image](https://s8.gifyu.com/images/keyboard_problem.gif)

**Comment by hodgef** [comment]
Hello @ZaneL, do you mind providing a test repository for this? I think the description you provided is very helpful, but I'm not sure what could be causing it and would like to debug it further.

I'll close this for now and reopen when I get the repro. Thanks!

**Comment by ZaneL** [comment]
Thank you!

Here is the link:
[https://codesandbox.io/s/bold-tree-ewxdu?file=/src/components/InputDialogFullKeyboard.vue](https://codesandbox.io/s/bold-tree-ewxdu?file=/src/components/InputDialogFullKeyboard.vue)

If you look in the components _FullKeyboard_ I essentially copied from your vue example. _InputDialogFullKeyboard_ is a component that just has the dialog with the two inputs and a keyboard. _SetupPage_ is where I pass in the props.

**Comment by hodgef** [comment]
Hello @ZaneL,

Here's a fixed version
https://codesandbox.io/s/strange-goldberg-p92sk?file=/src/components/SetupPage.vue

What was missing was an emitter that sends the new value to the parent when the dialog closed.

Hope that helps!
Francisco Hodge

**Comment by ZaneL** [comment]
Thank you so much!!

**Comment by PozziCode** [comment]
Hi @hodgef,
if while I select the text I leave the input it does not work correctly.
I noticed it in this [example](https://hodgef.com/simple-keyboard/editor/?d=simple-keyboard/simple-keyboard-preventmodefault-caret-pos/tree/master).
![bug](https://user-images.githubusercontent.com/39779328/103894514-55b0fb80-50ef-11eb-8334-49e78a3cae09.gif)
