### ISSUE TITLE
Is there a way to disable a key ( Enter Key )?

### ISSUE THREAD

**Issue by grimace** [hodgef/simple-keyboard#776]
I'm processing the Enter key and not allowing the keyboard to close when the user makes an invalid entry. I would like to be able to show the Enter key as disabled ( greyed out ),  if this is the case.  Do you have any suggestions for that?

**Comment by hodgef** [comment]
Hello @grimace,

Maybe the following ticket could help, it's the same request, but for the React version:
https://github.com/hodgef/react-simple-keyboard/issues/645

So you can definitely forbid clicks by giving the CSS `pointer-events: none` to your button. However if you want it to look disabled (grayed out) it could help to have actual button elements for buttons and then using the button attribute `disabled` as needed.

So the initial config (adapted from the React example) would be:

```
const keyboard = new Keyboard({
   useButtonTag: true
   ...
});
```

In your CSS you'd add this:
```
.hg-button[disabled] {
  pointer-events: none;
}
```

Then to disable and re-enable a button you'd do:
```
// disable
keyboard.setOptions({
   buttonAttributes: [
      {
          attribute: "disabled",
          value: "true",
          buttons: "{enter}"
      }
   ]
});


// Re-enable
keyboard.setOptions({
   buttonAttributes: null
});
```

Hope that helps,
Francisco Hodge
