### ISSUE TITLE
Using simple-keyboard with Svelte and Rollup not working

### ISSUE THREAD

**Issue by d-s-e** [hodgef/simple-keyboard#777]
I tried to create a svelte component providing simple-keyboard based on the plain JS example code, but unfortunately it is not working. I always get the following error in the browser:

> Uncaught TypeError: build is not a constructor

Maybe I'm missing something, any hints?

**Comment by hodgef** [comment]
Hello @d-s-e, I would need more details. For example to see how you are instantiating simple-keyboard. My guess is that you're missing the `new` keyword in `new Keyboard(...` but maybe it's something else. I would definitely need more details.

Thanks!
Francisco Hodge

**Comment by d-s-e** [comment]
This is my Keyboard component:

```
<script>
    import Keyboard from "simple-keyboard"

    let keyboard = new Keyboard({
        onChange: input => onChange(input),
        onKeyPress: button => onKeyPress(button)
    });

    function onChange(input){
        document.querySelector(".input").value = input;
        console.log("Input changed", input);
    }

    function onKeyPress(button){
        console.log("Button pressed", button);
    }
</script>

<input class="input" type="text" value="foo bar"/>
<div class="simple-keyboard"></div>

<style>
    @import 'simple-keyboard/build/css/index.css';
</style>
```

**Comment by hodgef** [comment]
Hello @d-s-e - So I've tried to create a Svelte sandbox myself but I wasn't able to do so. I haven't really used it before. Can you provide a sandbox or git repo with the full example? I can't see any mistake with the code provided.

Best,
Francisco Hodge

**Comment by d-s-e** [comment]
Here is an minimal svelte project including simple-keyboard:
https://github.com/d-s-e/svelte-simplekeyboard-test

**Comment by hodgef** [comment]
Hello @d-s-e, thanks for the test repo, it's very helpful.

I logged the Keyboard class, and here's what I see:
![image](https://user-images.githubusercontent.com/25509135/97506217-d2d22e80-1950-11eb-86b6-91e8673b4d44.png)

With Webpack we normally get the class directly, but here it's under the "default" property. It might be how Rollup packages things.

So to fix the issue, we change the import to this:
```
import SimpleKeyboard from 'simple-keyboard';
const Keyboard = SimpleKeyboard.default;
```

However, after we fix this we get a simple-keyboard error ([KEYBOARD_DOM_ERROR](https://hodgef.com/simple-keyboard/questions-answers/fix-keyboard-dom-error/)). It means that the instantiation was fired too early - before the DOM was ready.

![image](https://user-images.githubusercontent.com/25509135/97506610-bc78a280-1951-11eb-808f-0c99f662cd27.png)

To fix this, we need to instantiate the keyboard within [Svelte's onMount](https://svelte.dev/tutorial/onmount).

The keyboard now renders, but the style isn't right.

![image](https://user-images.githubusercontent.com/25509135/97507016-ac14f780-1952-11eb-947a-2081fefca5d4.png)

It seems that in this test repo the CSS import is not working. There might be plugins to import CSS with Rollup/Svelte that you might be missing. I'll let you check it out as this is not really a bug with the simple-keyboard library but just setup stuff.

Here are the full changes. Not including CSS import support that I mentioned.

```svelte
<script>
    import { onMount } from 'svelte';
    import SimpleKeyboard from 'simple-keyboard';
    const Keyboard = SimpleKeyboard.default;

    let keyboard;

    console.log('Keyboard', Keyboard);

    onMount(() => {
        keyboard = new Keyboard({
            onChange: input => onChange(input),
            onKeyPress: button => onKeyPress(button)
        });

        onInit();
    })

    function onInit(){
        console.log('keyboardInstance Loaded', keyboard);
    }

    function onChange(input){
        document.querySelector(".input").value = input;
        console.log("Input changed", input);
    }

    function onKeyPress(button){
        console.log("Button pressed", button);
    }
</script>


<input class="input" type="text" value="foo bar"/>
<div class="simple-keyboard"></div>


<style>
    @import '~/simple-keyboard/build/css/index.css';
</style>
```

Regards,
Francisco Hodge

**Comment by d-s-e** [comment]
Ah, ok, I tried it with onMount already, but as this was only one part of the solution, it couldn't work.
Yes, the CSS is a totally different topic, i think I can solve this.

Thank you very much!
