### ISSUE TITLE
Change button labels

### ISSUE THREAD

**Issue by ifyum** [hodgef/simple-keyboard#794]
I want to change the name of the "enter" and the "backspace"

**Comment by hodgef** [comment]
Hello @ifyum,

You can use the display option:

```
{
  display: {
    '{enter}': 'Enter label here',
    ...
  },
  mergeDisplay: true
}
```

https://hodgef.com/simple-keyboard/documentation/options/display/

Regards,
Francisco Hodge

**Comment by ifyum** [comment]
sorry for the inconvenience
what would be the correct way?
![image](https://user-images.githubusercontent.com/50993196/98558973-d5078780-2284-11eb-8906-ed285ff42124.png)

**Comment by hodgef** [comment]
Hello @ifyum, I linked the docs entry in the previous comment. Thanks!

**Comment by ifyum** [comment]
> sorry for the inconvenience
> what would be the correct way?
> ![image](https://user-images.githubusercontent.com/50993196/98558973-d5078780-2284-11eb-8906-ed285ff42124.png)

  layout: {
        default: [
          "7 8 9" ,
          "4 5 6",
          "1 2 3",
          "0 k",
          '{enter}'

        ]
        }
  
,
  display: {
    '{enter}': 'ENTER ',
    
  },
  mergeDisplay: true
