### ISSUE TITLE
format label

### ISSUE THREAD

**Issue by ifyum** [hodgef/simple-keyboard#795]
I want to give it a format, where the ninth number is separated by a hyphen
but when entering numbers by buttons it does not work, but the log says yes
![image](https://user-images.githubusercontent.com/50993196/98557546-1dbe4100-2283-11eb-8f49-a615f3276b37.png)

**Comment by hodgef** [comment]
Hello @ifyum, I'm not sure where that hyphen is coming from since it's not in your keyboard layout. However perhaps the input mask module might help.

Check out the docs:
https://hodgef.com/simple-keyboard/modules/input-mask/

Thanks,
Francisco Hodge
