### ISSUE TITLE
Is there a way to make every time you press a number also be like pressing enter?

### ISSUE THREAD

**Issue by xquitralx** [hodgef/simple-keyboard#796]
I have the following code
if (button === button)
      this.value=this.value.replace(/[.-]/g, '')
        .replace( /^(\d{1,2})(\d{3})(\d{3})(\w{1})$/, '$1$2$3-$4')

so that it gives a format to my "input" but ...
it only grants it when I hit enter
in this other way
(button === '7' ||
      button === "8" || button === "9" ||
      button === "4" || button === "5" ||
      button === "6" || button === "1" ||
      button === "2" || button === "3" ||
      button === "0" || button === "k"
    )
it didn't work either
### question
Is there a way to make every time you press a number also be like pressing enter?

**Comment by hodgef** [comment]
Hello @xquitralx,

Could you provide a test git repository or sandbox that shows the issue? This will help me understand the issue and to find a solution for this.

Thanks!
Francisco Hodge
