### ISSUE TITLE
Input value not visible when text is longer than the element width

### ISSUE THREAD

**Issue by Dunos** [hodgef/simple-keyboard#80]
**Simple-keyboard version**
2.21.0

**Describe the bug**
When typing some long content inside a small input field, once the input is full with content for the current width, you cannot see what you are typing. The expected behaviour should be like the normal input where the text scrolls once you reach the end on the field so you can actually see the characters you type in.

I made an example code here, just try to write a long text with the simple keyboard, and you will no longer see what you type --> https://codesandbox.io/s/simplekeyboardnpmdemos-jydqh

**Comment by hodgef** [comment]
Hello @Dunos,

If you have a small input element and run :

`input.value = "a very long string................."`,

You'll notice that the browser won't scroll to the end of that inserted string. This is the standard browser behavior, not something simple-keyboard is causing.

I agree that it would be nice for the browser to automatically scroll when a string is inserted through JS to an input, but for now it's something that we must implement ourselves.

**Check out this following issue, where I provide a sandbox with a workaround:**
https://github.com/hodgef/react-simple-keyboard/issues/45#issuecomment-479666675

The solution there is for `react-simple-keyboard`, but the relevant parts of the workaround (in the onChange method) will work in any project.

Let me know if you have any questions.

Regards,
Francisco Hodge
