### ISSUE TITLE
Alt and Fn keys in demo

### ISSUE THREAD

**Issue by bkmgit** [hodgef/simple-keyboard#801]
**Is your feature request related to a problem? Please describe.**

Many languages have more characters than can be accessed through a two layer keyboard. In addition, when typing in multiple languages, it can be helpful to not have to change keyboard type frequently.

**Describe the solution you'd like**

Many keyboards used in Linux have upto 4 symbols per key, usually accessed through using the Alt Gr key. It may be helpful to add this functionality to the demonstrations to easily enable addition of other languages.

**Describe alternatives you've considered**

**Additional context**
See 
* https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/tree/master/symbols
* https://github.com/keymanapp/keyboards

**Comment by hodgef** [comment]
Hey @bkmgit,

I think this would be excellent to have. My thinking is that this feature could come in handy as a [module](https://hodgef.com/simple-keyboard/modules/). However, I don't think I'll have much time to implement it soon.

I'll move this into the Enhancements project so I can pick this up whenever I have more time.

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
The new `layoutCandidates` option (available in v3) shows suggestions when you press a key. While not exactly the same as adding "Alt" of "Fn" keys, this might help address the use-case.

https://hodgef.com/simple-keyboard/documentation/options/layoutcandidates/

![image](https://user-images.githubusercontent.com/25509135/111923089-ca9b9c80-8a73-11eb-9f1d-0d1fe103df05.png)
