### ISSUE TITLE
Multiple keyboards on one HTML page in plane javaScript ?

### ISSUE THREAD

**Issue by seAfnan** [hodgef/simple-keyboard#806]
How can we declare multiple keyboards in one HTML page with different className in plane javaScript ?bcz I can declare only one keyboard in one HTML page with " .simple-keyboard " class...

**Comment by hodgef** [comment]
Hello @seAfnan,

Check out this Q&A entry:
https://hodgef.com/simple-keyboard/questions-answers/give-different-base-class-keyboard/

Regards,
Francisco Hodge
