### ISSUE TITLE
just erase the last number with mask

### ISSUE THREAD

**Issue by xquitralx** [hodgef/simple-keyboard#809]
https://twwx2.csb.app/ sanbox link

when I want to delete a number chosen by the cursor it only deletes the last one but this only happens with an "inputmask"

I need to use the mask but I also want that when I choose a number with the course, only that number is deleted and not the last one

**Comment by hodgef** [comment]
Hello @xquitralx,

When you open your Dev Tools, it'll tell you this
![image](https://user-images.githubusercontent.com/25509135/99542343-f1d84500-297f-11eb-8c35-feccb8df924c.png)

>SimpleKeyboardInputMask: Caret placement is not supported in this release. Option disableCaretPositioning will be enabled. To disable this warning, set option disableCaretPositioning to true.

Regards,
Francisco Hodge

**Comment by xquitralx** [comment]
delete the mask and pass the same, it is any type of format to the input
