### ISSUE TITLE
Demo not working in IPad Air

### ISSUE THREAD

**Issue by sfasp** [hodgef/simple-keyboard#813]
**Simple-keyboard version**
The used by the demo site (https://hodgef.com/simple-keyboard/demos/)

**Describe the bug**
On IPad Air / Software 12.4.9 / Safari or Chrome (86.0.4240.93) browsers:
  - for the demo "default":
       - keys are not highlighted
       - shift and caps do not work
  - for the demo "darkTheme":
       - shift and caps do not work

Aside from that, it is an amazing work. Thank you!

**Comment by hodgef** [comment]
Hello @sfasp,

I think simple-keyboard does work on iPad (based on issue #2), so this might be an issue only limited to the demo.

Unfortunately, I don't have a test device to debug this, and everything seems fine on Chrome's device emulator. I'll add this to my Bugs backlog and revisit this when I get ahold of a test device.

Thank you,
Francisco Hodge
