### ISSUE TITLE
Show keyboard only when user type input and hide options.

### ISSUE THREAD

**Issue by Naveed1842** [hodgef/simple-keyboard#821]
Hi does the simple keyboard has the feature to visible only when user type input on the screen?If there is already feature please let me know.In case of non-availability please let me know how much time require to develop this feature.

**Comment by hodgef** [comment]
Hello @Naveed1842,

In the Question and Answers section of the docs there are some examples of visibility toggling:
https://hodgef.com/simple-keyboard/questions-answers/implement-show-hide-toggling/

Feel free to take these examples and adapt them to your needs.

Regards,
Francisco Hodge
