### ISSUE TITLE
Do you have any suggestions for referencing the keyboard globally

### ISSUE THREAD

**Issue by skyunBoss** [hodgef/simple-keyboard#832]
I want to click the input in the project to directly pop up the keyboard instead of introducing no components

**Comment by hodgef** [comment]
Hey @skyunBoss,

That really depends on your implementation. One way is to attach an onFocus event to your inputs that would in turn instantiate (or display) the keyboard.

Something like this: https://github.com/hodgef/simple-keyboard/issues/340#issuecomment-563493815

Or this (Vue): https://codesandbox.io/s/demo-nuxt-spa-simplekeyboard-vuex-wi3kk?file=/layouts/default.vue

Feel free to try it out, and if you come across any bugs I can help.

Thanks,
Francisco Hodge

**Comment by skyunBoss** [comment]
need react example

**Comment by skyunBoss** [comment]
> Hey @skyunBoss,
> 
> That really depends on your implementation. One way is to attach an onFocus event to your inputs that would in turn instantiate (or display) the keyboard.
> 
> Something like this: [#340 (comment)](https://github.com/hodgef/simple-keyboard/issues/340#issuecomment-563493815)
> 
> Or this (Vue): https://codesandbox.io/s/demo-nuxt-spa-simplekeyboard-vuex-wi3kk?file=/layouts/default.vue
> 
> Feel free to try it out, and if you come across any bugs I can help.
> 
> Thanks,
> Francisco Hodge

need react example
