### ISSUE TITLE
Key Navigation & preventMouseDownDefault throws error

### ISSUE THREAD

**Issue by bjoerndot** [hodgef/simple-keyboard#844]
**Simple-keyboard version**
simple-keyboard: 2.32.57
simple-keyboard-key-navigation: 2.3.81

**Describe the bug**
```
this.keyboard = new Keyboard({
    onChange: input => this.onKeyboardChange(input),
    onKeyPress: button => this.onKeyboardKeyPress(button),
    preventMouseDownDefault: true,
    enableKeyNavigation: true,
    modules: [
        keyNavigation
    ]
});
```

With both **preventMouseDownDefault** and **stopMouseDownPropagation** an error occurs if a key on the keyboard is written through the physical keyboards enter-key. 
Error:

**ERROR TypeError: Cannot read property 'preventDefault' of undefined**

This seems to be a problem in the **handleButtonMouseDown**-function which is called by the key-navigation modules **onpointerdown**-function. 
Locally I can fix it by chaning the following:

Current Code:
```
if (this.options.preventMouseDownDefault) e.preventDefault();
if (this.options.stopMouseDownPropagation) e.stopPropagation();
```

Changed Code:
```
if (this.options.preventMouseDownDefault && e) e.preventDefault();
if (this.options.stopMouseDownPropagation && e) e.stopPropagation();
```

**Comment by hodgef** [comment]
Thank you for the detailed report @bjoerndot !

The issue should now be fixed as of version 2.32.66. Feel free to check it out.

Regards,
Francisco Hodge
