### ISSUE TITLE
Can you demo how to use with tinymce ?

### ISSUE THREAD

**Issue by caominhsg** [hodgef/simple-keyboard#849]
Can you demo how to use with tinymce ?

**Comment by hodgef** [comment]
Hello @caominhsg,

Sorry, I currently don't have a demo on how to use with tinymce. However simple-keyboard provides ways to get and set its values.

These are simple-keyboard integration points:

- It outputs through [`onKeyPress`](https://hodgef.com/simple-keyboard/documentation/options/onkeypress/), [`onChange`](https://hodgef.com/simple-keyboard/documentation/options/onchange/) and [`keyboard.getInput()`](https://hodgef.com/simple-keyboard/documentation/methods/getinput/).
- It takes input through [`keyboard.setInput()`](https://hodgef.com/simple-keyboard/documentation/methods/setinput/) and [`keyboard.replaceInput()`](https://hodgef.com/simple-keyboard/documentation/methods/replaceinput/)

You would need to investigate whether tinymce also provides a way (methods or options) to send in input and receive updated input programmatically, so you can do the syncing. That would apply to any library you'd like to integrate, not just tinymce.

If you integrate it and come across any problems, feel free to create an issue and I'll have a look.

Regards,
Francisco Hodge

**Comment by caominhsg** [comment]
The problems is if I use tinymce, its not received any text when I click on virtual keyboard button but text area is fine. Its not work with visual text editor.

**Comment by hodgef** [comment]
What's your current implementation? For example: How are you sending simple-keyboard's `onChange` value to tinymce?

**Comment by caominhsg** [comment]
I just implement normal. When not install tinymce plugin. it works fine with text area. But when I active tinymce plugin. It received nothing. So I guest due to visual editor of tinymce blocked. I used tinymce version 5
