### ISSUE TITLE
Binding NgModel with Simple Keyboard.

### ISSUE THREAD

**Issue by Naveed1842** [hodgef/simple-keyboard#851]
Hi
Please see the below snippet
![Screen Shot 2020-12-30 at 7 22 39 AM](https://user-images.githubusercontent.com/22956528/103325927-dfb5f000-4a6f-11eb-84de-5e4ac0639f57.png)

The problem I am facing is how to set ngModel. I noticed the inputs values are setup but they are not binding to [(ngModel)]

**Comment by hodgef** [comment]
Hello @Naveed1842,

I would like to help, but an image likely won't be enough. Do you happen to have a demo repository or sandbox where I can debug this? I'll reopen the ticket as soon as I get a repro.

Regards,
Francisco Hodge

**Comment by Naveed1842** [comment]
Hi @hodgef  sorry for late reply.Here is repo I created and added instruction in code.
https://github.com/Naveed1842/SimpleKeyboardModelBindingIssue
As discussed earlier need an auto way so we value can bind auto.Currently values are not binding to Model.Please run the angular repo.

**Comment by hodgef** [comment]
Hey @Naveed1842, thanks for the demo!

I've updated the Angular multiple inputs demo to use ngModel. Here's the link:

https://codesandbox.io/s/github/simple-keyboard/simple-keyboard-angular-multiple-inputs/tree/master/?from-embed=&file=/src/app/app.component.ts

Feel free to take that as a base and adapt it to your needs.

Just a note, when you give an initial value to your inputs, you must sync these with simple keyboard by using  [`keyboard.setInput()`](https://hodgef.com/simple-keyboard/documentation/methods/setinput/) or [`keyboard.replaceInput()`](https://hodgef.com/simple-keyboard/documentation/methods/replaceinput/).

Regards,
Francisco Hodge
