### ISSUE TITLE
checkbox change error

### ISSUE THREAD

**Issue by skyunBoss** [hodgef/simple-keyboard#855]
![9DDCD8B2-78D3-4b46-B36B-299FA23756C9](https://user-images.githubusercontent.com/29365288/103510530-64ee3a00-4ea0-11eb-9a6d-94227e155116.png)
![64FEFD7E-4F37-4199-8E8F-6B6553F7A063](https://user-images.githubusercontent.com/29365288/103510539-6a4b8480-4ea0-11eb-8981-29758a1a4470.png)

**Comment by hodgef** [comment]
Hello @skyunBoss,

I wasn't able to reproduce this on Chrome 87. However I've added a fix which I hope works in your case.

Feel free to upgrade to the latest simple-keyboard or react-simple-keyboard version (depending on which one you're using).

Thanks!
Francisco Hodge

**Comment by skyunBoss** [comment]
chrome 49

**Comment by hodgef** [comment]
Yeah updating Chrome will probably fix it. But if you don't want to update you can install the latest simple-keyboard and hopefully that'll fix it for you. Regards

**Comment by hodgef** [comment]
@skyunBoss I'll download Chrome 49 later today to see if I can reproduce the issue

**Comment by skyunBoss** [comment]
> @skyunBoss I'll download Chrome 49 later today to see if I can reproduce the issue

thank you very much

**Comment by hodgef** [comment]
I was able to confirm this issue in Chrome 49. This is now fixed as of simple-keyboard@2.32.128.

Thanks!
Francisco Hodge
