### ISSUE TITLE
Keyboard not resizing properly on resolutions < 400

### ISSUE THREAD

**Issue by Ardyey** [hodgef/simple-keyboard#856]
**simple-keyboard v2.32.71**

**Bug**
As you can see in the screenshot below, the keyboard starts to clip the buttons when the resolution of the screen is lower than 400. In the screenshot, the resolution is 360. Same can be said with the height, but height doesn't matter that match. Width is the one that is important.

The reason why I'm implementing this in lower resolutions is because I'm trying to integrate this beautiful keyboard into an HTML5 Game, and we need to handle mobile devices with resolutions lower than 400.

**Thoughts**
Is there a minimum size implemented for the buttons? If so, is there any way we can manually disable it so that they will continue to resize regardless?

**Screenshots**
Resolution = 360x640 (Chrome Devtools, Moto G4)
![image](https://user-images.githubusercontent.com/35645526/103521172-4b0a2280-4eb3-11eb-814f-52a1f9c446e2.png)

Resolution = 375 x 812 (Chrome Devtools, Iphone X)
![image](https://user-images.githubusercontent.com/35645526/103521342-8c9acd80-4eb3-11eb-94d1-f06f6d92fad9.png)

Resolution = 393 x 784 (Actual Device, Xiaomi Pocophone F1)
![image](https://user-images.githubusercontent.com/35645526/103522685-afc67c80-4eb5-11eb-8096-e9946841aec3.png)

**Comment by hodgef** [comment]
Hello @Ardyey,

There's no minimum size implemented, but the buttons cannot be smaller than the text they contain.

What you can do is to switch to a [mobile-style layout](https://hodgef.com/simple-keyboard/demos/?d=mobile) when your screen size reaches mobile size, just like it's done on https://virtual-keyboard.js.org/.

Regards,
Francisco Hodge

**Comment by ricjonsu-impact360** [comment]
Sweet. Definitely the best virtual keyboard there is.

**Comment by Ardyey** [comment]
Sweet. Definitely the best virtual keyboard there is.

**Comment by hodgef** [comment]
Thanks a lot ! It's very appreciated. If you come across any issues don't hesitate to reach out 👍
