### ISSUE TITLE
Event penetration

### ISSUE THREAD

**Issue by skyunBoss** [hodgef/simple-keyboard#872]
My page has a modal, there is a keyboard in the modal, triggering the OK key of the keyboard will trigger the event under the mask

**Comment by hodgef** [comment]
Hello @skyunBoss,

You can try using the options [`useMouseEvents`](https://hodgef.com/simple-keyboard/documentation/options/usemouseevents/) or [`stopMouseDownPropagation`](https://hodgef.com/simple-keyboard/documentation/options/stopmousedownpropagation/).

Hope that helps,
Francisco Hodge
