### ISSUE TITLE
Input field value with special character input at end or start showing in wrong direction for RTL

### ISSUE THREAD

**Issue by soumen-cn** [hodgef/simple-keyboard#876]
**Simple-keyboard version**
"simple-keyboard": "^2.31.4"

**Describe the bug**
If I type any special character at the start and end of Hebrew text from the Hardware keyboard in an input field the value of the input field direction showing wrong.

HTML code
```
<input class="txtbox"
style="text-align: right; direction: rtl;"
type="text" [value]="item.text"
(input)="inputChange($event, i)">
```
TS code

```
inputChange(event: any, i) {
    console.log(event.target.value); // showing wrong direction text
      if (this.keyboard) {
        this.keyboard.setInput(event.target.value);
      }
      this.onChange(event.target.value);
   }
```

Keyboard initialize

```
this.keyboard = new Keyboard(`simple-keyboard${i}`, {
  rtl: true,
  onChange: (input) => this.onChange(input),
  onKeyPress: (button) => this.onKeyPress(button),
  layout: hebrew,
});
```
**Screenshots**
Please check the screenshot input field and console

![Screenshot 2021-02-02 at 5 04 31 PM](https://user-images.githubusercontent.com/56528088/106595777-0f2db000-657a-11eb-8da2-0ea69c0fdcd2.png)

**Comment by hodgef** [comment]
Hello @soumen-cn,

I'm not completely sure I understand the issue. To provide a bit of context, simple-keyboard's internal value of the input will always be LTR. We leave the task to render as RTL to the browser (through CSS `direction: rtl`, etc).

For more information on the rtl option, check out this page:
https://hodgef.com/simple-keyboard/documentation/options/rtl/

Regards,
Francisco Hodge
