### ISSUE TITLE
Problem to run angular project with simple-keyboard

### ISSUE THREAD

**Issue by rodrifmed** [hodgef/simple-keyboard#89]
What I did was execute "npm install simple-keyboard --save"

and after I ran my app I received this erro:
 

> 
>  ERROR  Failed to compile with 35 errors                                                                                                                   3:49:41 PM
> 
> These dependencies were not found:
> 
> * child_process in ./node_modules/protractor/built/runner.js, ./node_modules/protractor/built/debugger.js and 4 others
> * fs in ./node_modules/blocking-proxy/built/lib/webdriver_logger.js, ./node_modules/fs.realpath/index.js and 21 others
> * net in ./node_modules/https-proxy-agent/index.js, ./node_modules/protractor/built/debugger.js and 1 other
> * repl in ./node_modules/protractor/built/debugger.js
> * tls in ./node_modules/https-proxy-agent/index.js
> 
> To install them, you can run: npm install --save child_process fs net repl tls
> 
> 
> This relative module was not found:
> 
> * ./lib-cov/SauceLabs in ./node_modules/saucelabs/index.js

**Comment by hodgef** [comment]
Hello @rodrifmed ,

I'll do a fresh install from `angular-cli` and try to reproduce the issue. I'll update this in a bit.

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
Hello @rodrifmed ,

I was not able to reproduce the issue on a fresh Angular 8 install. This specific issue seems to be related to your project setup. I'd recommend heading over to the angular-cli page and getting a fresh install.

https://cli.angular.io/

![image](https://user-images.githubusercontent.com/25509135/58518445-40d35e80-817d-11e9-9dac-684a973d8470.png)

Regards,
Francisco Hodge

**Comment by rodrifmed** [comment]
Hi Francesco,

I`m using webpack, maybe this is the problem with your lib?

regards,

Rodrigo Medeiros

**Comment by rodrifmed** [comment]
Hi Francesco,

It is my fault I was importing a wrong lib

thanks for your fast reply!

regards,

Rodrigo Medeiros

**Comment by hodgef** [comment]
Glad to hear that it works now! Feel free to reach out if you have any other issues :)
