### ISSUE TITLE
Keyboard inside of iframe 

### ISSUE THREAD

**Issue by nicoagp** [hodgef/simple-keyboard#891]
Hi, is there any way to use the keyboard inside of an iframe ? I am using stripe elements and the fields are inserted inside of an iframe. Any solution, hack or alternative ? thanks
![Screen Shot 2021-02-17 at 9 20 49 pm](https://user-images.githubusercontent.com/28281438/108191875-c07e3980-7167-11eb-966f-49718377ed8b.png)

**Comment by hodgef** [comment]
Hello @nicoagp, could you share a test git repository that shows the issue? I think this is something that would need to be fixed within the application.

Regards,
Francisco Hodge
