### ISSUE TITLE
Move to Next input field on Enter

### ISSUE THREAD

**Issue by rgrokett** [hodgef/simple-keyboard#897]
I have a multiple input fields form with 6 input fields and using the "Simple-keyboard with multiple inputs" example which works fine when I click on each field then input using the simple-keyboard.  

But I want to jump to the next input field when the user clicks the Enter key and/or Tab key instead of having to click on each specific input field.  

I am using the JS (CDN) version code. 

```
function onKeyPress(button) {
  if (button === "{enter}" || button === "{tab}") handleNextField();  
}

function handleNextField() {      // Move to next input field 
  keyboard.?? 
}
```

``` 
<input id="default" class="input" placeholder="Input 1" /> 
<input id="input2" class="input" placeholder="Input 2" /> 
<input id="input3" class="input" placeholder="Input 3" /> 
...
	<div class="simple-keyboard"></div>
```

Thanks for any help!

**Comment by hodgef** [comment]
Hello @rgrokett,

This is a functionality that you would need to do custom for your app. One approach would be to fetch all inputs with `document.querySelectorAll(".input")` which will give you an array of inputs. You could then focus any of them as needed.

Here's some (untested) code. It's rather incomplete, but it's just to give an idea:

```js
const inputs = document.querySelectorAll(".inputs");
const inputIndex = 0;
const inputName = inputs[inputIndex].id; // For simple-keyboard

const keyboard = new Keyboard({ inputName });

const selectCurrentInput = () => {
  if(inputs[inputIndex]){
    keyboard.setOptions({ inputName: input[inputIndex].id });
    input[inputIndex].focus();
  }
}

selectCurrentInput();

const handleNextField = () => {
  inputIndex++;
  selectCurrentInput();
}
```

Hope that helps,
Francisco Hodge
