### ISSUE TITLE
Backspace always deletes last character

### ISSUE THREAD

**Issue by chhunchha** [hodgef/simple-keyboard#9]
Backspace key is always deleting last character.
Steps to reproduce:

'|' is showing cursor position

Type few characters for example - "REACT|"
move cursor in between some where - for example - "REA|CT"
Press backspace - it deletes 'T' rather than 'A'

**Comment by hodgef** [comment]
Hello @chhunchha,

Currently text is appended only. However, adding text from the cursor is on the Roadmap.
https://github.com/hodgef/simple-keyboard/wiki/Roadmap

I can't guarantee a delivery date for this, but rest assured this is acknowledged and will ship soon.

Regards

**Comment by hodgef** [comment]
Now supoorted !

https://github.com/hodgef/react-simple-keyboard/issues/5#issuecomment-427621984
