### ISSUE TITLE
Not working with contenteditable elements

### ISSUE THREAD

**Issue by vPolyovyj** [hodgef/simple-keyboard#908]
As I understand the problem is here
https://github.com/hodgef/simple-keyboard/blob/master/src/lib/components/Keyboard.js#L848
Is there any workaround?

For now I'am manually setting caret with window.getSelection() and document.createRange()... It's a bit tricky and does not work properly with CKE5, only with simple editable elements.

**Comment by hodgef** [comment]
Hello @vPolyovyj,

Simple-keyboard is not meant for handling ContentEditable elements, I wouldn't recommend using it for that purpose.

If you still want to go that route, I'd suggest creating a module and overriding simple-keyboard's `caretEventHandler` method. 

Here's an example, feel free to adapt it to your needs:
https://codesandbox.io/s/suspicious-franklin-pviwx?file=/src/index.js

Regards,
Francisco Hodge
