### ISSUE TITLE
Vue code sandbox breaks with custom `keyboardClass`

### ISSUE THREAD

**Issue by maxshuty** [hodgef/simple-keyboard#910]
**Simple-keyboard version**
Latest

**Describe the bug**
The [Vue code sandbox](https://codesandbox.io/s/github/hodgef/vue-simple-keyboard/tree/master/?from-embed=&file=/src/SimpleKeyboard.vue) has a prop called `keyboardClass` which gives the impression you can pass it whatever you class you want. As you can see, [this does not work](https://codesandbox.io/s/keen-sanderson-m9voy?file=/src/SimpleKeyboard.vue). I was passing a custom class to this and after 30 minutes of trying to debug why the `simple-keyboard` was not loading for me, I realized it was because I was passing a custom class for this `prop`. It makes sense that this class should stay the same, otherwise how would the plugin know what to work off of?

It should just be a class on that `div` element, like this `<div class="simple-keyboard"></div>` to prevent confusion. [Here is an example](https://codesandbox.io/s/competent-northcutt-gb1l1?file=/src/SimpleKeyboard.vue) of what I mean. The [baseClass](https://hodgef.com/simple-keyboard/documentation/options/baseclass/) option is only currently available for react, but it would be neat to be able to do something like this in Vue `<div class="simple-keyboard" :class="customKeyboardClass"></div>` then you could still get the functionality of the custom class that is passed via `prop`s while maintaining the class that is needed to instantiate the plugin.

Really my only request here would be to update the pen to prevent confusion for those of us using Vue. 

Thanks for the awesome plugin!

**Comment by hodgef** [comment]
Hey @maxshuty,

I've pushed [this commit](https://github.com/simple-keyboard/vue-simple-keyboard/commit/ba6f7ce01cfe51c1f1d62ebd25660b429159f3df) to the main Vue sandbox which should fix the issue.

https://codesandbox.io/s/github/hodgef/vue-simple-keyboard/tree/master/?from-embed=&file=/src/SimpleKeyboard.vue

One heads up though is that the issue might be present in other Vue demos - It'll take me a bit longer to get to those.

Thanks!
Francisco Hodge

**Comment by maxshuty** [comment]
Awesome thank you, really appreciate how responsive you are with all of these requests.
