### ISSUE TITLE
Is 'Cap' button function already supported?

### ISSUE THREAD

**Issue by yzy0704YZY** [hodgef/simple-keyboard#916]
**Is your feature request related to a problem? Please describe.**
Currently nothing happens when clicking on the 'Cap'

**Describe the solution you'd like**
After clicking on the 'Cap', it should give us at least one chance to type a capital letter.

**Comment by yzy0704YZY** [comment]
Or maybe it's already solved in latest...I am still using v2_30_5

**Comment by hodgef** [comment]
Hello @yzy0704YZY,

Do you mean the `caps` button? It seems to be working in the main demo:
https://codesandbox.io/s/github/hodgef/simple-keyboard-npm-demos/tree/master/?from-embed

Feel free to check out the code in that sandbox for reference.

Regards,
Francisco Hodge
