### ISSUE TITLE
buttonTheme does not work with {shift}

### ISSUE THREAD

**Issue by hunterpp** [hodgef/simple-keyboard#929]
First, thank you for making such a great thing!!!

**Simple-keyboard version**
v2.28.35

**Describe the bug**
I believe that buttonTheme does not work with {shift}

**Comment by hodgef** [comment]
Hey @hunterpp,

Applying a class to `{shift}` through `buttonTheme` seems to work. Here's a sandbox demo:
https://codesandbox.io/s/simple-keyboard-npm-demos-forked-94r7u?file=/src/index.js

If you still have the issue, could you show it in a demo sandbox? I'll reopen the ticket and continue investigating once I get the repro.

Thanks!
Francisco Hodge
