### ISSUE TITLE
Is it possible to have a layout other than shift?

### ISSUE THREAD

**Issue by hunterpp** [hodgef/simple-keyboard#930]
Hi Francisco, I don't know where else to ask.
I want a layout for example for when alt is pressed.

I have tried: 

layout: {
  altleft: ["A X"]
}

and

layout: {
  alt: ["A X"]
}

Both produce no results. I am inspecting code, but wondering if you have any advice? Thank you.

**Comment by hodgef** [comment]
Hey @hunterpp,

The layout switching is handled in your `onKeyPress` function. Here's an example with `shift` and `caps` layouts:

https://hodgef.com/simple-keyboard/editor/?d=hodgef/simple-keyboard-npm-demos/tree/uc-shiftandcaps

Regards,
Francisco Hodge

**Comment by hunterpp** [comment]
Thank you Francisco!!! 🙌
