### ISSUE TITLE
Add  Chinese mode with pinyin

### ISSUE THREAD

**Issue by Dante-dan** [hodgef/simple-keyboard#95]
**Is your feature request related to a problem? Please describe.**
I can't add some Chinese words

**Describe the solution you'd like**
Add the options to choose the words or phrase.

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by hodgef** [comment]
@Dante-dan ,

This option is called `layouts` and can be found at the beginning of the docs.
https://simple-keyboard.com/documentation/

Regards,
Francisco Hodge
