### ISSUE TITLE
Strongly coupled input element and keyboard

### ISSUE THREAD

**Issue by okeoke85** [hodgef/simple-keyboard#950]
**I want to use keyboard coupled with input element**
I guess your design aims to be used one keyboard component for entire application, i want to use it coupled with input element and manage seperate text-input variables for every input element, as far as i see keyboard tries to manage of input value which is focused at t moment. 

**Keyboard input couple, input html element as option parameter**

Is there a option like Keyboard.input = fooInput; when you are building keyboard component, i want to use multiple input-keyboard couples, i want  some of my inputs dont have keyboard entry option, entry shuld only be with phisycal keyboard

Keyboard layouts are best and rtl solution is perfect thanks in advance.

Best Regards.

**Comment by hodgef** [comment]
Hello @okeoke85,

The simple-keyboard library actually doesn't manage input elements. You have to tell it where to send the input.

You can see this in demos, such as the multiple inputs demo:
https://hodgef.com/simple-keyboard/questions-answers/use-simple-keyboard-multiple-inputs/

In that demo, we tell simple-keyboard to track a different value when an input is focused. You can adapt this to any requirement you have, but this of course requires some dev effort.

If you're looking for a keyboard that couples to an input out of the box, perhaps another library would better fit that use-case.

Regards,
Francisco Hodge
