### ISSUE TITLE
WebPack 5 and old chrome (webview 38)

### ISSUE THREAD

**Issue by oreons** [hodgef/simple-keyboard#954]
**Simple-keyboard version** 3.0.0

**Describe the bug**
In webpack 5, to support older versions of browsers, necessary to include in webpack.config.js option: `target: ["es5"]`.
Otherwise, webpack will use a new syntax in the final bundle (for example, the **_const_** keyword). Some older versions of chrome, such as 38, don't understand the new syntax and throw an error.
Unfortunately, these webview versions are still used in industrial devices running Android 4.1. When running program with keyboard module on such a device, the error "_Uncaught SyntaxError: Use of const in strict mode._"
You can read about it here: https://webpack.js.org/migrate/5/#need-to-support-an-older-browser-like-ie-11
If you need an old browser for the test, you can download it here: https://www.googleapis.com/download/storage/v1/b/chromium-browser-continuous/o/Win%2F288629%2Fchrome-win32.zip?generation=1407723831493000&alt=media

![Image 1](https://user-images.githubusercontent.com/61789749/112643124-11fba180-8e55-11eb-9df1-714307d588f4.png)

**Comment by hodgef** [comment]
Hey @oreons,

The demos site is not compatible with older browsers, because it's meant for devs.

However, the simple-keyboard library [is compatible with older browsers](https://github.com/hodgef/simple-keyboard/blob/master/babel.config.js#L6).

You can run the following demo in an old supported browser (such as Internet Explorer 11) to verify:
https://hodgef.com/static/simple-keyboard-test-ie.html

Regards,
Francisco Hodge

**Comment by oreons** [comment]
Thanks for the answer.
I tested the keyboard on a separate empty project of mine. The trouble is that this extremely unfortunate and buggy version of webview 38, which is installed on industrial terminals, works even worse than internet explorer 11. Chinese terminals cannot be updated to new versions of webview and I have to adjust the software to support them. I compiled the simple-keyboard project locally and if I don't add the target: ["es5"] option, it won't run on webview 38.
![Image 2](https://user-images.githubusercontent.com/61789749/112647780-eb8c3500-8e59-11eb-8fb5-b2acc1198e08.png)

**Comment by hodgef** [comment]
Oh! Sorry - I did use const in that IE demo. Just changed it to `var`. Could you try again?
https://hodgef.com/static/simple-keyboard-test-ie.html

Regards,
Francisco Hodge

**Comment by oreons** [comment]
There's also "let" in html)
But the first error is due const inside index.js
![Image 3](https://user-images.githubusercontent.com/61789749/112650283-44f56380-8e5c-11eb-9c71-abeb94a3e0f8.png)
![Image 4](https://user-images.githubusercontent.com/61789749/112650291-4757bd80-8e5c-11eb-89f3-db94afc2fdc5.png)

**Comment by hodgef** [comment]
Interesting... Thanks for the heads up!

**Comment by hodgef** [comment]
Hey @oreons,

This issue should be fixed in the newly published simple-keyboard@3.0.19. I've also updated the [Internet Explorer demo](https://hodgef.com/static/simple-keyboard-test-ie.html).

Let me know if you're still having this issue!

Regards,
Francisco Hodge

**Comment by oreons** [comment]
Thank you very much , now its works!
