### ISSUE TITLE
Property 'inputName' in clearInput() method isn't set optional

### ISSUE THREAD

**Issue by BernhardBehrendt** [hodgef/simple-keyboard#959]
**Simple-keyboard version**
Version: 3.0.20 (also in master)

**Description:**
When calling `simpleKeyboard.clearInput()` inside a Typescript project with those compilerOptions:

```json
{
  [...]
  },
  "compilerOptions": {
    [...]
    "strict": true
  }
}
```

 the following error occurs:

**TS2554: Expected 1 arguments, but got 0.** 

**Screenshot:**
![Bildschirmfoto 2021-03-29 um 21 35 45](https://user-images.githubusercontent.com/1717382/112890115-c0fae000-90d6-11eb-94c0-3b43045b5703.png)

**Comment by hodgef** [comment]
Should be fixed as of v3.0.22, please feel free to update. Thanks!
