### ISSUE TITLE
physicalKeyboardHighlightPress makes multiple presses

### ISSUE THREAD

**Issue by tuomassa** [hodgef/simple-keyboard#987]
**Simple-keyboard version**
Vue, 2.32.62, but also happens in your playground which is master?

**Describe the bug**
having
```
physicalKeyboardHighlight: true
physicalKeyboardHighlightPress: true
```
causes physical button to make multiple entries. Usually 2 characters, but sometimes the amount increases every time I create the component.
**Screenshots**

**Comment by hodgef** [comment]
Hello @tuomassa,

I can't seem to reproduce this in the latest version. I could only repro it in codesandbox which I assume was using a cached version. Once I forked the sandbox the issue disappeared:

https://codesandbox.io/s/blissful-wood-86mpk?file=/src/index.js

Could you update to the latest version and try again?

Regards,
Francisco Hodge

**Comment by tuomassa** [comment]
I updated to 3.0.0 and the issue remains. Also forking the codesandbox (with cache disabled too) doesn't help, it always inputs double characters.

On my application the amount of extra characters appearing per keypress increases by one every time the keyboard is created. It goes back to one on full page refresh, and then starts again increasing every time it is created.

Also,
Pressing capslock/shift on physical keyboard, doesn't turn on caps on sandbox, but I get capital letters, ONE per keypress, as expected.

**Comment by hodgef** [comment]
Hey @tuomassa,

I took another look at the sandbox. Sadly I'm still not able to repro. Could you provide a test git repo of your app that has the issue? 

![test](https://user-images.githubusercontent.com/25509135/116438084-192f1a00-a81c-11eb-96ea-e12b8031d341.gif)

Also, if you have to recreate the component, you can call [keyboard.destroy()](https://hodgef.com/simple-keyboard/documentation/methods/destroy/) first to make sure the listeners are removed.

Regards,
Francisco Hodge

**Comment by tuomassa** [comment]
Hi, can you try with the text field selected? So that the caret is visible. That might be the problem.

**Comment by hodgef** [comment]
I see, in that case it's the effect of typing into the input + having simple-keyboard also type into it.

The increasing character amount will probably be fixed by calling keyboard.destroy() before re-instantiating simple-keyboard.

**Comment by kalnode** [comment]
I experienced the same issue as OP, but solved with below.
Perhaps it was solved elsewhere, years onward.
```
physicalKeyboardHighlight: true,
physicalKeyboardHighlightPress: true,

// Add one more property to fix double-event when using physical keyboard:
physicalKeyboardHighlightPressUseClick: true
```
